### ISSUE TITLE
API response format change between 3.5.6 and 3.5.7

### ISSUE THREAD

**Issue by jippi** [rabbitmq/rabbitmq-management#100]
Hey,

First of all, thanks for an amazing project - we use it very happily, and generally without any problems at bownty! :)

Some of our internal tooling broke when we upgraded from 3.5.6 to 3.5.7 - due to the default value change for `consumer_utilisation` 

In 3.5.6 - the value was `""` (empty string) if there was no utilization, where in the 3.5.7 the response is `null`

While the change is suttle, its causing our auto-scale code change in weird ways (we use python-diamond/diamond) - that doesn't emit `null` values, but do emit empty string values as `0`  ( https://github.com/python-diamond/Diamond/blob/master/src/collectors/rabbitmq/rabbitmq.py#L241 ) 

I'm in no way an erlang developer, but seems like the offender could be commit 2fdb3130d0f95eb391029f0f3585e17672ed9872 

Can we either change it back to `""` - or maybe even better, output a `0` when there is messages and no consumers - instead of `"" `

Thanks

**Comment by michaelklishin** [comment]
`null` makes a lot more sense to us than an empty string. We won't be changing it back and `3.5.x` will see no future releases.

`0` isn't quite correct when there is no utilisation to report (e.g. no consumers). `null` should be reasonably easy to handle in any client.

**Comment by jippi** [comment]
But its a breaking change in a patch verison - i would have been fine with this in the changelog and a major / minor version bump - but a response change like that in a patch version doesn't seem fair or semver friendly?

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-management/commit/2fdb3130d0f95eb391029f0f3585e17672ed9872 will be in `3.7.0` and certainly didn't make it into `3.5.7`.

The change you are looking for is https://github.com/rabbitmq/rabbitmq-management/pull/74.

**Comment by jippi** [comment]
Okay, either way, its a breaking change in a patch version :(

**Comment by michaelklishin** [comment]
@jippi previous version was a bug that was fixed. An empty string is hardly a great way to indicate "no value". I consider that to be a bug fix. Yes, sometimes breaking changes are necessary when fixing bugs. We are intentionally aggressive about making them early as opposed to waiting for another year or so.

**Comment by michaelklishin** [comment]
@jippi *way* more people reported the empty string being an unreasonable value (especially for JSON parsers in languages such as Java, Go and Haskell) than this being a breaking change.

**Comment by jippi** [comment]
@michaelklishin okay, thanks for the clarification - sorry if my frustration made me sound whiny.. I'm still super happy with the project though :)
