### ISSUE TITLE
release 3.0.6 - main.js for loop (line 1069) breaks management plugin for IE

### ISSUE THREAD

**Issue by jarlehal** [rabbitmq/rabbitmq-management#105]
I TRIED CHANGING for (item of contexts) TO  for (item in contexts)
and that works better ;) 
...
                 var matches = /api\/(.*)\?/.exec(req.responseURL);
                 if (matches != null && matches.length > 1) {
        ------>>  for (item in contexts) {
                         if (matches[1].indexOf(item) == 0) {update_pages(item, 1)};
                     }
                 }
                 last_page_out_of_range_error = new Date()

**Comment by michaelklishin** [comment]
See https://github.com/rabbitmq/rabbitmq-management/issues/98.

**Comment by jarlehal** [comment]
Ok. Great!!
