### ISSUE TITLE
Unsupported media type 415 response code

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#107]
Looks like after moving to cowboy REST some management UI requests could fail with 415 HTTP code, because API expect `application/json`, but forms being sent with `text/plain`.
Detected when trying to publish message to exchange. Could be in some other forms as well.

**Comment by essen** [comment]
Which forms? How to reproduce?

**Comment by hairyhum** [comment]
`http://localhost:15672/#/exchanges/%2F/amq.direct`

Fill publish message form.

Click `Publish message`

Get `Got response code 415 with body`

In request headers: `Content-Type: text/plain;charset=UTF-8`

**Comment by essen** [comment]
I can reproduce thanks. It *is* sending JSON though so it's probably the request content-type that should be fixed. Apparently coming from JS.

**Comment by essen** [comment]
Sent a PR in #109

**Comment by michaelklishin** [comment]
Should be fixed in #109.
