### ISSUE TITLE
IE 11 JS error in Sammy.js

### ISSUE THREAD

**Issue by noxhoej** [rabbitmq/rabbitmq-management#112]
When trying to open the management Web UI at http://localhost:15672/ in IE 11 I just get a blank window.

In the console I get an error stating that "Object doesn't support this action" at the statement `console.log.apply` in sammy-0.6.0.min.js.

This error seems to be fixed in newer versions of Sammy (https://github.com/quirkey/sammy/issues/211), so should be solvable by upgrading the version of Sammy used in the Management Plugin

**Comment by michaelklishin** [comment]
We are happy to upgrade Sammy but are you sure this is not #98? What version of RabbitMQ do you run?

**Comment by noxhoej** [comment]
Actually it is a bit strange:

If I tried to connect to http://localhost:15672/ I ran in to the issue that I posted about, described at https://github.com/quirkey/sammy/issues/211

If instead I tried to connect to http://<_actual hostname_>:15672/ I ran in to https://github.com/rabbitmq/rabbitmq-management/issues/98

**Comment by michaelklishin** [comment]
Most likely because guest/guest cannot sign in from localhost by default.

**Comment by Gsantomaggio** [comment]
I tried the management Web UI using IE 11 on 3.6.0 and I had #98.

I made a test based on `stable` and `master` this problem is solved

**Comment by michaelklishin** [comment]
@Gsantomaggio have you tried with a node running on a separate machine, as in, when the user isn't authenticated or fails to sign in?

**Comment by Gsantomaggio** [comment]
@michaelklishin I tried:
- localhost
- same machine with ip
- remote machine

I got always this error:

`SCRIPT1004: ...';'`
`File: main.js, row: 1068, column: 32`

as the issue 98. 

I could not tried the login because the page is always blank. I didn't get this error:
 `Object doesn't support this action`

**Comment by noxhoej** [comment]
I'm **so** sorry. I accidentally _switched_ the two scenarios when reporting this issue :cry:

When accessing the management Web UI in IE 11 at http://**localhost**:15672/, just like you, I get the error described in https://github.com/rabbitmq/rabbitmq-management/issues/98:

![localhost](https://cloud.githubusercontent.com/assets/496242/12545957/d3f59924-c346-11e5-8fa6-c86134bc8e1b.PNG)

But when I use the _actual_ host name instead of `localhost` (i.e. http://**_<actual host name_**>:15672/) I get the JS error described in https://github.com/quirkey/sammy/issues/211:

![hostname](https://cloud.githubusercontent.com/assets/496242/12546011/3220e526-c347-11e5-84a8-553220c69116.PNG)

**Comment by Gsantomaggio** [comment]
Thank you very much @noxhoej for reporting. 
Using the actual name I got the same error. 
Sorry, I was using the actual ip and not the actual name. 
We are working on it.

**Comment by michaelklishin** [comment]
Thank you for the clarification @noxhoej. We have a way to reproduce => scheduled for `3.6.1`. @Gsantomaggio feel free to submit a PR that upgrades Sammy when you have a moment, then we can test it.

**Comment by Gsantomaggio** [comment]
Sammy has been updated, see the branch [rabbitmq-management-112 ](https://github.com/rabbitmq/rabbitmq-management/tree/rabbitmq-management-112).

The problem `Object doesn't support this action` is solved.  

BTW with actual-name there are other errors during the render, as:
![error_windows_using_name](https://cloud.githubusercontent.com/assets/386987/12638909/d92e4632-c5a0-11e5-90c2-169eb0bb8940.png)

**Comment by michaelklishin** [comment]
@Gsantomaggio if this is ready, please submit a PR.

**Comment by Gsantomaggio** [comment]
IE by default uses `compatibility mode` for intranet sites. 
Just disable it this configuration and the UI works correctly also using the host-name. 

Note: to disable it `IE --> tools --> Compatibility view settings`

**Comment by michaelklishin** [comment]
@Gsantomaggio thanks. We should look into working around this. Asking all users to tweak compatibility settings won't be well received ;)

**Comment by michaelklishin** [comment]
…but that can be a separate issue not blocking the merge of #120, of course.

**Comment by Gsantomaggio** [comment]
@michaelklishin yes I agree, I have to understand why the UI doesn't work on `compatibility mode` . 
 I'd open another issue If the https://github.com/rabbitmq/rabbitmq-management/pull/120 is ok.

**Comment by michaelklishin** [comment]
@Gsantomaggio please do. #120 is in.
