### ISSUE TITLE
the  enter key does not work correctly on the new filter tool-bar IE 11

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#114]
When apply a filter for example by name and press `enter` the filter is not applied, seems does not call the pagination api.

This error occurs  only using IE  ( I tested on version 11 )

**Comment by Gsantomaggio** [comment]
Yes, it is a bug, this function https://github.com/rabbitmq/rabbitmq-management/blob/rabbitmq-management-50/priv/www/js/main.js#L642 it is not raised on IE11.

I changed it with this:
`function postprocess_partial() {`
`    $('.pagination_class').keypress(function(e) {`
 `       if (e.keyCode == 13) {`
  `          update_pages(current_template, !!$(this).attr('data-page-start') ? $(this).attr('data-page-start') : $(this).val());`
`        }`
 `   });`

now seems work correctly. I will made a few tests

**Comment by michaelklishin** [comment]
Please submit a PR and I will test it in other browsers and on OS X/Linux some more.

**Comment by Gsantomaggio** [comment]
Thank you @michaelklishin ! I did also a few tests also using Opera `34.0.2036.50` on Windows 7

**Comment by michaelklishin** [comment]
Fixed in #115.
