### ISSUE TITLE
Broker definition from versions before 3.6.0 break user passwords

### ISSUE THREAD

**Issue by jwegne** [rabbitmq/rabbitmq-management#116]
Hi,

we have a broker definition exported from RabbitMQ 3.5.7. If we import this definition into 3.6.0, the user accounts do no longer work.

Our guess is that versions before 3.6.0 use md5 hashed passwords, but 3.6.0 interprets them as sha256 on import.

Proposed fix: prefix hashed with algorithm - for example 'sha256:PG0qKRL89LdmxdO/9wXDIZCz7wpEZKOhUHCQ2HtaU+pdJQVF'. If there is no prefix, assume md5.

Please note that upgrading 3.5.7 to 3.6.0 will still export passwords as md5 hashes.

Attached are the exports from 3.5.7 and 3.6.0:
[rabbit_3.5.7.json.txt](https://github.com/rabbitmq/rabbitmq-management/files/103479/rabbit_3.5.7.json.txt)
[rabbit_3.6.0.json.txt](https://github.com/rabbitmq/rabbitmq-management/files/103480/rabbit_3.6.0.json.txt)

**Comment by michaelklishin** [comment]
See http://rabbitmq.com/passwords.html. We don't have user passwords and thus cannot do anything about it. Password hashing function can be changed back to MD5, feel free to do that if this is convenient.

**Comment by jwegne** [comment]
Hi,
I understand that you do not have the passwords. Therefore I suggested to add the hash algorithm to the export.

Or at least add something to the release notes that broker definitions from earlier versions to no longer work.

**Comment by michaelklishin** [comment]
@jwegne that means doing another `3.5.x` release and hoping that people will upgrade to it. There is little interest in doing that. Release notes already have warnings about breaking changes. Many do not read them, so we have to point http://www.rabbitmq.com/passwords.html out anyway.

I'm going to add a doco link to the change log now.

**Comment by jwegne** [comment]
Thanks for updating the change log. You mean http://www.rabbitmq.com/changelog.html, correct?

**Comment by michaelklishin** [comment]
We can update that, too. I've updated only https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_0 so far.

**Comment by jwegne** [comment]
That would be great. Next time I will check the detailed changes on github. Thank you very much for your help.

**Comment by michaelklishin** [comment]
@jwegne http://www.rabbitmq.com/changelog.html is updated, too.

**Comment by michaelklishin** [comment]
@jwegne FYI, #117 will be in `3.6.1`.
