### ISSUE TITLE
The UI doesn't work correctly with IE 11 in  compatibility mode

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#123]
IE 11 by default uses `compatibility mode` for intranet sites.
In `compatibility mode` the UI  doesn't work correctly.
This fix https://github.com/rabbitmq/rabbitmq-management/pull/120 solves in part the problem. 

To reproduce the problem use the `http://<<actual host name>>:15672/` 

**Current workaround** : Disable `compatibility mode`  in this way: `IE --> tools --> Compatibility view settings`  and disable `display intranet sites in compatibility view` check.

**Comment by micdenny** [comment]
+1
