### ISSUE TITLE
Stats page link in the HTTP API docs is broken on raw.githack.com

### ISSUE THREAD

**Issue by mbettex** [rabbitmq/rabbitmq-management#124]
Hello,

On the documentation page https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_0/priv/www/api/index.html, the link to the documentation of the objects returned by the get endpoints is broken:
- it goes to https://raw.githack.com/doc/stats.html
- but should go to https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_0/priv/www/doc/stats.html

I believe the problem is that the link value is wrong.
`<a href="/doc/stats.html">`
should be
`<a href="../doc/stats.html">`

Let me know if this is not the right place to report this.

**Comment by michaelklishin** [comment]
I updated the links for `3.6.0`, where it is still the case.

**Comment by mbettex** [comment]
Woaw, that was quick.

Thanks a lot.

**Comment by michaelklishin** [comment]
@mbettex it's OK to report it here. Note that those docs are also available at `/api/` on any node that can serve management UI, and the link is correct there. So the real problem is that `raw.githack.com` uses a different "root path". I'm not immediately sure what we should do about it.

**Comment by michaelklishin** [comment]
I think we should point that link to `raw.githack.com` or whatever we choose to host those docs in the future (e.g. Markdown on GitHub), in other words, simply use an absolute URL. FWIW the `/api/` doc endpoint is not well known even though there's a link to it in the footer.

**Comment by neoascetic** [comment]
Probably better solution than absolute URLs is to use [`base`](https://developer.mozilla.org/en/docs/Web/HTML/Element/base) HTML element to specify "root" for each relative link or whatever on the page and then use relative URLs for everything. At least the base URL will be specified in the single place (layout or something).

For example, for this particular issue base URL must be `https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_0/priv/www/` (notice the trailing slash) and URL to docs must be simply "doc/stats.html" (w/o leading slash). Hope this help.

**Comment by michaelklishin** [comment]
@neoascetic thank you for the suggestion!
