### ISSUE TITLE
rabbitmqadmin declare user fails to update user hashing function

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#125]
See [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/yJHV3CnlRdo). This can be a `rabbitmqadmin`-specific issue. It only affects those exporting definitions on `3.5.x` and importing them into `3.6.0`, not those upgrading in place.

**Comment by iacopo-papalini** [comment]
Unfortunately the problem occurs using rabbitmqctl, too.

**Comment by michaelklishin** [comment]
OK, this is a server issue, so moved to https://github.com/rabbitmq/rabbitmq-server/issues/623.
