### ISSUE TITLE
Management UI login fails with cookies disabled

### ISSUE THREAD

**Issue by CVTJNII** [rabbitmq/rabbitmq-management#127]
If a user attempts to login to the management UI with cookies disabled the page will report a "Login failed" message with no error logged in the server logs.  This can be confusing as it can mislead a user to believe there is a RabbitMQ user issue (password/tag) preventing login when the real issue is the UI cannot set a cookie.

Please detect if the user is browsing with cookies off in the frontend code and alert the user that logins will fail with cookies off.  This will provide us paranoid folks who normally surf with cookies off a valuable clue that we need to turn cookies on to use the management UI.  Thanks.

**Comment by michaelklishin** [comment]
I'm sorry but this is the first time I hear about someone trying to use management UI with cookies disabled. If there's enough demand for this feature, we certainly can do it but currently we have a lot of improvements to make that affect orders of magnitude more users.

**Comment by michaelklishin** [comment]
If someone cares enough about this, please don't be shy to leave a comment.
