### ISSUE TITLE
max-priority on Create Queue

### ISSUE THREAD

**Issue by buildmaster** [rabbitmq/rabbitmq-management#129]
Hi There,

The management API is awesome, and is great to use from integration tests. I'm just wondering if I'm missing a way of adding Max Priority to a queue (x-max-priority) when creating a queue, as it doesn't seem to be available.

Can someone let me know if I'm missing something or if it's actually not available.

Love your work!

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users. You can add any optional argument via management UI, there are even links for common ones, including max priority. See Arguments under Add a New Queue on the Queues tab.

**Comment by buildmaster** [comment]
sorry will post there, but the question was around the API not the UI, it's hard to programmatically access the UI.

**Comment by michaelklishin** [comment]
[HTTP API docs](https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_0/priv/www/api/index.html) mention

```
PUT /api/queues/vhost/name
```

with a body such as

```
 {"auto_delete":false,"durable":true,"arguments":{},"node":"rabbit@smacmullen"}
```

The `arguments` object is what you are looking for.

**Comment by buildmaster** [comment]
thank you!
