### ISSUE TITLE
Enable response body compression

### ISSUE THREAD

**Issue by bradjorgensen** [rabbitmq/rabbitmq-management#138]
gzip compression for responses is currently not enabled.  It looks like it should be easy to add.  In my environment, some API requests can be large (multiple megabytes) and compression will decrease the transfer size significantly.

**Comment by noahhaon** [comment]
:+1: this is an issue we see often, enabling gzip would help out significantly.

**Comment by essen** [comment]
To be clear this is for response bodies? Or also request bodies?

**Comment by michaelklishin** [comment]
I think response body compression would be more valuable.

**Comment by noahhaon** [comment]
@essen for response bodies.

**Comment by essen** [comment]
On master response bodies are easy (just an option to enable/make available), on stable I'm not sure.

**Comment by essen** [comment]
I've sent a PR for this on master. On stable I'm not sure we can do something that easily. Should I investigate or do we plan this for 3.7?

**Comment by michaelklishin** [comment]
Please investigate.

**Comment by essen** [comment]
I have added a PR for stable.

There's a difference between stable and master though: on stable it can't be disabled (but stays optional, if the client requests gzip responses it gets them, otherwise gets normal responses). On master it must be enabled explicitly in the settings.

**Comment by noahhaon** [comment]
I would default this to being enabled in master with the option to disable via configuration.  As long as Cowboy handles HTTP content encoding negotiation with the client it should not be a breaking change to leave this on by default, IMO.

**Comment by michaelklishin** [comment]
@essen thank you. I agree with @noahhaon on the above.

**Comment by essen** [comment]
Alright, shouldn't be a problem.

**Comment by essen** [comment]
Pushed another commit enabling compression by default.

**Comment by michaelklishin** [comment]
@essen I'm sorry, was there ever a PR in this repo that enables compression by default? I can't find it.

**Comment by essen** [comment]
It's these for master: https://github.com/rabbitmq/rabbitmq-web-dispatch/pull/8 https://github.com/rabbitmq/rabbitmq-website/pull/165

Nothing to do in management per se.

**Comment by michaelklishin** [comment]
Yup, just found out that it's in the web-dispatch one. Thank you.

**Comment by michaelklishin** [comment]
The milestone says so.

**Comment by asgs** [comment]
thank you, @michaelklishin
