### ISSUE TITLE
Line feeds in queue and exchange names

### ISSUE THREAD

**Issue by davidvanlaatum** [rabbitmq/rabbitmq-management#140]
Running RabbitMQ 3.5.4 we managed to accidentally create queues and exchanges with a new line on the end of their name but were then unable to delete them via the management UI as it inserted a \<br/\> in the url and json it used to delete them resulting in a not found message. Resending the delete request with the \<br/\> removed successfully deleted them. The queues were created via AMQP

**Comment by michaelklishin** [comment]
@davidvanlaatum can you please be more specific about what your request is?

**Comment by davidvanlaatum** [comment]
Either you shouldn't be able to create a queue with a newline on the end or the management ui should be able to delete them....

**Comment by davidvanlaatum** [comment]
I wouldn't call this usabillity I would say its a bug. Additionally have since discovered that when rabbit is restarted the queue comes back but now with an extra \<br\> in the name

**Comment by michaelklishin** [comment]
The plugin cannot solve every single problem with line feeds, invisible/unprintable characters, etc. please adjust your expectations. It is a usability issue and this is the 2nd time it was reported in many years.

**Comment by davidvanlaatum** [comment]
Not being able to delete a queue via any method I have tried is a bug. The fact that it happends suggests escaping is not being done correctly which could be a security issue.

**Comment by michaelklishin** [comment]
@davidvanlaatum like I said, technically, yes, but this is something that most people never hit or report, and there are unrealistic cases this plugin cannot solve. And please stop speculating about what it can and cannot be: this issue was filed about one specific case.

**Comment by michaelklishin** [comment]
I'm locking this issue because this is counterproductive. If you feel like it is very important, please look into a pull request: it does not affect the vast majority of users and I do not agree this is important enough to qualify for a bug.

**Comment by michaelklishin** [comment]
A related issue [reported on rabbitmq-users](https://groups.google.com/forum/#!searchin/rabbitmq-users/unprintable/rabbitmq-users/IhxqihCO3cc/zp7wtqKDoyYJ). Technically a bug but realistically it cannot be solved.

The spec dictates that queue names must only contain ASCII characters. Line feed falls into this category so chances are, we can do something about it (e.g. strip it). But claiming that running into trouble with unprintable characters is a bug is just silly.

**Comment by michaelklishin** [comment]
Closing in favour of https://github.com/rabbitmq/rabbitmq-server/issues/710.
