### ISSUE TITLE
Add /api/users/user/tags to API

### ISSUE THREAD

**Issue by DanHomerick** [rabbitmq/rabbitmq-management#141]
rabbitmqctl has a set_user_tags command that allows tags to be modified, but the management plugin only allows setting tags when the user is initially created.

My particular use case is that I would like to tag a user with an expiration timestamp, and would like to be able to update that timestamp.

**Comment by michaelklishin** [comment]
You can update user tags with a `PUT`.

**Comment by DanHomerick** [comment]
Trying to PUT to /api/users/<username> also changes the user's password, either clearing it if not supplied, or changing it.

If you know the user's current password, that's fine. However, setting tags for a user is something that would be nice to do as an admin, without needing to know user password details. The rabbitmqctl interface allows this through set_user_tags.
