### ISSUE TITLE
Cluster name can be returned as a list of integers

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#143]
After running `make tests` in the plugin, `GET /api/overview` returns the following for cluster name:

```
{
    "cluster_name": [
        102,
        111,
        111
    ],
```

which breaks Hop test suite and results in a blank page in the management UI.

Assigning to @dcorbacho because she had fixed something very similar elsewhere recently :)

**Comment by michaelklishin** [comment]
Also: this can be a test suite issue. The problem with cluster name is that it can be set to just about anything from Erlang code.

**Comment by dcorbacho** [comment]
PR in https://github.com/rabbitmq/rabbitmq-management/pull/144
