### ISSUE TITLE
The information of connection from management api is different with rabbitmqctl 

### ISSUE THREAD

**Issue by coffeesweet** [rabbitmq/rabbitmq-management#145]
1、curl -i -u guest:guest "http://192.168.7.102:15672/api/connections/192.168.7.74:9362%20->%20192.168.7.132:5672"

result:
{"type":"network","node":"rabbit@hbaseredis01-7-50","name":"192.168.7.74:9362 -> 192.168.7.132:5672","port":5672,"peer_port":9362,"host":"192.168.7.132","peer_host":"192.168.7.74","ssl":false,"peer_cert_subject":"","peer_cert_issuer":"","peer_cert_validity":"","auth_mechanism":"AMQPLAIN","ssl_protocol":"","ssl_key_exchange":"","ssl_cipher":"","ssl_hash":"","protocol":"AMQP 0-9-1","user":"guest","vhost":"/","timeout":0,"frame_max":131072,"client_properties":{"product":"py-amqp","product_version":"1.4.6","capabilities":{"connection.blocked":true,"consumer_cancel_notify":true}}}

2、./rabbitmqctl list_connections name peer_host peer_port client_properties  state|grep "192.168.7.74:9362 -> 192.168.7.132:5672"

result:
192.168.7.74:9362 -> 192.168.7.132:5672	192.168.7.74	9362	[{"product","py-amqp"},{"product_version","1.4.6"},{"capabilities",[{"connection.blocked",true},{"consumer_cancel_notify",true}]}]	running

the first result could not get "state" field，but the second result could get this field（state:running）

why? Please help me ,thanks!

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users.
