### ISSUE TITLE
File descriptors shown in UI in disagreement with rabbitmqctl report

### ISSUE THREAD

**Issue by aauer** [rabbitmq/rabbitmq-management#148]
![image](https://cloud.githubusercontent.com/assets/3219982/13556888/70d2d9f6-e3b2-11e5-9586-c5901c2d71ec.png)

The attached shows a file descriptor count in excess of the maximum; despite this, new connections are successful, and the output of **rabbitmqctl report** shows

{file_descriptors,
    [{total_limit,8092},
     {total_used,111},
     {sockets_limit,7280},
     {sockets_used,5}]},

Server version 3.6.0.

**Comment by michaelklishin** [comment]
What OS is used to run RabbitMQ?

**Comment by michaelklishin** [comment]
Also, what protocol-providing plugins are enabled and used (e.g. STOMP, Web STOMP)?

**Comment by aauer** [comment]
OS is Windows Server 2012.
No protocol-enabling plugins; only the management plugin and its dependencies are enabled, as well as the consistent_hash (which we are in the process of disabling; a test environment where this is already done also exhibits the file descriptors behaviour).

**Comment by michaelklishin** [comment]
File descriptor calculation is far from perfect on Windows, so this is a known issue. I will leave this open but it's not clear how much better we can do it.

**Comment by firewave** [comment]
Looks like the issue I am seeing as well on Windows.
FYI my thread from the mailing list regarding this - https://groups.google.com/d/msg/rabbitmq-users/0Ni_ZckZNS0/gyj6h36YUWQJ

**Comment by aauer** [comment]
Just to collect info in one place, here was my thread:
[https://groups.google.com/forum/#!searchin/rabbitmq-users/file$20descriptors$20huge/rabbitmq-users/kA5xQ-GPM9Y/mgaOESsOAwAJ]

**Comment by aauer** [comment]
Also, I'm not sure this will help, but in each of my clusters, this only manifests itself on the first node listed. In one case the second node listed has been up for over twice as long and has 1/55th the indicated file descriptor count (1400+ vs 81000+)

**Comment by michaelklishin** [comment]
Closing as something that we have not seen reported elsewhere (or cannot recall) and due to the issue being four year old. Management UI relies on a periodically updated stats database and `rabbitmqctl` goes "straight to the source" at invocation time, so this could be one explanation.

**Comment by aauer** [comment]
I totally forgot about this ticket, ancient history, no problem.
