### ISSUE TITLE
rabbitmqadmin should not use deprecated HTTPSConnection methods

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#149]
E.g. we do not use [ssl.SSLContext.load_cert_chain](https://docs.python.org/2/library/ssl.html#ssl.SSLContext.load_cert_chain) as [HTTPSConnection docs](https://docs.python.org/2/library/httplib.html) suggest.

**Comment by nhinds** [comment]
This broke compatibility with python 2.6...
