### ISSUE TITLE
rabbitmqadmin should provide a way to specify trusted CAs

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#151]
Currently we (implicitly) load the list of system CAs and Python's ssl module seems to assume that the client's own CA should not be trusted :/

See [Python ssl docs](https://docs.python.org/2/library/ssl.html) for more info.

**Comment by carlhoerberg** [comment]
This seems to have broken normal TLS, eg. when the client just should verify the server's cert and is not providing a client cert. Will submit a patch that will support both cases.
