### ISSUE TITLE
Vhost based administration rights

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#153]
Based on [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/xA8pDPTEdZQ)
Exchanges an queues are already shown based on user permissions in admin panel. But user permissions can be changed and created only on broker level.
Administration rights system in management should be extended to support vhost specific admin restrictions.

**Comment by michaelklishin** [comment]
I'm pretty sure this belongs to rabbitmq-server.
