### ISSUE TITLE
Management API to return CORS headers

### ISSUE THREAD

**Issue by epretha** [rabbitmq/rabbitmq-management#157]
Producing a monitoring or alternative management GUI that uses HTTP API from JavaScript is not currently possible via XHR because HTTP API does not return CORS headers.

**Comment by michaelklishin** [comment]
We had this request in the past, https://github.com/rabbitmq/rabbitmq-management/issues/3, which was fixed for Web STOMP but not HTTP API.

**Comment by uvzubovs** [comment]
Thank you for considering this. For now, we will have to use IE.

**Comment by essen** [comment]
Not be a problem, one question though: should this be configurable or always-on? And if configurable, what should be the default?

**Comment by michaelklishin** [comment]
Unless there are reasons to disable it, probably always on.

Headers can be stripped by reverse proxies as a workaround.

Are there any known downsides?

**Comment by essen** [comment]
None that I can think of at the moment.

**Comment by essen** [comment]
OK after reading more on the subject I think we should not enable it by default. My fear is that people may have a management node exposed to the Internet, and the combination of "allowing everything" and "exposed to everyone" can lead to CSRF attacks.

In the use case here we want to allow only on a specific origin (company-specific management GUI) or origins, so users should configure the allowed origin(s) explicitly to only allow requests from that GUI. If not configured or value is undefined, then all origins are rejected (the same as today). Note that users can still configure it to allow everything (can be convenient, but we should stress out not to do this unless behind a firewall).

The other interesting configuration value is the max-age for the preflight request cache. I also need to find a good default for this. I will look at what is usually done.

In the future it might also be necessary to handle `Access-Control-Expose-Headers` but I don't think it will matter for the time being.

**Comment by michaelklishin** [comment]
@essen thank you, we can start with "disabled by default", that's fine. I doubt many management UI instances are exposed on the public Internet: default credentials are limited to localhost-only access by default, for example. But I see where you're coming from.

**Comment by uvzubovs** [comment]
I don't have preference one way or another, as long as we can enable CORS headers somehow. It just seems that exposing management UI to public internet is rather naïve as Rabbit does not implement credential locking on certain number of failed login attempts.

**Comment by essen** [comment]
I have just pushed a branch implementing CORS support on stable. Work remain to be done for master and for the documentation.

**Comment by michaelklishin** [comment]
@essen can you please look into a PR for master soon? we have a script that spams us if stable isn't merged into master in any of the repos. Thank you.

**Comment by essen** [comment]
I won't be available until next week unfortunately. I wasn't expecting it to be merged already. :-)
