### ISSUE TITLE
Add a new endpoint that returns memory breakdown

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#161]
Like `rabbitmqctl status`.

**Comment by michaelklishin** [comment]
Note: we already provide access to this at `GET /api/nodes/{node}` if the `memory` query parameter is set to `true`. However, it is not documented and easy to find. We should introduce a new endpoint and document it: `GET /api/nodes/{node}/memory`, for example.

More ideas: relative memory use breakdown (in % of total), e.g. as a separate endpoint such as `GET /api/nodes/{node}/memory/relative`.

**Comment by dcorbacho** [comment]
Done in #181
