### ISSUE TITLE
the management statistics database with large queue,  version 3.6.1

### ISSUE THREAD

**Issue by zengzhenbo** [rabbitmq/rabbitmq-management#164]
since we upgraded rabbitmq from 3.5.7 to 3.6.1, the managment ui notice that:

> The management statistics database currently has a queue of X events to process. If this number keeps increasing, so will the memory used by the management plugin. 

and the memory  continuously increases.
In rabbitmq config file, `rates_mode` has been set like this:
**{rabbitmq_management, [{rates_mode, none}]}
**
it seem that mgmt_db_handler set `collect_statistics` with value `coarse`(line 83 in `rabbit_mgmt_db_handler.erl`).

Is there a way to solve this problem without disabled `rabbitmq_management`, and keep `rates_mode` with value `none`?

**Comment by noahhaon** [comment]
We ran into this same issue on `3.6.0`, some discussion [here](https://groups.google.com/d/topic/rabbitmq-users/a0ND5VdAbQQ/discussion). Settings `rates_mode` to `none` did not mitigate the issue for us, we ended up having to downgrade.

**Comment by michaelklishin** [comment]
There is no and the real issue we are interested in fixing is #41.

**Comment by michaelklishin** [comment]
Although thank you for finding that the setting might get overriden, it is not intentional and we will investigate.

**Comment by michaelklishin** [comment]
@zengzhenbo what version are you referring to? Can you please link to the link on GitHub? @Gsantomaggio

**Comment by zengzhenbo** [comment]
@michaelklishin @Gsantomaggio 
Thank you for your reply.
We use [rabbitmq_v3_6_1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_1), _rabbitmq-server-3.6.1-1.noarch.rpm_
We have 1000+ consumers, 1000+ queues, 1000+ publishers in one server, and set `rates_mode` with `none`

**Comment by michaelklishin** [comment]
@zengzhenbo thanks. You claim above that `collect_statistics` is forcefully set to `coarse` somewhere in the code, can you please link to that specific line on GitHub? I cannot find it in `stable` but it has a reworked event collector.

Also, we already started publishing [3.6.2 milestones](https://groups.google.com/forum/#!topic/rabbitmq-users/HiKSUkaPZtM), so if you can, feel free to give it a try. We have surprisingly little feedback on #41 to date.

**Comment by zengzhenbo** [comment]
It is in rabbitmq-management-agent, sorry for missing information
[rabbitmq-management-agent/src/rabbit_mgmt_db_handler.erl ](https://github.com/rabbitmq/rabbitmq-management-agent/blob/master/src/rabbit_mgmt_db_handler.erl#L74-L88)
```
ensure_statistics_enabled() ->
    ForceStats = rates_mode() =/= none,
    handle_force_fine_statistics(),
    {ok, StatsLevel} = application:get_env(rabbit, collect_statistics),
    rabbit_log:info("Management plugin: using rates mode '~p'~n", [rates_mode()]),
    case {ForceStats, StatsLevel} of
        {true,  fine} ->
            ok;
        {true,  _} ->
            application:set_env(rabbit, collect_statistics, fine);
        {false, none} ->
            application:set_env(rabbit, collect_statistics, coarse);
        {_, _} ->
            ok
    end.
```
When set `rates_mode` with `none`, and `collect_statistics` is `none` by default, it match `{false, none} ` and set `collect_statistics` to `coarse`

**Comment by michaelklishin** [comment]
@dcorbacho can you comment if the above is intentional?

**Comment by dcorbacho** [comment]
@michaelklishin That is very old code (2010), not changed in #41 either.

I'd say that it is intentional, to ensure that statistics are available whenever the management plugin is used. I'm not sure of the capabilities of the plugin back then, but the performance problems might have been unknown and the plugin completely useless without any data to show.

**Comment by michaelklishin** [comment]
@dcorbacho thanks. One line was changed in 2013, and the log messages that were removed in it provide a clue: https://github.com/rabbitmq/rabbitmq-management-agent/commit/80f51592bd73efc72c92d5c567b80753c79b57ca. So it was intentional but I'm not sure why. Possibly an idiosyncratic way of forcing a default.

**Comment by michaelklishin** [comment]
Let's wait for feedback on 3.6.2 M2, this might be significantly less relevant now.

**Comment by noahhaon** [comment]
We were able to trigger this issue almost immediately on `3.6.0`, regardless of configuration, so we should be able to validate 3.6.2 very quickly once it is released.  We are also waiting for the OTP Mnesia deadlock fix, so once those are both out we will schedule an upgrade.
