### ISSUE TITLE
Consistently increasing stats DB RAM use with the new event collector

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#173]
A follow-up issue to https://github.com/rabbitmq/rabbitmq-management/issues/166.

**Comment by dcorbacho** [comment]
There is definitely a leak on the queue and channel stats, which are not being removed form the db after the test has stopped. I'll continue the investigation. 

```
(rabbit@isis)39> [{T, ets:info(T, size)} || T <- Ta]. 
[{queue_stats,446},
 {connection_stats,0},
 {channel_stats,120627},
 {consumers_by_queue,0},
 {consumers_by_channel,0},
 {node_stats,1},
 {node_node_stats,0},
 {old_stats,193441}]

(rabbit@isis)15> [{T, ets:info(T, size)} || T <- Tabs].                            
[{aggr_queue_stats_fine_stats,2},
 {aggr_queue_stats_deliver_get,2},
 {aggr_queue_stats_queue_msg_counts,0},
 {aggr_queue_stats_queue_msg_rates,0},
 {aggr_queue_exchange_stats_fine_stats,0},
 {aggr_vhost_stats_deliver_get,9},
 {aggr_vhost_stats_fine_stats,9},
 {aggr_vhost_stats_queue_msg_rates,0},
 {aggr_vhost_stats_queue_msg_counts,32},
 {aggr_vhost_stats_coarse_conn_stats,32},
 {aggr_channel_queue_stats_deliver_get,0},
 {aggr_channel_queue_stats_fine_stats,0},
 {aggr_channel_queue_stats_queue_msg_counts,0},
 {aggr_channel_stats_deliver_get,170908},
 {aggr_channel_stats_fine_stats,170902},
 {aggr_channel_stats_queue_msg_counts,0},
 {aggr_channel_exchange_stats_deliver_get,0},
 {aggr_channel_exchange_stats_fine_stats,0},
 {aggr_exchange_stats_fine_stats,3},
 {aggr_node_stats_coarse_node_stats,173},
 {aggr_node_node_stats_coarse_node_node_stats,0},
 {aggr_connection_stats_coarse_conn_stats,0}]
```

**Comment by dcorbacho** [comment]
Some queue and channel stats were arriving after the `channel_closed` or `queue_deleted` was processed, and that data was never purged. Queue and channel events are now all processed on their own collectors, so they cannot be handled out of order.

**Comment by spatula75** [comment]
Any way I could get a .deb to give it a shot?  I thought about using a nightly, but I see those are built off master, not stable.

**Comment by michaelklishin** [comment]
I will send you one.

**Comment by spatula75** [comment]
Looks very good so far! Memory is holding steady in both of our clusters.  Will continue to keep an eye on it over the next few days.

**Comment by spatula75** [comment]
Still looking fine after running overnight, too; previously, we'd have leaked 25M or so by now, but we're holding very steady at about 2.5M in use.

**Comment by spatula75** [comment]
I think this one is very probably fixed; however I notice some creep in the size of the message store index when running several instances of the simload script for several days.  It's an unrelated problem, though, so it should be a different issue.

**Comment by michaelklishin** [comment]
We've noticed something similar, too.

On Mon, Apr 11, 2016 at 6:08 PM, Nicklas Johnson <notifications@github.com>
wrote:

> I think this one is very probably fixed; however I notice some creep in
> the size of the message store index when running several instances of the
> simload script for several days. It's an unrelated problem, though, so it
> should be a different issue.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/rabbitmq/rabbitmq-management/issues/173#issuecomment-208392462>
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by spatula75** [comment]
Opened https://github.com/rabbitmq/rabbitmq-server/issues/740 but it won't hurt my feelings if it's a duplicate and you want to close it.

**Comment by michaelklishin** [comment]
@spatula75 we will release a new milestone after resolving a few more issues. Thanks for your feedback (and running the test for a couple of days).
