### ISSUE TITLE
Web UI reports bad requests as server unreachability

### ISSUE THREAD

**Issue by spatula75** [rabbitmq/rabbitmq-management#188]
The Admin UI erroneously reports API requests which are rejected by the server as though the server itself were unreachable.  For example, attempting to delete an exclusive queue will result in a 405 RESOURCE_LOCKED response from the server, but the Admin UI reports this as a server outage.

Steps to reproduce:

1. Create an exclusive, auto-delete queue on the server with no consumers (might work with consumers and other modes too, but exclusive is the easiest way to see the issue)
2. Using the Admin UI, select this exclusive queue from the list of queues.
3. Attempt to delete the queue using the Delete button.
4. Admin UI reports that the server can't be reached (in a red banner at the bottom of the page), but what actually happened was a 405 Resource Locked response from the server.

One can still rid oneself of the unwanted queues by killing the connection with the exclusive queue.  The more interesting issue is getting the correct error message reported back to the end user.

**Comment by hairyhum** [comment]
This looks like regression in `3.6.2RC1`
@spatula75  can you confirm version on which you have this error?

**Comment by spatula75** [comment]
We're seeing it with 3.6.2rc1. I didn't notice whether it was happening with earlier milestone builds.

**Comment by michaelklishin** [comment]
@hairyhum has fixed this for `stable` but we need a separate PR for `master`. So keeping this open for now.

**Comment by michaelklishin** [comment]
@spatula75 I'll send you a one-off build to try tomorrow (PST).

**Comment by hairyhum** [comment]
I cannot reproduce it with `master` or `3.7.0.milestone3`. Cowboy use different encoding mechanism.

**Comment by michaelklishin** [comment]
@hairyhum cheers.

**Comment by michaelklishin** [comment]
This was a regression since `3.6.1` which was fixed before `3.6.2` => not including into release notes.
