### ISSUE TITLE
Designated stats node(s)

### ISSUE THREAD

**Issue by EricPoker** [rabbitmq/rabbitmq-management#194]
I need a way of setting which node is Stats node.Because some node have my durable queue, they are very busy.If they selected Stats node.The performance is too bad!

**Comment by michaelklishin** [comment]
There is no way to do that presently. One designated node sounds like a bad idea availability-wise.

**Comment by noahhaon** [comment]
I would like to add a +1 to this feature request.  In Google's whitepaper on scaling RabbitMQ they make mention of running a dedicated stats node, and in my conversations with Pivotal support they suggest this as well.  We do this in our deployment, by being careful which node gets started first in our cluster, and ensuring that fewer queues are running on the stats node.

The lack of a configuration to select the stats node makes this difficult to do, but something similar to the `ha-policy` for queues would be very nice to have.  If the recent improvements to the management plugin have allowed the process(es) on the stats node to utilize multiple cores, then this may be more important as it could now have an even larger footprint on the node it is on.

**Comment by michaelklishin** [comment]
How should this work if the designated stats node is unavailable? At the very least it should be a set of nodes.

**Comment by noahhaon** [comment]
I think the easiest to reason about would be something like, 

1. Node is selected via existing behavior
2. If Node is not in preferred list, defer/fail over to plugin running on preferred Node if available, in order specified in list
3. If all plugins on preferred Nodes are unavailable, log error and remain running

What do you think?

**Comment by michaelklishin** [comment]
By "log an error and remain running" do you mean "migrate the database to a different node not on the list"?

**Comment by noahhaon** [comment]
No. In step 1, I assume the normal/legacy stats db startup has happened (or is happening).  In step 3 it would just continue running on whichever node it started on in step 1, per the current behavior, instead of migrating to a "preferred" node.

**Comment by michaelklishin** [comment]
We're discussing this as part of https://github.com/rabbitmq/rabbitmq-management/issues/236 but in `3.7.0`. Many open ended deployment questions, in particular with a cluster of collectors ("management nodes"), so far.

**Comment by michaelklishin** [comment]
#236 (which is close to being merged) makes this issue effectively obsolete.
