### ISSUE TITLE
Channels and connection stats is never deleted if process was killed

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#198]
If channel or connection process is deleted by `kill` signal, it's stats record will never be deleted from database and it will be displayed in management UI.

`kill` exit signal is rare, but not impossible, since it's a part of otp supervision behaviour.

Can be related to [rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/z9J1hHPPZuk)

**Comment by hairyhum** [comment]
There are two options I can see right now:

- monitoring process for channels and connections (somewhere in channel and connection supervisor)
- periodical garbage collection for channels and connections database

Latter is more flexible and configurable, but network partitions in cluster can mess it up.

**Comment by michaelklishin** [comment]
@hairyhum the same is true for option 1 (about partitions). As far as the stats node is concerned, if a connection is unreachable, it doesn't exist.

I personally think we should consider both. How should we decide if it's time to GC a channel or connection samples? @dcorbacho

**Comment by dcorbacho** [comment]
We already have processes that GC the old data, one per table that runs every 5 seconds over a subset of its data, so the initial idea would be to change those relating to channels and connections to a special type that does some extra checks on them. However, there are several tables related to channels and each channel should be checked only once to avoid overheads.

We could use the timestamp of the last channel/connection stats to decide if it's time to remove them. But as we might drop channel stats if the system is under heavy load, we can't really trust that data. I think the management should check on the server the status of those items, and may be create a new GC process only for that.

**Comment by michaelklishin** [comment]
@dcorbacho the idea of keeping track when a channel/connection/queue info was updated last and GC'ed based on that data has crossed my mind and makes sense to me.

**Comment by michaelklishin** [comment]
Separate GC processes that verify channel/connection/queue process availability sounds good, as long as we don't do it too often. For example, 1 minute. We could also consider using a pool of worker processes that will perform actual checks: we have a generic process pool library that's used elsewhere.

**Comment by hairyhum** [comment]
Channel and connection stats store Pid as key, so we can check if process for channel/connection is still alive and delete stats for dead processes only.

**Comment by hairyhum** [comment]
As for check periods we can make it configurable, like `sample_retention_policies`, but for channels, connections and consumers.
Queues stats are being loaded from mnesia database, so it shouldn't be affected by this issue.

**Comment by dumbbell** [comment]
Depending on the method you use to detect and decide which records to clean, be sure to not remove soemthing which in fact is still valid. For instance, RabbitMQ does cleanups after a remote node goes down. Sometimes, this node comes back before the end of the cleanup and RabbitMQ removes data which are valid again. Several of those bugs were fixed, but I fear some of them are still there.
