### ISSUE TITLE
rabbitmqadmin misinterprets boolean settings in configfile

### ISSUE THREAD

**Issue by terrorobe** [rabbitmq/rabbitmq-management#20]
In

https://github.com/rabbitmq/rabbitmq-management/blob/491911cc07496bd0fade6035ae161f004ea093cd/bin/rabbitmqadmin#L344-358

the config values are read from the rabbitmqadmin.conf

In case of the ``ssl`` option the check at

https://github.com/rabbitmq/rabbitmq-management/blob/491911cc07496bd0fade6035ae161f004ea093cd/bin/rabbitmqadmin#L424

will always succeed if the option is set (e.g. ``ssl = False``)  since the string always evaluates to True.

**Comment by michaelklishin** [comment]
@terrorobe is this still relevant?

**Comment by terrorobe** [comment]
This got fixed in the puppet module upstream.

The implementation in rabbitmqadmin is unchanged and is still misleading in my opinion ;) At least I expect that a "False" value can be used to deactivate a feature in a config file when a "True" value enables it.

See https://github.com/rabbitmq/rabbitmq-management/blob/963a16dc622c16585dc844a228a542502829f254/bin/rabbitmqadmin#L200-207

If this is how you want to roll, please close the bug.

**Comment by michaelklishin** [comment]
@terrorobe we want to fix this properly here, too. Thank you for confirming! We've now moved to GitHub, by the way, so feel free to file issues here should anything else come up.

**Comment by terrorobe** [comment]
Ahh, good to know! I think rabbitmq has been fine so far, there're some kinks we're going to work out in the puppet modules, if anything else comes up we'll let you know. 

Thanks for your work so far!

**Comment by michaelklishin** [comment]
Resolved in #72.
