### ISSUE TITLE
Report stats database memory for each ETS table it uses

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#215]
To be able to investigate issues like https://github.com/rabbitmq/rabbitmq-management/issues/214 management database memory reporting should be able to show memory per table.

**Comment by michaelklishin** [comment]
@hairyhum we now have it in the API. Should I close this or do we want to add a UI section?

**Comment by hairyhum** [comment]
@michaelklishin I don't know how to make UI section representative.
