### ISSUE TITLE
High memory consumption due to unbound collector queue

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-management#221]
Some users reported high memory consumption while using the mgmt plugin, linked to memory process and not stats database.

Reproduced using the scripts provided by Zhenbo Zeng in https://groups.google.com/forum/#!topic/rabbitmq-users/adba2MqHem0

**Comment by michaelklishin** [comment]
This is a regression introduced in #41. However, we will employ a much simpler strategy of dropping after process message queue grows longer than X, where X will be a configurable parameter.
