### ISSUE TITLE
Message rates chart shows delivered noack in confirm color

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-management#224]
Legend does not assign a color to messages noack, but they are shown in pale blue, which is the color for confirms.

See also: https://groups.google.com/forum/m/#!topic/rabbitmq-users/KTryQ2oDq4A

**Comment by Gsantomaggio** [comment]
the following colours  were missing:

- Get 
- Deliver (noack)
- Get (noack)
- Return
- Disk read
- Disk write

Here the colours for single queue:
![single](https://cloud.githubusercontent.com/assets/386987/17367498/67d04bbe-5990-11e6-89d8-9655386f0099.png)

and for overview:
![oveview](https://cloud.githubusercontent.com/assets/386987/17367536/9c356e20-5990-11e6-8fcc-d449cb519037.png)

Thoughts ?

**Comment by uvzubovs** [comment]
These look reasonable to me, but I will let you decide which colors to use for the missing values ;) 
I appreciate you fixing this as it's quite confusing as it is!
