### ISSUE TITLE
Cannot find rabbitmq-server 3.6.1 in apt repo to workaround #225

### ISSUE THREAD

**Issue by nhinds** [rabbitmq/rabbitmq-management#226]
I can't `apt install` the old version of rabbitmq-server (3.6.1) to work around #225, because it seems to have disappeared from the apt repository: http://www.rabbitmq.com/debian/pool/main/r/rabbitmq-server/

Why is this version unavailable, and where can it be retrieved from via apt?

**Comment by michaelklishin** [comment]
packagecloud.io/rabbitmq. Please post questions to rabbitmq-users in the future.

**Comment by nhinds** [comment]
You've not answered why the official package repository doesn't have it, which I would consider a bug relevant to this repository

**Comment by michaelklishin** [comment]
Because we only provide a single version on rabbitmq.com.

**Comment by danielhodder** [comment]
Ummm. Why? That's not how Apt repositories work. You need to have all supported version there or point people at a place that actually works.

**Comment by michaelklishin** [comment]
There is a Package Cloud repository that contains a few recent releases as well as `3.5.7`. Do you want to spend your time arguing about "how apt repositories work?"
