### ISSUE TITLE
Pre-select virtual host when creating exchanges/queues to match the one in context

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-management#235]
When we have access to more than one vhost, we usually select the one we want to work with from the drop-down in the upper right corner (under the Rabbit and Erlang version numbers).

However, the add exchange/queue panels on the exchange/queue pages, respectively, always default to the default vhost (/). As a result, we tend to make the same mistake over and over -- creating exchanges and queues in the default vhost, deleting them, and recreating where we wanted.

Would it be possible to default create exchange/page panels to the vhost selected in the upper right corner? If nothing is selected in the upper right corner (or All), then you may default to the default vhost. 

Thanks

**Comment by uvzubovs** [comment]
Thank you so much! Will save much time and avoid much frustration ;)

**Comment by michaelklishin** [comment]
So #322 only covers queues. @dcorbacho should we do the same for exchanges to really consider this closed?

**Comment by dcorbacho** [comment]
Ops, my bad. Totally missed the 'exchange' part in the description :(
Just pushed that part
