### ISSUE TITLE
Make statistics collection and aggregation distributed across all cluster nodes

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#236]
Follow-up to #41. Problem definition is the same and the solution there doesn't work for some workload because a single node collecting and aggregating all stats only can go so far.

So this issue is about making the collector distributed (stats are stored on every cluster node) for `3.6.x`.

**Comment by sega-yarkin** [comment]
Is it make sense to append some parameters to choose which statistics I want to collect? For example, if I need statistics for exchanges and queues, but not need it for channels and connections, it will save some system resources.

**Comment by michaelklishin** [comment]
Some have asked for this. This may be a good chance to make that possible. Currently exchange and queue stats are emitted by channels so you cannot disable one without the others.

**Comment by sega-yarkin** [comment]
For now, even if `rates_mode` is `none` `rabbit_mgmt_*_collector` processes are doing some work, but without saving stats to tables. Am I right? 

![screen](https://cloud.githubusercontent.com/assets/1433049/16342994/7e879a0a-3a3d-11e6-9e41-5164e6bd4a12.png)

**Comment by michaelklishin** [comment]
@sega-yarkin let's not turn this issue into a support case. Please take this to the mailing list. Thanks.

**Comment by michaelklishin** [comment]
We are considering if we should try to target `3.6.x` with this. This is easily over half of our support load right now.

Introducing another breaking management plugin version in `3.6.x` isn't cool at all, however.

**Comment by noahhaon** [comment]
@michaelklishin What would the breaking changes be?

**Comment by michaelklishin** [comment]
@noahhaon mixed clusters will have to all run the new plugin, same as with `3.6.2`. No breaking HTTP API changes planned.

**Comment by noahhaon** [comment]
Do users often upgrade rabbitmq-server without upgrading the plugins?  I assume they are all packaged together now?  I suppose the issue would be for rolling upgrades, but as long as those failures are handled gracefully ...

As you mentioned, this is a real pain point for large RMQ clusters and appears to be causing support issues for Pivotal.  We would certainly love to see this feature, and it seems like it would be worth getting into `3.6.x`, despite some pain during a rolling upgrade.

**Comment by michaelklishin** [comment]
It's not about plugins being out of sync with the server but rather mixed
patch version clusters. But I definitely see your point.

On Thu, Jun 30, 2016 at 7:56 PM, noahhaon <notifications@github.com> wrote:

> Do users often upgrade rabbitmq-server without upgrading the plugins? I
> assume they are all packaged together now? I suppose the issue would be for
> rolling upgrades, but as long as those failures are handled gracefully ...
>
> As you mentioned, this is a real pain point for large RMQ clusters and
> appears to be causing support issues for Pivotal. We would certainly love
> to see this feature, and it seems like it would be worth getting into
> 3.6.x, despite some pain during a rolling upgrade.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rabbitmq/rabbitmq-management/issues/236#issuecomment-229720558>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAEQmrrfYHC-QOi0ncODG6TBSm_zu1Aks5qQ_UlgaJpZM4I9tBc>
> .
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by noahhaon** [comment]
Gotcha - well, maybe an out-of-cycle release of the plugin which would run on `3.6.x` clusters?  Then at least you're not violating least-surprise and breaking versioning semantics by bundling it with a `3.6.x` release.

Not sure which is worse from a maintenance perspective, but I'd imagine many users with large clusters (including us) would be quite happy to install the plugin separately if it included this feature.

**Comment by michaelklishin** [comment]
@noahhaon we are leaning towards shipping it in `3.6.5` or so. Most users would rather upgrade all nodes to `3.6.5` than continue fighting the issues with the existing collector.

**Comment by michaelklishin** [comment]
A couple of updates:

 * So far we intend to ship this in a `3.6.x` release
 * We will switch to Cowboy at the same time (`3.7.0` already uses Cowboy) to reduce the delta between branches. The only user facing change is HTTP API response code changing from `201` to `204` in some cases — virtually no client libraries or users should be affected.

**Comment by essen** [comment]
The development branches now use Cowboy.

**Comment by michaelklishin** [comment]
It has been merged and will be dogfooded in `stable` before cutting a milestone release for the community.

**Comment by luchiano1** [comment]
1
