### ISSUE TITLE
Unable to switch tabs using web interface

### ISSUE THREAD

**Issue by JeffreyM** [rabbitmq/rabbitmq-management#242]
After upgrading to 3.6.2, switching from 'Overview' to any other tab results in no UI refresh and a message of 'ReferenceError: 'pagiante_ui' is undefined'

**Comment by michaelklishin** [comment]
This can either be something in UI code or slow HTTP API responses. Let's investigate on the mailing list, our team does not use GitHub issues for discussions.

**Comment by michaelklishin** [comment]
[HTTP API](http://www.rabbitmq.com/management.html) can be invoked via curl to see if the API responds in time.

To see if this can be a UI code issue, clear your browser's cache and reload.

Also, if we discover something actionable, we will file a new issue.

**Comment by JeffreyM** [comment]
Clearing the browser cache resolved the issue - thanks for the quick response.
