### ISSUE TITLE
Queues endpoint fails to serialize GC metrics on Erlang 19.0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#244]
Moved from https://github.com/rabbitmq/rabbitmq-server/issues/876#issuecomment-231076923.

SASL log entry:

```
=ERROR REPORT==== 7-Jul-2016::16:25:03 ===
JSON encode error: {bad_term,#{error_logger => true,kill => true,size => 0}}
While encoding:
[[{memory,14128},
  {reductions,3628},
  {reductions_details,[{rate,0.0}]},
  {messages,0},
  {messages_details,[{rate,0.0}]},
  {messages_ready,0},
  {messages_ready_details,[{rate,0.0}]},
  {messages_unacknowledged,0},
  {messages_unacknowledged_details,[{rate,0.0}]},
  {idle_since,<<"2016-07-07 13:22:09">>},
  {consumer_utilisation,''},
  {policy,<<"ha-all">>},
  {exclusive_consumer_tag,''},
  {consumers,1},
  {slave_nodes,[]},
  {synchronised_slave_nodes,[]},
  {recoverable_slaves,[]},
  {state,running},
  {reductions,3628},
  {garbage_collection,[{max_heap_size,#{error_logger => true,kill => true,size => 0}},
                       {min_bin_vheap_size,46422},
                       {min_heap_size,233},
                       {fullsweep_after,65535},
                       {minor_gcs,1}]},
  {messages_ram,0},
  {messages_ready_ram,0},
  {messages_unacknowledged_ram,0},
  {messages_persistent,0},
  {message_bytes,0},
  {message_bytes_ready,0},
  {message_bytes_unacknowledged,0},
  {message_bytes_ram,0},
  {message_bytes_persistent,0},
  {head_message_timestamp,''},
  {disk_reads,0},
  {disk_writes,0},
  {backing_queue_status,{struct,[{mode,default},
                                 {q1,0},
                                 {q2,0},
                                 {delta,[delta,undefined,0,undefined]},
                                 {q3,0},
                                 {q4,0},
                                 {len,0},
                                 {target_ram_count,infinity},
                                 {next_seq_id,0},
                                 {avg_ingress_rate,0.0},
                                 {avg_egress_rate,0.0},
                                 {avg_ack_ingress_rate,0.0},
                                 {avg_ack_egress_rate,0.0},
                                 {mirror_seen,0},
                                 {mirror_senders,0}]}},
  {node,'rabbit@it-kae-rmq'},
  {arguments,{struct,[{<<"x-dead-letter-exchange"...
```

So somehow GC statistics return something other than a value we expect.

**Comment by michaelklishin** [comment]
@kae what Erlang version is used?

**Comment by michaelklishin** [comment]
What does `rabbitmqctl eval 'erlang:process_info(self(), garbage_collection).'` output?

**Comment by dcorbacho** [comment]
Erlang 19 causes that output, but is not documented as such:
```
1> erlang:process_info(self(), garbage_collection).
{garbage_collection,[{max_heap_size,#{error_logger => true,
                                      kill => true,
                                      size => 0}},
                     {min_bin_vheap_size,46422},
                     {min_heap_size,233},
                     {fullsweep_after,65535},
                     {minor_gcs,1}]}
```

**Comment by michaelklishin** [comment]
Yup, in a bare Erlang shell:

```
1> erlang:process_info(self(), garbage_collection).
{garbage_collection,[{max_heap_size,#{error_logger => true,
                                      kill => true,
                                      size => 0}},
                     {min_bin_vheap_size,46422},
                     {min_heap_size,233},
                     {fullsweep_after,65535},
                     {minor_gcs,1}]}
```

**Comment by dcorbacho** [comment]
@michaelklishin just talked to @garazdawi and he confirmed that it is an expected output, but the typespec hasn't been updated yet.

**Comment by kae** [comment]
@michaelklishin  Erlang 19.0 here confirmed

**Comment by michaelklishin** [comment]
@kae stick to 18.x until `3.6.4` comes out.

**Comment by Tomdarkness** [comment]
Do we know when 3.6.4 will be released? Running Erlang 19 and need to upgrade to fix memory leak fixed in 3.6.3 (#214) but downgrading Erlang will require us taking the whole cluster down.

**Comment by michaelklishin** [comment]
@Tomdarkness in a few days.

**Comment by sisingh** [comment]
Getting error while trying to view queues : Got response code 500 with body {"error":"JSON encode error: ...
 
curl -u guest:guest -X GET http://127.0.0.1:15672/api/queues/ | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
101  6790  101  6790    0     0   905k      0 --:--:-- --:--:-- --:--:-- 1105k
{
    "error": "JSON encode error: {bad_term,#{error_logger => true,kill => true,size => 0}}", 
    "reason": "While encoding: \n[[{memory,14056},\n  {message_stats,\n      [{deliver,1},\n       {deliver_details,[{rate,0.0}]},\n       {deliver_no_ack,0},\n       {deliver_no_ack_details,[{rate,0.0}]},\n       {get,0},\n       {get_details,[{rate,0.0}]},\n       {get_no_ack,1},\n       {get_no_ack_details,[{rate,0.0}]},\n       {publish,0},\n       {publish_details,[{rate,0.0}]},\n       {publish_in,0},\n       {publish_in_details,[{rate,0.0}]},\n       {publish_out,0},\n       {publish_out_details,[{rate,0.0}]},\n       {ack,1},\n       {ack_details,[{rate,0.0}]},\n       {deliver_get,2},\n       {deliver_get_details,[{rate,0.0}]},\n       {confirm,0},\n       {confirm_details,[{rate,0.0}]},\n       {return_unroutable,0},\n       {return_unroutable_details,[{rate,0.0}]},\n       {redeliver,0},\n       {redeliver_details,[{rate,0.0}]}]},\n  {reductions,23862},\n  {reductions_details,[{rate,0.0}]},\n  {messages,0},\n  {messages_details,[{rate,0.0}]},\n  {messages_ready,0},\n  {messages_ready_details,[{rate,0.0}]},\n  {messages_unacknowledged,0},\n  {messages_unacknowledged_details,[{rate,0.0}]},\n  {idle_since,<<\"2016-07-28 14:32:09\">>},\n  {consumer_utilisation,''},\n  {policy,''},\n  {exclusive_consumer_tag,''},\n  {consumers,0},\n  {recoverable_slaves,''},\n  {state,running},\n  {reductions,23862},\n  {garbage_collection,\n      [{max_heap_size,#{error_logger => true,kill => true,size => 0}},\n       {min_bin_vheap_size,46422},\n       {min_heap_size,233},\n       {fullsweep_after,65535},\n       {minor_gcs,1}]},\n  {messages_ram,0},\n  {messages_ready_ram,0},\n  {messages_unacknowledged_ram,0},\n  {messages_persistent,0},\n  {message_bytes,0},\n  {message_bytes_ready,0},\n  {message_bytes_unacknowledged,0},\n  {message_bytes_ram,0},\n  {message_bytes_persistent,0},\n  {head_message_timestamp,''},\n  {disk_reads,0},\n  {disk_writes,0},\n  {backing_queue_status,\n      {struct,\n          [{mode,default},\n           {q1,0},\n           {q2,0},\n           {delta,[delta,0,0,0]},\n           {q3,0},\n           {q4,0},\n           {len,0},\n           {target_ram_count,infinity},\n           {next_seq_id,2},\n           {avg_ingress_rate,4.012691758790037e-124},\n           {avg_egress_rate,5.026837959663088e-68},\n           {avg_ack_ingress_rate,5.022802443097065e-68},\n           {avg_ack_egress_rate,5.022802443097065e-68}]}},\n  {node,'rabbit@ggn-47-61'},\n  {arguments,{struct,[]}},\n  {exclusive,false},\n  {auto_delete,false},\n  {durable,true},\n  {vhost,<<\"/\">>},\n  {name,<<\"email\">>}],\n [{memory,14056},\n  {message_stats,\n      [{deliver,3},\n       {deliver_details,[{rate,0.0}]},\n       {deliver_no_ack,0},\n       {deliver_no_ack_details,[{rate,0.0}]},\n       {get,0},\n       {get_details,[{rate,0.0}]},\n       {get_no_ack,1},\n       {get_no_ack_details,[{rate,0.0}]},\n       {publish,0},\n       {publish_details,[{rate,0.0}]},\n       {publish_in,0},\n       {publish_in_details,[{rate,0.0}]},\n       {publish_out,0},\n       {publish_out_details,[{rate,0.0}]},\n       {ack,3},\n       {ack_details,[{rate,0.0}]},\n       {deliver_get,4},\n       {deliver_get_details,[{rate,0.0}]},\n       {confirm,0},\n       {confirm_details,[{rate,0.0}]},\n       {return_unroutable,0},\n       {return_unroutable_details,[{rate,0.0}]},\n       {redeliver,0},\n       {redeliver_details,[{rate,0.0}]}]},\n  {reductions,26958},\n  {reductions_details,[{rate,0.0}]},\n  {messages,0},\n  {messages_details,[{rate,0.0}]},\n  {messages_ready,0},\n  {messages_ready_details,[{rate,0.0}]},\n  {messages_unacknowledged,0},\n  {messages_unacknowledged_details,[{rate,0.0}]},\n  {idle_since,<<\"2016-07-28 14:32:09\">>},\n  {consumer_utilisation,''},\n  {policy,''},\n  {exclusive_consumer_tag,''},\n  {consumers,0},\n  {recoverable_slaves,''},\n  {state,running},\n  {reductions,26958},\n  {garbage_collection,\n      [{max_heap_size,#{error_logger => true,kill => true,size => 0}},\n       {min_bin_vheap_size,46422},\n       {min_heap_size,233},\n       {fullsweep_after,65535},\n       {minor_gcs,1}]},\n  {messages_ram,0},\n  {messages_ready_ram,0},\n  {messages_unacknowledged_ram,0},\n  {messages_persistent,0},\n  {message_bytes,0},\n  {message_bytes_ready,0},\n  {message_bytes_unacknowledged,0},\n  {message_bytes_ram,0},\n  {message_bytes_persistent,0},\n  {head_message_timestamp,''},\n  {disk_reads,0},\n  {disk_writes,0},\n  {backing_queue_status,\n      {struct,\n          [{mode,default},\n           {q1,0},\n           {q2,0},\n           {delta,[delta,0,0,0]},\n           {q3,0},\n           {q4,0},\n           {len,0},\n           {target_ram_count,infinity},\n           {next_seq_id,4},\n           {avg_ingress_rate,4.6079203330479575e-124},\n           {avg_egress_rate,1.519750778518055e-67},\n           {avg_ack_ingress_rate,1.5195938854652614e-67},\n           {avg_ack_egress_rate,1.5195938854652614e-67}]}},\n  {node,'rabbit@ggn-47-61'},\n  {arguments,{struct,[]}},\n  {exclusive,false},\n  {auto_delete,false},\n  {durable,true},\n  {vhost,<<\"/\">>},\n  {name,<<\"nav\">>}],\n [{memory,14040},\n  {reductions,18849},\n  {reductions_details,[{rate,0.0}]},\n  {messages,0},\n  {messages_details,[{rate,0.0}]},\n  {messages_ready,0},\n  {messages_ready_details,[{rate,0.0}]},\n  {messages_unacknowledged,0},\n  {messages_unacknowledged_details,[{rate,0.0}]},\n  {idle_since,<<\"2016-07-28 14:32:09\">>},\n  {consumer_utilisation,''},\n  {policy,''},\n  {exclusive_consumer_tag,''},\n  {consumers,0},\n  {recoverable_slaves,''},\n  {state,running},\n  {reductions,18849},\n  {garbage_collection,\n      [{max_heap_size,#{error_logger => true,kill => true,size => 0}},\n       {min_bin_vheap_size,46422},\n       {min_heap_size,233},\n       {fullsweep_after,65535},\n       {minor_gcs,1}]},\n  {messages_ram,0},\n  {messages_ready_ram,0},\n  {messages_unacknowledged_ram,0},\n  {messages_persistent,0},\n  {message_bytes,0},\n  {message_bytes_ready,0},\n  {message_bytes_unacknowledged,0},\n  {message_bytes_ram,0},\n  {message_bytes_persistent,0},\n  {head_message_timestamp,''},\n  {disk_reads,0},\n  {disk_writes,0},\n  {backing_queue_status,\n      {struct,\n          [{mode,default},\n           {q1,0},\n           {q2,0},\n           {delta,[delta,0,0,0]},\n           {q3,0},\n           {q4,0},\n           {len,0},\n           {target_ram_count,infinity},\n           {next_seq_id,0},\n           {avg_ingress_rate,0.0},\n           {avg_egress_rate,0.0},\n           {avg_ack_ingress_rate,0.0},\n           {avg_ack_egress_rate,0.0}]}},\n  {node,'rabbit@ggn-47-60'},\n  {arguments,{struct,[]}},\n  {exclusive,false},\n  {auto_delete,false},\n  {durable,true},\n  {vhost,<<\"/\">>},\n  {name,<<\"sms\">>}]]"
}
==============
Erlang report
]$ erl
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.0  (abort with ^G)
1> process_info(self(), garbage_collection).
{garbage_collection,[{max_heap_size,#{error_logger => true,
                                      kill => true,
                                      size => 0}},
                     {min_bin_vheap_size,46422},
                     {min_heap_size,233},
                     {fullsweep_after,65535},
                     {minor_gcs,4}]}
Please suggest the fix.

**Comment by michaelklishin** [comment]
I'm locking this as we get the same issue reported over and over. `3.6.4` will be compatible with Erlang 19.0. Until then, use an older Erlang version.
