### ISSUE TITLE
Timestamps returned by `erlang:now()` can be confusing

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-management#25]
stobix on #rabbitmq reports that some timestamps in the management UI (eg. the charts) don't match the wall clock time.

In his test case, `erlang:now()` slowly drifts apart from `erlang:time()` for instance. A way to reproduce it is to suspend/resume the computer.

**Comment by simonmacmullen** [comment]
Are they running 3.3.5 or earlier? This was supposed to be fixed in 3.4.0, see bug 26399.

**Comment by dumbbell** [comment]
I asked the user on IRC; waiting for his reply.

**Comment by dumbbell** [comment]
According to a screenshot of the management UI, he is using RabbitMQ 3.2.4. I will ask him if he can upgrade.
