### ISSUE TITLE
Management plugin without web_ui javascript

### ISSUE THREAD

**Issue by deadtrickster** [rabbitmq/rabbitmq-management#251]
I have plugin that just mounts new api endpoint without touching UI.

```erlang
dispatcher() -> [{["metrics"],        rabbit_mgmt_metrics_handler, []}].
web_ui()     -> [].
```

this apparently breaks web ui because `/api/extensions` renders this:

```javascript
[[],{"javascript":"dispatcher.js"}]
```
[`setup_extensions`](
https://github.com/rabbitmq/rabbitmq-management/blob/5e1e841a936d6a48a3a2f3c49d41d7d59fe91ba8/priv/www/js/main.js#L140) always expects javascript key.

Question: what should `web_ui` return in this case? or maybe `setup_extensions` could be patched?

Thank you.

**Comment by michaelklishin** [comment]
Take a look at [

Feel free to submit a patch that makes `setup_extensions` more resilient in general, e.g. it could filter out `nulls` (which is a value that kind of makes sense in a dynamically typed language to indicate "nothing").

**Comment by deadtrickster** [comment]
Yeah can do the patch, against what branch?

**Comment by michaelklishin** [comment]
`stable`.
