### ISSUE TITLE
Consumer utilisation for queues with no consumers is reported as "" in HTTP API responses

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#26]
It should be `0.0` or `0`.

**Comment by simonmacmullen** [comment]
Why should it be 0.0? Really it's not defined when there are no consumers, so null or NaN would make more sense.

Reporting it as `""` is a bit unfortunate, sure. But that's an artefact of the way our info items return the zero length atom `''` for empty values, as `rabbitmqctl` expects. If you are going to change that behaviour, please don't just change this one field, make it generic that management converts `''` to something else.

See bug 26312 for the last time we had this conversation. In fact, you even did some work on it :smile:

**Comment by michaelklishin** [comment]
It should be null then but definitely not a string.

**Comment by michaelklishin** [comment]
Fixed in #74.
