### ISSUE TITLE
PUT /api/queues/{vhost}/{name} does not handle `null` node

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#27]
If a client sends `node` value = `null`, `rabbit_mgmt_util:http_to_amqp/5` fails with:

```
=ERROR REPORT==== 23-Mar-2015::15:29:19 ===
webmachine error: path="/api/queues/%2F/hop.test"
{error,{error,badarg,
              [{erlang,binary_to_list,[null],[]},
               {rabbit_mgmt_util,http_to_amqp,5,[]},
               {webmachine_resource,resource_call,3,[]},
               {webmachine_resource,do,3,[]},
               {webmachine_decision_core,resource_call,1,[]},
               {webmachine_decision_core,accept_helper,1,[]},
               {webmachine_decision_core,decision,1,[]},
               {webmachine_decision_core,handle_request,2,[]}]}}
```

Inspecting the code suggests it only handles `undefined` values.

**Comment by simonmacmullen** [comment]
Should it?

The approach up until now has been that if you don't want to set a key, you omit it. To me `{'node':null}` reads like you explicitly want to set the node to null, which doesn't make much sense.

**Comment by michaelklishin** [comment]
OK, fair enough. Jackson (by the far the most popular JSON serializer on the JVM) needs an explicit annotation to exclude `null` fields.
