### ISSUE TITLE
Node health check  with rabbitmq-server 3.6.4

### ISSUE THREAD

**Issue by zhiqi17** [rabbitmq/rabbitmq-management#270]
When an alarm is in effect, HTTP API reports Health check passed.

Does this version have this bug?

 `./rabbitmqctl node_health_check
Timeout: 70.0 seconds ...
Checking health of node 'rabbit@TEST001' ...
Error: resource alarm(s) in effect:[memory]`

`curl -L -u guest:guest   http://127.0.0.1:15672/api/healthchecks/node
{"status":"ok"}`

**Comment by MaxBarraclough** [comment]
How was this resolved?
