### ISSUE TITLE
Log client IP address and select HTTP headers in the HTTP access log

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-management#273]
Would it be possible to log client IP address in the HTTP access log produced by the management plug-in? We have an issue of someone banging against the management API with bad passwords, and we need to cut them off. 

In general, it would help if the HTTP access log follows what web servers produce, i.e. the NCSA log (no matter how it is formatted).

Also, perhaps we could log certain headers, such as X-Forwarded-For for when traffic goes through the load balancer or a reverse proxy, thus masking true client IP.

**Comment by essen** [comment]
As far as I can tell, this is already the case, at least on current stable and master. We use the Webmachine logger, and the first thing it puts in the logs is the IP. It also seems to follow the NCSA format. It also logs the referer and user-agent; but not x-forwarded-for (I am not sure if the IP logged is one found in forwarded or the peer IP, it's possible it's the forwarded IP directly).

Can you tell me what RabbitMQ version you are using, and how you are enabling/configuring the logs? Maybe there's an option I'm missing.

**Comment by uvzubovs** [comment]
When I submitted this, we were using 3.5.7. We have upgraded to 3.6.5 recently. Let me check again.

**Comment by uvzubovs** [comment]
Here is what this looks like in 3.6.5:

```
10.105.174.229 - - [28/Nov/2016:19:00:00 +0000] "GET /api/queues/Express-QA/bde-vfa/bindings HTTP/1.1" 200 340 "https://pivotal-rabbitmq.somehost.com/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
10.105.174.229 - - [28/Nov/2016:19:00:00 +0000] "GET /api/nodes HTTP/1.1" 200 30129 "" "Java/1.8.0_91"
10.105.174.228 - - [28/Nov/2016:19:00:01 +0000] "GET /api/queues/DataSync-DEV?page=1&page_size=100&name=&use_regex=false&pagination=true HTTP/1.1" 200 171633 "https://pivotal-rabbitmq.somehost.com/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
10.105.174.229 - - [28/Nov/2016:19:00:03 +0000] "GET /api/queues/DataSync-DEV/DataDistribution_BigData-LEAD-RTSF-UPS?lengths_age=60&lengths_incr=5&msg_rates_age=60&msg_rates_incr=5&data_rates_age=60&data_rates_incr=5 HTTP/1.1" 200 11155 "https://pivotal-rabbitmq.somehost.com/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36"
10.105.174.228 - - [28/Nov/2016:19:00:03 +0000] "GET /api/nodes HTTP/1.1" 200 30156 "https://pivotal-rabbitmq.somehost.com/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.105.174.228 - - [28/Nov/2016:19:00:39 +0000] "GET /api/vhosts HTTP/1.1" 200 28902 "https://pivotal-rabbitmq.somehost.com/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"

```
The IP address is that of the load balancer, and there is no X-Forwarded-For header (inserted by the load balancer).

**Comment by michaelklishin** [comment]
This will be addressed when we move Proxy protocol support into Ranch and Cowboy, and thus make it available to all plugins that use Cowboy (HTTP, WebSockets).
