### ISSUE TITLE
ReferenceError: data_reductions is not defined

### ISSUE THREAD

**Issue by pferrot** [rabbitmq/rabbitmq-management#275]
I get this error message when I click on a queue to view its details since I upgraded from 3.6.2 to 3.6.5.

![data_reductions_not_defined](https://cloud.githubusercontent.com/assets/12295384/17669013/4751c3ce-630c-11e6-97c2-f6d27d56aac9.png)

**Comment by michaelklishin** [comment]
I highly suspect that you simply need to clear your browser's cache. Please reopen with JS exception stack trace if that's not the case.

**Comment by michaelklishin** [comment]
Alternatively it could be an older API response getting to the new JS code. Still, sounds like a fairly basic JS code and API version mismatch.

**Comment by pferrot** [comment]
Thanks for the quick reply. It seems it was indeed a browser's cache issue.
