### ISSUE TITLE
Duplicate JSON key in queue info items (e.g. `GET /api/queues/{vhost}`)

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#278]
See the [group thread](https://groups.google.com/forum/#!topic/rabbitmq-users/2hifylvq_mM)

To reproduce the issue:

- Create a queue

- Publish and consume some message

- use `curl -X GET -u guest:guest http://localhost:15672/api/queues/%2F` 

Some  `json` parsers remove automatically the duplicates, hiding  this bug.

**Comment by dcorbacho** [comment]
@Gsantomaggio you probably want to extend the [format](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_event_collector_utils.erl#L49) functions to remove the `reductions` key.
