### ISSUE TITLE
Consider a "set user permission for all vhosts" function

### ISSUE THREAD

**Issue by jrlog** [rabbitmq/rabbitmq-management#293]
As the number of vhosts in our environment has grown, including growth in CF-generated vhosts (we're running in PCF), it has become very difficult maintain visibility into all vhosts for our admin users. 

At the moment, if we want visibility into all vhosts, we have to compile a list of vhosts that we have access to, compile a separate list of all defined vhosts, cross-reference the two lists to find the vhosts for which we're missing permissions, and then set permissions for ourselves for every vhost in that list. 

This would be easily resolved with a mechanism to set a user permission for all vhosts.

**Comment by michaelklishin** [comment]
We will but this belongs to rabbitmq-server.
