### ISSUE TITLE
CLI extension that clears stats database

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#295]
Now that [new CLI tools](https://github.com/rabbitmq/rabbitmq-cli) are merged, we should take advantage of their extensibility and provide a command that clears statistics database on a particular node (so, it will only target management plugin versions after #236, since that's what `3.7.0` will ship with).

**Comment by dcorbacho** [comment]
The command is implemented in the agent, as the stats db now resides there.
