### ISSUE TITLE
Custom response headers

### ISSUE THREAD

**Issue by carlhoerberg** [rabbitmq/rabbitmq-management#3]
What about including CORS headers in the response? 

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```

So that the API can be used from other clients?

**Comment by ceefour** [comment]
+1 for this. We're already using pure HTML5 RabbitMQ clients now using SockJS+stomp.js but it can only connect to the same RabbitMQ server as the web server IP due to this issue :(

**Comment by ceefour** [comment]
Sorry for unassigning @simonmacmullen. It must've been a GitHub bug... as I have no privileges whatsoever in this repo

**Comment by ceefour** [comment]
Mailing list thread: http://rabbitmq.1065348.n5.nabble.com/CORS-in-the-mgmt-http-api-td25693.html

However I just noticed that this is talking about **rabbitmq-management**, while what I'm looking for is CORS for [rabbitmq_web_stomp plugin](https://www.rabbitmq.com/web-stomp.html).

**Comment by michaelklishin** [comment]
@ceefour file a similar issue there, explaining what the current limitations are.

**Comment by michaelklishin** [comment]
Now that https://github.com/rabbitmq/rabbitmq-web-stomp/issues/12 is fixed, I think this can be closed unless someone comes up with more specific improvements.

**Comment by uvzubovs** [comment]
+10 

Being able to access management API from JavaScript (XHR) is very useful in developing dashboards that complement Rabbit management UI and don't provide access to queue/exchange manipulation, which is the #1 reason for restricting access to management UI in production.
