### ISSUE TITLE
Management DB crashes with 'badarith' if fd_used or disk_free temporarily unavailable

### ISSUE THREAD

**Issue by simonmacmullen** [rabbitmq/rabbitmq-management#30]
From an escalation:
```
 =ERROR REPORT==== 17-Feb-2015::21:14:31 ===
** Generic server rabbit_mgmt_db terminating
** Last message in was {'$gen_cast',
{event,
{event,node_stats,
<snip>
** Reason for termination ==
** {badarith,[{rabbit_mgmt_db,append_sample,6,[]},
{rabbit_mgmt_db,'-append_samples/6-lc$^1/1-0-',6,[]},
{rabbit_mgmt_db,append_samples,6,[]},
{rabbit_mgmt_db,handle_stats,6,[]} 
<snip>
```

So we get a `badarith` recording samples from `node_stats` - how can that be? `append_sample/6` guards against the new value not being a number, but does not check the old value from the `old_stats` table. Looking at `rabbit_mgmt_external_stats`, both `fd_used` and `disk_free` can return atoms when they failed to parse some external command.

Probably `append_sample/6` should just ignore the case where the old stat is not a number.

**Comment by michaelklishin** [comment]
Easy way to reproduce: temporarily change any numerical metric in `rabbit_mgmt_external_stats` to emit an atom some of the time:

``` erlang
i(proc_used,       _State) ->
  case random:uniform(100) > 50 of
    true  -> erlang:system_info(process_count);
    false -> blahblah
  end;
```
