### ISSUE TITLE
CORS support doesn't work

### ISSUE THREAD

**Issue by zywind** [rabbitmq/rabbitmq-management#301]
I'm using rabbitmq management REST APIs from webpages, but the CORs support doesn't seem to work. My test environment is Mac OS X 10.10.5, RabbitMQ 3.6.4. My rabbitmq.config is: 

```
[
  {rabbitmq_management,
    [{cors_allow_origins, ["*"]}]}
].
```

In my webpage, there is a fetch request to try to get the list of the queues available on the '/' vhost:
`fetch('http://localhost:15672/api/queues/%2f', {mode: 'cors', headers: {Authorization: 'Basic '+btoa('guest:guest')}})`

and I get the following error for that request
```
OPTIONS  XHR  http://localhost:15672/api/queues/%2f [HTTP/1.1 401 Unauthorized 1ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:15672/api/queues/%2f. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

You can run the same command using Firefox's console to test it.

I tried using curl, and it seems the rabbitmq server respond to the actual CORS request, but not the preflight options request correctly:
The actual request:
```
curl -H "Origin: http://localhost" -H "Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=" --head http://localhost:15672/api/queues/%2f

HTTP/1.1 200 OK
vary: Accept-Encoding, origin
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Sun, 27 Nov 2016 16:49:07 GMT
Content-Type: application/json
Content-Length: 7322
Cache-Control: no-cache
access-control-allow-origin: http://localhost
access-control-allow-credentials: true
```

The preflight options request:
```
curl -H "Origin: http://localhost" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: X-Requested-With" -X OPTIONS -H "Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=" --head http://localhost:15672/api/queues/%2f

HTTP/1.1 200 OK
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Sun, 27 Nov 2016 16:51:00 GMT
Content-Length: 0
```

Note that for the options request, the response header doesn't contain access-control-allow-origin fields etc., which might have caused the issue.

I have also tried this with a 3.6.5 rabbitmq server running on Ubuntu 16.04, and I got the same error.

**Comment by essen** [comment]
From memory of the code I am not surprised, I did not special case OPTIONS so that one also requires authentication; it probably shouldn't.

We have big changes planned soon and those do not have the issue (if you try 3.7.0 it should work as intended). If @michaelklishin thinks it's worthwhile I can fix the issue with the current code, otherwise we'll just apply the new correct server code.

**Comment by michaelklishin** [comment]
It would be great to fix it in stable or at least rabbitmq-management-236.

**Comment by essen** [comment]
CORS is applied much earlier with Cowboy so the issue should not be in 236. I will confirm on Tuesday.

**Comment by essen** [comment]
Alright so on master (and 236), headers are sent properly, but the request results in a 401 and *should* be rejected by browsers. There seems to be inconsistencies depending on browser/version in that behavior. The correct thing to do is to send a 200 response in that case, bypassing the authentication for OPTIONS requests.

**Comment by essen** [comment]
A PR is open for master. Will add a commit to 236 also.

**Comment by essen** [comment]
236 now has commit https://github.com/rabbitmq/rabbitmq-management/commit/aaf2276590c18a18053534c746c9166391265560 - it's the same, cherry-picked.

**Comment by michaelklishin** [comment]
This should be in `3.6.7` but just in case I'm setting the milestone to `3.7.0` for now.
