### ISSUE TITLE
channels unknown after restarting statistics database

### ISSUE THREAD

**Issue by NicholasMarty** [rabbitmq/rabbitmq-management#306]
Restarting the node hosting the statistics database or just restarting the statistics database as described [here](https://www.rabbitmq.com/management.html#stats-db) drops information about channels.

The connections themselves are still working like nothing happened. I'd therefore conclude that the AMQP channels also still have to exist.
The call to the Management Website "/#/channels" lists no channels:
![nochannels](https://cloud.githubusercontent.com/assets/19569510/20833926/6e5b65a2-b892-11e6-8ab2-4cabdd583af9.PNG)
Although for the connections is listed that there is a channel associated with:
![connections](https://cloud.githubusercontent.com/assets/19569510/20833898/52f888d0-b892-11e6-95ec-2791cad1bf45.PNG)

The call to the HTTP API "/api/channels" only lists an empty array as well:
> []

RabbitMQ Version 3.6.5 with Erlang Version 19.1

As the channel hold the information about what consumer is running on what connection that information would be quite useful to always have available without forcing clients to reconnect.

**Comment by michaelklishin** [comment]
We've merged #236 recently so this may or may not be relevant because it's a nearly a ground up reimplementation of the plugin.
