### ISSUE TITLE
Inconsistent Prefetch count values

### ISSUE THREAD

**Issue by cap10morgan** [rabbitmq/rabbitmq-management#311]
Observed: Depending on the order in which I subscribe to a queue vs. set the qos value on the channel, the Prefetch count in the management UI's Consumers table is different.

Expected: The Prefetch count value would be the same regardless of the order in which I subscribe vs. set the channel's qos value.

[Steps to reproduce](https://gist.github.com/cap10morgan/cb6e2567cd330a11e1424ed2cbe52dd8) (with Docker and Langohr in Clojure).

RabbitMQ versions: Seen in 3.6.2 and 3.6.5 (official Docker images)

The prefetch count in the "Details" section of the channel does accurately reflect the qos value in both scenarios, and the actual queue behavior _seems_ correct in both cases. So that's what makes me suspect this is just a management UI bug. But I'm not 100% certain of that.

**Comment by michaelklishin** [comment]
This is a [documented behaviour](http://www.rabbitmq.com/consumer-prefetch.html) and a lesser known protocol feature. Yes, order matters and QoS is often set up right after channel is opened.

**Comment by cap10morgan** [comment]
@michaelklishin OK, thanks for that link. But that doc still doesn't seem to explain what should happen in the case of subscribing and then setting non-global qos on the channel. I would love to know what the expected behavior is there.

**Comment by michaelklishin** [comment]
"`prefetch_count` with global set to `false`: applied separately to each new consumer on the channel…"

**Comment by michaelklishin** [comment]
"`prefetch_count` with global set to `true`: shared across all consumers on the channel…" (note: no mentions of "new")

**Comment by cap10morgan** [comment]
@michaelklishin OK so should I infer that the "new" in that statement is very intentional and that the pre-existing consumer should _not_ be expected to get the qos setting?

This is surprising because we were pretty sure we observed the opposite behavior (i.e. that the pre-existing consumer _did_ get the qos setting behavior-wise). We'll double-check, though. Thanks again!

**Comment by michaelklishin** [comment]
@cap10morgan just configure QoS after opening a channel. This is one of the protocol features I wish we could get rid of but it's way too late.

**Comment by cap10morgan** [comment]
@michaelklishin 10-4. We are changing our code to do it this way from now on.
