### ISSUE TITLE
No mention of api/federation-links in RabbitMQ Management HTTP API reference

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-management#313]
RabbitMQ Management HTTP API reference (at /api) does not mention uses of api/federation-links although it is listed in https://www.rabbitmq.com/federation-reference.html

**Comment by michaelklishin** [comment]
That document only lists what's in the management plugin, not management plugin plugins. Individual plugins document their own HTTP API endpoints.
