### ISSUE TITLE
Errors on Limits page and Policies page 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#325]
There are two typo link errors in `dispatcher.js`:
1.'/vhost_limits' should be '/vhost-limits'
2. `operator_policies` should be `operator-policies`

The  `Limits` page does not show the items when a `vhost` is filtered:

![error](https://cloud.githubusercontent.com/assets/386987/21881185/312cc474-d8a3-11e6-830d-6c29d728e766.png)

**Comment by michaelklishin** [comment]
The path was changed in https://github.com/rabbitmq/rabbitmq-management/commit/e9e2e5dc90106af5f735a0079549b217e2760378, good catch.

**Comment by Gsantomaggio** [comment]
The Limits page problem seems to be a server problem:

The API `http://localhost:15672/api/vhost-limits` returns:
```
[

    {
        "vhost": "/",
        "value": {
            "max-queues": 999,
            "max-connections": 1
        }
    },
    {
        "vhost": "r",
        "value": {
            "max-queues": 11,
            "max-connections": 6
        }
    }

]
```

The vhost API `http://localhost:15672/api/vhost-limits/r` returns:

```
{

    "max-connections": 6,
    "max-queues": 11

}
```
but it should be:

```
[

    {
        "vhost": "/",
        "value": {
            "max-queues": 999,
            "max-connections": 1
        }
    }
]
```
is that right ?

**Comment by michaelklishin** [comment]
@Gsantomaggio why would a response to fetch a limit for a specific vhost also return that vhost? For listing of *all* limits that makes sense.

**Comment by dcorbacho** [comment]
Fixed on https://github.com/rabbitmq/rabbitmq-management/commit/f608459cb0c21b3c7c0af090303974a41b78b17a, https://github.com/rabbitmq/rabbitmq-management/commit/6d52f9e924711f9f109c8c4a5bb2575f06492f4e and https://github.com/rabbitmq/rabbitmq-management/commit/3d97129ca98f074dbf2019c34ef94374216a8d94

**Comment by Gsantomaggio** [comment]
Just to follow the standard, the other API(s) work in this way:

for example: `http://localhost:15672/api/policies` returns 
```
[

    {
        "vhost": "/",
        "name": "a",
        "pattern": "",
        "apply-to": "all",
        "definition": {
            "ha-mode": "all"
        },
        "priority": 0
    },
    {
        "vhost": "/",
        "name": "pippo",
        "pattern": "",
        "apply-to": "all",
        "definition": {
            "ha-mode": "all"
        },
        "priority": 0
    },
    {
        "vhost": "r",
        "name": "aaaaaaaa",
        "pattern": "",
        "apply-to": "all",
        "definition": {
            "ha-mode": "all"
        },
        "priority": 0
    }

]
```

and `http://localhost:15672/api/policies/r` returns:

```
[

    {
        "vhost": "r",
        "name": "aaaaaaaa",
        "pattern": "",
        "apply-to": "all",
        "definition": {
            "ha-mode": "all"
        },
        "priority": 0
    }

]
```

same thing as the `queues`, `exchanges` etc.. `Limits` is the only exception.
The item it is always retuned with the `vhost` ant other info.

In this way the users have always the same output and not two different `JSON`

**Comment by michaelklishin** [comment]
@Gsantomaggio OK, feel free to make the change, it's harmless and there are no existing users of this endpoint at the moment.
