### ISSUE TITLE
Pre-3.6.7: deliver rate on the Overview tab is always 0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#338]
I can reproduce this with AMQP 0-9-1 or MQTT clients:

 * Start a publisher that publishes anywhere between 200 to 5000 messages/second
 * Start a consume that consumes and prints messages

Observe that client network traffic and queue rates are non-zero, as is publishing rate in Overview.
Unfortunately delivery rate in Overview is always 0.

**Comment by michaelklishin** [comment]
Noticed when QA'ing https://github.com/rabbitmq/rabbitmq-mqtt/issues/122 (https://github.com/rabbitmq/rabbitmq-mqtt/issues/121).

**Comment by michaelklishin** [comment]
One more observation: as soon as I switch my consumer to manual acknowledgements and about 2 stats emission intervals pass, both delivery and acknowledgement rates in Overview are what I'd expect them to be (roughly match the publishing rate).

**Comment by kjnilsson** [comment]
The UI displays the "no ack" delivery rate separately from the one using manual acks. Closing.

<img width="385" alt="screenshot 2017-01-27 09 34 12" src="https://cloud.githubusercontent.com/assets/1180564/22366349/16c7ef46-e474-11e6-8790-5c3ccf49fa1f.png">

**Comment by michaelklishin** [comment]
🤦‍♂️. Sorry. I filed #339 so that we can make both rates easier to spot.
