### ISSUE TITLE
Connections and channel tabs in the UI should respect active vhost

### ISSUE THREAD

**Issue by eugenebell** [rabbitmq/rabbitmq-management#34]
When viewing the Connections and Channels the Virtual host filter does not filter the connections/channels to the selected virtual host. On closer inspection it looks like the API request does not add the select virtual host as seen in Exchanges and Queues views.

Example Queue request filtering by virtual host call 'vhost1': http://localhost:15672/api/queues/vhost1
Example Connection request filtering by virtual host call 'vhost1': http://localhost:15672/api/connections -> missing vhost1. 

Might need to add these API calls as well:
/api/channels/{vhost}
/api/connections/{vhost}
 as manually calling gives an "Object not found response".

**Comment by michaelklishin** [comment]
I have a fix in the works, unfortunately, it requires more changes than I expected and can't got into a bug fix release.

**Comment by michaelklishin** [comment]
@eugenebell fixed and will be in `3.6.0`.
