### ISSUE TITLE
rabbitmqadmin table listing can't handle Unicode

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#343]
From [stackoverflow](http://stackoverflow.com/questions/42053119/rabbitmqadmin-cant-handle-unicode)

Steps how to reproduce the queue name issue:

1. Create a queue with unicode in it: `rabbitmqadmin declare queue name=ööö`
2. List queues: `rabbitmqadmin list queues`

The problem is this [`str`](https://github.com/rabbitmq/rabbitmq-management/blob/rabbitmq-management-325/bin/rabbitmqadmin#L774) conversion.

**Comment by michaelklishin** [comment]
Note that we still support Python 2.7.x and 3.x ;)

**Comment by Gsantomaggio** [comment]
Yes, this bug affects only `Python 2.7.x`  with `Python3` it works :)
