### ISSUE TITLE
NULL char in queue name

### ISSUE THREAD

**Issue by bsibaud** [rabbitmq/rabbitmq-management#351]
WIth RabbitMQ 3.6.5 or 3.6.6, you can create a queue with a NULL char in its name, via API, but expect issues to manage them with rabbitmq-management.

With Firefox 51.0.1:
- the NULL is not displayed in the "name" field on http://127.0.0.1:15672/#/queues or on http://127.0.0.1:15672/#/queues/vhost/xxxx%00xxxx queue's page.
- you can't delete the queue from the queue's page (click on Delete, confirm, nothing happens). DELETE request is sent to http://127.0.0.1:15672/api/queues/vhost/xxxx%EF%BF%BDxxxx  (HTTP 404).

With Chromium 53.0.2785.143:
- the NULL is not displayed in the "name" field on http://127.0.0.1:15672/#/queues 
- you can't access to the queue's page:

main.js:1037 XMLHttpRequest cannot load http://127.0.0.1:15672/api/queues/vhost/xxxx%00xxxx?lengths_age=60&lengths_incr=5&msg_rates_age=60&msg_rates_incr=5&data_rates_age=60&data_rates_incr=5. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Queue created with:

curl -i -u user:pass -H "content-type:application/json" -v -d '{"auto_delete":false,"durable":true,"arguments":[]}' -X PUT "127.0.0.1:15672/api/queues/vhost/xxxx%00xxxx"

Queue deleted with:

curl -i -u user:pass -H "content-type:application/json" -v -X DELETE "127.0.0.1:15672/api/queues/vhost/xxxx%00xxxx"

**Comment by michaelklishin** [comment]
No messaging protocols I'm aware of allow for `\0` characters to be used in queue/topic/etc names,
so arguable it's an application and client responsibility to account for that.

This is not the first time we see this, so it was addressed in https://github.com/rabbitmq/rabbitmq-server/issues/710 and will be available in the 3.7.0 release.
