### ISSUE TITLE
No feedback when non-admin user tries to force close a connection

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-management#355]
When a non-admin user tries to force-close a connection, management UI accepts the command but nothing happens -- connection is not closed and no feedback to the user about insufficient privilege. Rabbit 3.6.6.

**Comment by dcorbacho** [comment]
This is already solved in 3.6.9, a pop-up notifies of the lack of privileges.

<img width="1171" alt="screen shot 2017-05-04 at 2 04 16 pm" src="https://cloud.githubusercontent.com/assets/646577/25704812/e4ef79b6-30d2-11e7-9c6a-81ae1dc78aff.png">
