### ISSUE TITLE
Admin does not work well with queues with an empty name

### ISSUE THREAD

**Issue by vStone** [rabbitmq/rabbitmq-management#36]
We have managed to create a queue (Unknown how this happened, I blame java) with an empty name and I am unable to remove it using the webui.

RabbitMQ 3.3.4, Erlang R15B01

**Comment by michaelklishin** [comment]
Empty queue name would case a name to be generated. So you have unprintable characters in the name. See [this mailing list thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/unprintable/rabbitmq-users/IhxqihCO3cc/zp7wtqKDoyYJ). I can't know how that happens but it is a lot more likely with `rabbitmqadmin` or similar tools that accept input from the command line.

I'm not sure how much RabbitMQ can do about that without potentially breaking legitimate cases.

**Comment by vStone** [comment]
In case somebody runs into the same problem:
```
rabbitmqctl eval '{ok, Q}=rabbit_amqqueue:lookup(rabbit_misc:r(<<"/">>, queue, <<"">>)),rabbit_amqqueue:delete(Q,false,false).'
```
