### ISSUE TITLE
Queue page's Get Messages button appears to be broken in 3.6.7 in Edge

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-management#362]
After installing 3.6.7, it appears that the Get Messages button on the Queue page doesn't work any more. I have a message in a queue, but when I click the button, I don't see any of the details that I used to see:

![get-message](https://cloud.githubusercontent.com/assets/753669/24016001/ce8e5310-0a60-11e7-8626-efae6cd7778a.PNG)

Clicking the button makes the part of the page below the button jump a bit, but nothing else seems to happen.

**Comment by michaelklishin** [comment]
What do you see in the developer console and server logs?

**Comment by michaelklishin** [comment]
I just tried and I do see a message consumed and its information displayed.

**Comment by bording** [comment]
Trying to compile a bit more information, but it looks like it's browser-specific. On Chrome 57 it's working fine, but on Edge is where I'm seeing the problem.

It looks like it works fine on Firefox 52 as well.

For various reasons, I tend to use Edge for the RabbitMQ management page, so I know it was working fine before. I'll dig into the reason for the failure and provide more details on what it's complaining about.

**Comment by bording** [comment]
When the problem is happening here's what I'm seeing in the Edge console: 

![edge-console](https://cloud.githubusercontent.com/assets/753669/24016997/ac8aabe8-0a64-11e7-9422-5d87e1347909.PNG)

However, if I open Fiddler to intercept and view the HTTP traffic, the server reponse appears to be 200, not 400 like the console shows.

One other weird thing is if I ctrl-F5 to force a cache refresh while Fiddler is open, then everything starts working fine.

If I then close Fiddler and ctrl-F5 again, it breaks again.

Are they any sort of management UI server logs that would be helpful? I regular server log doesn't show anything relevant.

**Comment by michaelklishin** [comment]
Thank you @bording. This is enough information to work with.

**Comment by michaelklishin** [comment]
The most reliable way of capturing traffic is [Wireshark](https://www.rabbitmq.com/amqp-wireshark.html).

**Comment by bording** [comment]
I do have Wireshark installed as well, if you end up needing a traffic capture.

**Comment by michaelklishin** [comment]
Well, there are few sources of information that reveal more than Wireshark. Please take a capture and upload it somewhere?

**Comment by bording** [comment]
Here's a capture: https://www.dropbox.com/s/1xzlwapqmxnrmrj/Capture.pcapng?dl=0

I refreshed the page and clicked the button. Sometimes after refreshing the page, the button would work, and sometimes it would fail.

**Comment by michaelklishin** [comment]
We believe this is https://github.com/rabbitmq/rabbitmq-management/issues/377.
