### ISSUE TITLE
Startup crashes when both Management and Shovel plugins are enabled

### ISSUE THREAD

**Issue by rtraschke** [rabbitmq/rabbitmq-management#368]
You can get intermittent startup crashes when having both the Management and the Shovel plugins enabled on a node. The usual error you will see in the logs contains this:

```
** Reason for termination == 
** {badarg,[{ets,member,[pg2_table,{group,rabbit_shovel_dyn_worker_sup_sup}],[]},
            {pg2,create,1,[{file,"pg2.erl"},{line,50}]},
            {mirrored_supervisor,handle_call,3,
                                 [{file,"src/mirrored_supervisor.erl"},
                                  {line,288}]},
            {gen_server2,handle_msg,2,
                         [{file,"src/gen_server2.erl"},{line,1011}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

The way that the Management plugin is started, means that the `rabbit_mgmt_sup` is started in the background (see the `rabbit_mgmt_sup_sup:init/1`).

The `rabbit_mgmt_sup` uses the behaviour `mirrored_supervisor`.

The `mirrored_supervisor` uses `pg2` internally, and `pg2` uses an `ets` table called `pg2_table`.

When a `mirrored_supervisor` first calls `pg2:create/1`, `pg2` will check if its server is running, and if it isn't it gets started. This is when the `pg2_table` first gets created.

Because `rabbit_mgmt_sup` is started concurrently, a following plugin that uses the behaviour `mirrored_supervisor`, like the Shovel, can end up calling `pg2:create/1` at the same time.

Since the `pg2` server is already in the process of starting, a process under that name has been registered. This leads to the situation where the second call to `pg2:create/1` hits the code path that assumes `pg2` has been fully initialised and this can lead to the call to `ets:member/2` exiting with a `badarg`, since the `pg2_table` may have not yet been created at that point.

**Comment by michaelklishin** [comment]
Is there a proposed solution? Should plugins that rely on `mirrored_supervisor` (which we hope to get rid of in the long term, by the way) inject a small random delay?

**Comment by rtraschke** [comment]
A brute force approach would be to check that either `pg2` is not yet registered or that if it is registered, the `pg2_table` exists.

**Comment by rtraschke** [comment]
I guess an issue against OTP could be raised, to state that calling `pg2:create/1` in concurrent processes leads to race conditions.

**Comment by rtraschke** [comment]
Ah, just noticed that this is potentially already fixed.

**Comment by michaelklishin** [comment]
@rtraschke we should look into a workaround of our own since OTP issues take a long time to propagate into a widely used release.

I think checking for a table with a delay between retries is a low risk solution. @kjnilsson @dcorbacho WDYT?

**Comment by rtraschke** [comment]
OK, I believe this was fixed in release 3.6.7.
The `rabbit_mgmt_sup_sup` there no longer contains the starting in the background.

**Comment by rtraschke** [comment]
I will close this issue, and re-open if testing shows this to be untrue :-)

**Comment by rtraschke** [comment]
Just to note, this issue can appear in versions 3.5.7 through 3.6.6.
