### ISSUE TITLE
Creating a user with "No password" option fails with "no_password_or_password_hash_provided"

### ISSUE THREAD

**Issue by jrlog** [rabbitmq/rabbitmq-management#383]
I recently upgraded to version 3.6.9 and noticed that I am not able to create a user with "No password" (i.e. for use with external authentication via LDAP). The "No password" option is still present in the form, but selecting it and clicking "Add user" now produces a yellow pop-up error that says "no_password_or_password_hash_provided".

**Comment by michaelklishin** [comment]
We should probably remove the option or replace it with a "generated password" but that term means something else to many developers. Or document when passwords are ignored entirely.

Allowing for blank passwords is also a guaranteed way to get a myriad of automated scanners to report a vulnerability.

**Comment by jrlog** [comment]
Thanks Michael. I've been working around this in our sandbox environment by creating users with dummy passwords and then using "rabbitmqctl clear_password username" to clear the password. It works well enough for some simple user administration tasks. 

I have vhost-creation scripts that add users without a password, and these scripts have been working fine up to 3.6.6. It looks like when we upgrade, the scripts will start failing with the same "no_password_or_password_hash_provided" error. I imagine that we could mass-alter the scripts to perform the same workaround (i.e. define with temporary password, then clear the password), but I have not tested this in the HTTP API.

**Comment by agwaltz** [comment]
We need this for creating users for TLS authentication ex: https://weblogs.asp.net/jeffreyabecker/Using-SSL-client-certificates-for-authentication-with-RabbitMQ

The workaround by @michaelklishin works however.

**Comment by jason-archidera** [comment]
We are using the LDAP plug-in for authN and the internal RabbitMQ db for AuthZ since it's easier to be more granular on read/write permissions.  Please do not get rid of the blank passwords until so other method of handling this is created.

**Comment by michaelklishin** [comment]
@jason-archidera there are no plans to remove support for "passwordless" users, although the exact mechanism may change at some point.

**Comment by michaelklishin** [comment]
I have a fix, finishing local QA but should be up for a review tomorrow.
