### ISSUE TITLE
I/O average time per operation graph doesn't match legend in 3.6.9

### ISSUE THREAD

**Issue by cap10morgan** [rabbitmq/rabbitmq-management#384]
In RabbitMQ 3.6.9: 
<img width="668" alt="screen shot 2017-04-26 at 10 44 49 am" src="https://cloud.githubusercontent.com/assets/59748/25451270/d8cc7dbe-2a7e-11e7-9f93-ee96bf24b155.png">

Note the discrepancy between the "File handle open attempt" legend value and where the line is at in the graph.

Here's the same chart from a 3.6.6 cluster (I don't have any instances of versions 3.6.7 or 3.6.8 to test with unfortunately):
<img width="616" alt="screen shot 2017-04-26 at 12 51 27 pm" src="https://cloud.githubusercontent.com/assets/59748/25451370/300bc742-2a7f-11e7-8ebc-2687d9e3a998.png">

I'll see if I can figure out some simple steps to reproduce. I'm running the `3.6.9-management-alpine` docker image in a 5-node cluster in case that helps.

**Comment by michaelklishin** [comment]
@cap10morgan thank you. I suspect that running a publisher publishing a lot of small persistent messages to a durable queue should produce a healthy rate of file handle open attempts for new queue index segment files.

**Comment by cap10morgan** [comment]
I was able to reproduce this by running the `rabbitmq:3.6.9-management` Docker container, connecting to the management UI, and letting it sit for a few minutes. It looks like the graph is just off by a few orders of magnitude (e.g. 0.11ms in the legend shows up as 1,100ms in the graph).
