### ISSUE TITLE
change default displaying language of rabbitmq management

### ISSUE THREAD

**Issue by BigSully** [rabbitmq/rabbitmq-management#395]
The rabbitmq-management is displayed in English. I want to change it to other language, but I didn't find some place in the web management to achieve this.Did I miss something?

**Comment by michaelklishin** [comment]
You did not.

You can build your own management UI using the same [HTTP API](https://rawcdn.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_9/priv/www/api/index.html) but some messages and values returned in the API do not support i18n.

Unfortunately i18n is not a priority for our team (and honestly, not a commonly requested feature).
However, a custom management UI can get you most of the way there if it's important for you.

Please post questions to rabbitmq-users in the future.
