### ISSUE TITLE
Exclusive queues should have a clearly named field in the info payload

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#40]
Exclusive queues are currently indicated via non-blank `owner_pid_details` in the payload. That's internal implementation details leaked. This is very confusing.

Management API should include a boolean field for `exclusive`.

**Comment by Ayanda-D** [comment]
@michaelklishin  proposal here is to add another clause for [`rabbit_mgmt_format:queue`](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_format.erl#L227). 
- On first clause, add guard to check if `exclusive_owner` field in `#amqqueue{}` is_pid. If PID, add `{exclusive,  true}` to the tuple list being passed to the [`format`](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_format.erl#L234) function.  
- On second clause, no guard, i.e. `exclusive_owner` not PID, add `{exclusive,  false}` to the tuple list passed in [`format`](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_format.erl#L234) function..

This should add a boolean field for `exclusive` in Management API. Is this okay?

**Comment by michaelklishin** [comment]
@Ayanda-D either that or something like

``` erlang
{exclusive, is_pid(ExclusiveOwner)}
```

**Comment by Ayanda-D** [comment]
@michaelklishin okay thanks. Much simpler :)

**Comment by michaelklishin** [comment]
Fixed in master.
