### ISSUE TITLE
Investigate how channel listing can be made more more efficient

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#401]
See https://github.com/rabbitmq/rabbitmq-management/pull/399 for the idea. We should explore doing the same for endpoints that list channels.

**Comment by kjnilsson** [comment]
I've given this a bit of thought and come up with a potential approach that is similar to what was done in #418 .

Currently all filtering is done on the [full result set](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_channels.erl#L53)
It is possible to calculate an "augmentation spec"  that is passed to each node to use to reduce the dataset and augmentation it returns back for aggregation.

The "spec" should contain the following information:

* vhost - for filtering
* user + tags - filtering
* a flag indicating whether augmentation is needed (when only a basic set of columns is requested).
* sort columns
* pagination parameters.

To ensure enough records are returned by each node to correctly build up a full page each node needs to return _all_ pages prior to the one requested. This means the last page will return the full set as before however prior pages should reap some benefit.

**Comment by michaelklishin** [comment]
[Prometheus and Grafana support](https://www.rabbitmq.com/prometheus.html) largely supersede this.
