### ISSUE TITLE
Fields selection

### ISSUE THREAD

**Issue by mirkods** [rabbitmq/rabbitmq-management#403]
Hi there,
Is there any way to filter the fields in the response? In my case I need to know the names of my queues but I can't to download a big json that contains all the keys of the queue model.
How can I filter the result?

Mirko

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users in the future. This team does not use GitHub issues for questions.

You can [limit the number of fields](https://rawcdn.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_10/priv/www/api/index.html) but you cannot exclude all of them but the name, I don't think.

You can do that with `rabbitmqctl list_queues`, if that's an option .

**Comment by mirkods** [comment]
So in this case I think this can be considered a valid issue. In this moment most of all the rest api available support fields selection in order to reduce overhead.

**Comment by mirkods** [comment]
Ok, it is possible to filter the fields using the `colums` query parameter.

**Comment by michaelklishin** [comment]
@mirkods so is there still a feature request from you? :)

**Comment by mirkods** [comment]
No thanks, from the documentation my case is covered using `colums=name` and I'm able to get only the name field

**Comment by michaelklishin** [comment]
Excellent. We will try to make it more obvious/discoverable in the management plugin's HTTP API section.

**Comment by Gsantomaggio** [comment]
@michaelklishin it seems that it is not possible to combine `colums` parameter with paginations parameters:

This works:
`http://localhost:15672/api/queues?columns=name` 


This does not work(empty result):
`http://localhost:15672/api/queues?columns=name&page=1&page_size=1` 
(same `http://localhost:15672/api/queues?page=1&page_size=1&columns=name`)

Should we consider to implement/fix it ?

**Comment by michaelklishin** [comment]
@Gsantomaggio sure, please file a separate issue and feel free to take a look at it :)

**Comment by Gsantomaggio** [comment]
Done: https://github.com/rabbitmq/rabbitmq-management/issues/404

cc @mirkods if you are interested on it :)

**Comment by mirkods** [comment]
Thanks @Gsantomaggio!
