### ISSUE TITLE
columns parameter does not work with paginations parameters

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#404]
It seems that it is not possible to combine `columns` parameter with pagination parameters

This works:
`http://localhost:15672/api/queues?columns=name`

This does not work(empty result):
`http://localhost:15672/api/queues?columns=name&page=1&page_size=1`
(same `http://localhost:15672/api/queues?page=1&page_size=1&columns=name`)

**Comment by binarin** [comment]
Another good improvement in this regard would be skipping augmenting information when no extended columns are requested - something like #399 does for paging.

**Comment by mirkods** [comment]
I don't know if we can consider this a separated issue but using a regex in the name field does not work without pagination, in summary:

```
- http://localhost:15672/api/queues?name=fifo-*&use_regex=true&pagination=true&page=1&page_size=300 // this filter correctly

- http://localhost:15672/api/queues?name=fifo-*&use_regex=true // this not
```

Best,
Mirko

**Comment by Gsantomaggio** [comment]
@binarin yes, I think so

**Comment by Gsantomaggio** [comment]
@mirkods yes, these filters are [available only for pagination](https://github.com/rabbitmq/rabbitmq-management/blob/stable/src/rabbit_mgmt_util.erl#L436). 
Originally  we wanted to discourage to use `/queues` API and use pagination API(s)

We could move this filters outside paginations.

thoughts ? 
@michaelklishin @kjnilsson @dcorbacho

**Comment by Gsantomaggio** [comment]
Looking inside this issue, I found another bug currently only in `stable`:

by executing this call works correctly on `3.6.10`:

```
➜  sbin ./rabbitmqctl eval 'rabbit_mgmt_db:augment_queues([[{name,<<"a">>},{durable,true},{vhost,<<"/">>}]],{no_range,no_range,no_range,no_range},basic).'
[[{name,<<"a">>},{durable,true},{vhost,<<"/">>}]]
```
the same call on `stable`:
```
➜  sbin ./rabbitmqctl eval 'rabbit_mgmt_db:augment_queues([[{name,<<"a">>},{durable,true},{vhost,<<"/">>}]],{no_range,no_range,no_range,no_range},basic).'
Error: {{badarg,
            [{erlang,node,[unknown],[]},
             {delegate,'-group_pids_by_node/1-fun-1-',3,
                 [{file,"src/delegate.erl"},{line,199}]},
             {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
             {delegate,invoke,3,[{file,"src/delegate.erl"},{line,116}]},
             {rabbit_mgmt_db,adjust_hibernated_memory_use,1,
                 [{file,"src/rabbit_mgmt_db.erl"},{line,650}]},
             {timer,tc,2,[{file,"timer.erl"},{line,181}]},
             {rabbit_mgmt_db_cache,handle_call,3,
                 [{file,"src/rabbit_mgmt_db_cache.erl"},{line,107}]},
             {gen_server,try_handle_call,4,
                 [{file,"gen_server.erl"},{line,615}]}]},
        {gen_server,call,
            [<10522.485.0>,
             {fetch,#Fun<rabbit_mgmt_db.22.98651915>,
                 [[[{name,<<"a">>},{durable,true},{vhost,<<"/">>}]]]},
             60000]}}
```

**Comment by Gsantomaggio** [comment]
Closed via https://github.com/rabbitmq/rabbitmq-management/issues/417
