### ISSUE TITLE
Potential definitions import regression

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#414]
See [this report on rabbitmq-users](https://groups.google.com/forum/#!topic/rabbitmq-users/HHd-uMO9bCI), however, the logs are not silent in my case: looks like existing vhosts are used as input instead of what's in the JSON file.

UPD: I found a few things that can make definition import confusing but the import seems to succeed.

**Comment by michaelklishin** [comment]
[3.6.0_all_vhosts.json.zip](https://github.com/rabbitmq/rabbitmq-management/files/1064058/3.6.0_all_vhosts.json.zip) is the file I used to reproduce.

**Comment by michaelklishin** [comment]
Importing my definitions file works in the end, it just takes a moment for 15K queues to import
and initialize.

I tried with

 * rabbitmq-management built from source (the tip of stable)
 * 3.6.10

What I did discover, however, is that the Import Succeeded template
is rendered a bit too quickly.

Another potentially confusing thing is that you can import definitions for all vhosts
or a single existing vhost (in which case its definitions are merged and all other definitions are ignored).

I'm going to ask a few more team members to verify my findings.

**Comment by lukebakken** [comment]
Everything works as described by @michaelklishin in my environment (`stable` and `3.6.10`). "Import Succeeded" rendered almost immediately, and I did see items imported in the log file.

**Comment by oneiros-de** [comment]
I suppose it's a browser issue - it work with Google Chrome. Sorry for the noise.
