### ISSUE TITLE
Overview Totals can be changed all at once

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-management#416]
It's frustrating for size & type to be per time series but time range for all time series. All changes should be possible for individual time series as well as all time series.

This is an early prototype that breaks a lot of stuff, but at least gives an idea of what this change would look like. Thoughts @michaelklishin @dcorbacho ?

![image](https://user-images.githubusercontent.com/3342/27145260-fb909fae-512c-11e7-9cec-49d1f7e53cf7.png)

**Comment by michaelklishin** [comment]
[Prometheus and Grafana support](https://www.rabbitmq.com/prometheus.html) supersede this.
