### ISSUE TITLE
Import definitions doesn't apply vhost limits to number of queues

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-management#423]
Importing definitions allows to create an unlimited number of queues even when vhost limits are set.

Validation should fail with an option to let the user decide whether or not to proceed, as importing L out of N queues may be OK but the user will not know which ones will be imported. An improvement would be confirmation screen with a warning. Per conversation with @michaelklishin.

**Comment by michaelklishin** [comment]
Of course, this is only a problem with L (the limit) is greater than N (the number of queues in a vhost being imported).

**Comment by lukebakken** [comment]
The code that handles an import skips validation by calling `rabbit_amqqueue:declare` directly, while the code that handles a request to add a single queue sends a `queue.declare` message via `amqp_channel:call`. The latter's handler does the validation.

I'm assuming that the import code does not use `amqp_channel:call` for performance or other reasons - is this correct? I could switch import to use the same method to import a batch of queues as is done for a single queue.

Or, I could move validation into `rabbit_amqqueue:declare` itself, but I would have to evaluate how `exit` exceptions raised there could cause issue.

@michaelklishin - thoughts or other suggestions?

**Comment by michaelklishin** [comment]
I highly doubt that Erlang client connections are used for efficiency reasons. We already decided to not use them in #421 for different reasons.

Key issue here is that we do not take into consideration how many queues we will be importing and validate that against effective limit for each vhost. I don't think `rabbit_amqqueue:declare/7` should try to perform this kind of validation. We should introduce a new function that takes limits
into accounts (e.g. `declare_if_queue_count_limit_not_reached/7`).

But even that may be unnecessary. Before we attempt to declare anything we should see whether it's safe to proceed and display a page that asks for user confirmation with a strong warning ("some queues will not be imported") and a way to cancel. Once that is in place, per-operation validation becomes largely a non-issue here.

**Comment by lukebakken** [comment]
> I highly doubt that Erlang client connections are used for efficiency

Apologies, my statement was worded poorly ( the import code does **not** use amqp_channel:call for performance or other reasons).

I'll see about having a confirmation popup if queue limits are in place and will see how feasible it is to compare that limit with the count of queues that may be imported. It would be nice to tell the user that their limit is `8` queues but they're trying to import `10`, for instance.

**Comment by michaelklishin** [comment]
@lukebakken yes, that's a good idea.
