### ISSUE TITLE
Improve "network partition detected" warning to give solutions

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-management#43]
The following warning is frightening and doesn't give constructive solutions to move forward:
> Network partition detected
> Mnesia reports that this RabbitMQ cluster has experienced a network partition. This is a dangerous situation. RabbitMQ clusters should not be installed on networks which can experience partitions.

**Comment by michaelklishin** [comment]
Yes, this has to change. It should say on "networks with high probability of partitions, e.g. WAN" or something along those lines.

**Comment by dumbbell** [comment]
@michaelklishin, I made the above commit before seeing your message. What do you think?

**Comment by michaelklishin** [comment]
@dumbbell :+1:
