### ISSUE TITLE
rabbitmqadmin: support --uri for HTTP API

### ISSUE THREAD

**Issue by j3pic** [rabbitmq/rabbitmq-management#437]
Based on the output of `rabbitmqadmin --help`, it looks like it is necessary to manually break apart the elements of an amqp:// URI (obtained from another app's config) into separate `--username`, `--password`, `--host`, `--port`, and `--path-prefix` parameters. It would be nice if there was a `--uri` option that just accepted a URI.

**Comment by michaelklishin** [comment]
I assume you mean URI (for HTTP API endpoint with an optional prefix), not URL.

Feel free to look into a pull request.

**Comment by michaelklishin** [comment]
Also, this client is for [RabbitMQ HTTP API](http://www.rabbitmq.com/management.html), so using URIs with `amqp` and `amqps` schemes with it won't be possible. We'll assume the request is for `http` and `https` URIs.
