### ISSUE TITLE
3.7 - no access to vhost page for admin user.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#444]
In `master` when adding a new vhost without any permissions, the vhost page access is refused even for the admin user. 
In `stable` admin can access the page.

**Comment by dcorbacho** [comment]
The problem has been introduced by listing exchanges to add topic permissions in the vhost page. The API call to `exchanges/:vhost` uses [`rabbit_mgmt_util:is_authorized_vhost/2`](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_exchange.erl#L82), which refuses the access as it only checks the `rabbit_user_permission` table. This also means that both in `master` and `stable`, the exchanges page on the new vhost generates an access refused error.

@michaelklishin, @hairyhum shall we allow access to `administrator` tags on both cases?

**Comment by michaelklishin** [comment]
@dcorbacho allowing administrators to list permissions (both topic and regular ones) seems fine to me.
