### ISSUE TITLE
rabbitmqadmin: ssl-disable-hostname-verification does not appear to take effect

### ISSUE THREAD

**Issue by warmfusion** [rabbitmq/rabbitmq-management#452]
As shown below, when connecting to a broker node using valid test credentials, against self-signed CA and certificates with the `-s` ssl option and certificate verification disabled, the admin command aborts reporting certificate errors.

```
 rabbitmqadmin -s --ssl-disable-hostname-verification --username=admin --password=admin list users
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 490, in http
    conn.request(method, path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1250, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
*** Could not connect: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Environment details;

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

$ python -V
Python 2.7.9

$ rabbitmqadmin --version
rabbitmqadmin 3.6.10
```

Certificate is issued by a self-signed CA root, and is otherwise valid enough for chrome/firefox to use https and report secure when we only trust the CA.

**Comment by michaelklishin** [comment]
What does `rabbitmqctl environment` output?
Can you reproduce with [tls-gen's basic profile](https://github.com/michaelklishin/tls-gen/)?

The way `SSLContext#check_hostname` [is set](https://github.com/rabbitmq/rabbitmq-management/blob/stable/bin/rabbitmqadmin#L487) is quite straightforward. My best guess is that it is effectively ignored with `SSLContext#verify_mode` set to `ssl.CERT_REQUIRED`.

**Comment by warmfusion** [comment]
I've redacted the fqdn a little - but heres the raw output

<details>
<summary>rabbitmqctl environment</summary>
[{amqp_client,[{prefer_ipv6,false},{ssl_options,[]}]},
 {asn1,[]},
 {compiler,[]},
 {cowboy,[]},
 {cowlib,[]},
 {crypto,[]},
 {inets,[]},
 {kernel,
     [{error_logger,tty},
      {inet_default_connect_options,[{nodelay,true}]},
      {inet_dist_listen_max,65535},
      {inet_dist_listen_min,65535}]},
 {mnesia,[{dir,"/var/lib/rabbitmq/mnesia/rabbit@rmq01"}]},
 {os_mon,
     [{start_cpu_sup,false},
      {start_disksup,false},
      {start_memsup,false},
      {start_os_sup,false}]},
 {public_key,[]},
 {rabbit,
     [{auth_backends,[rabbit_auth_backend_internal]},
      {auth_mechanisms,['PLAIN','AMQPLAIN']},
      {background_gc_enabled,false},
      {background_gc_target_interval,60000},
      {backing_queue_module,rabbit_priority_queue},
      {channel_max,0},
      {channel_operation_timeout,15000},
      {cluster_keepalive_interval,10000},
      {cluster_nodes,
          {['rabbit@rmq01.brk.example.org.uk','rabbit@rmq02.brk.example.org.uk',
            'rabbit@rmq03.brk.example.org.uk'],
           disc}},
      {cluster_partition_handling,ignore},
      {collect_statistics,fine},
      {collect_statistics_interval,5000},
      {config_entry_decoder,
          [{cipher,aes_cbc256},
           {hash,sha512},
           {iterations,1000},
           {passphrase,undefined}]},
      {credit_flow_default_credit,{400,200}},
      {default_permissions,[<<".*">>,<<".*">>,<<".*">>]},
      {default_user,<<"admin">>},
      {default_user_tags,[administrator]},
      {default_vhost,<<"/">>},
      {delegate_count,16},
      {disk_free_limit,50000000},
      {disk_monitor_failure_retries,10},
      {disk_monitor_failure_retry_interval,120000},
      {enabled_plugins_file,"/etc/rabbitmq/enabled_plugins"},
      {error_logger,{file,"/var/log/rabbitmq/rabbit@rmq01.log"}},
      {fhc_read_buffering,false},
      {fhc_write_buffering,true},
      {frame_max,131072},
      {halt_on_upgrade_failure,true},
      {handshake_timeout,10000},
      {heartbeat,60},
      {hipe_compile,false},
      {hipe_modules,
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
           rabbit_command_assembler,rabbit_framing_amqp_0_9_1,rabbit_basic,
           rabbit_event,lists,queue,priority_queue,rabbit_router,rabbit_trace,
           rabbit_misc,rabbit_binary_parser,rabbit_exchange_type_direct,
           rabbit_guid,rabbit_net,rabbit_amqqueue_process,
           rabbit_variable_queue,rabbit_binary_generator,rabbit_writer,
           delegate,gb_sets,lqueue,sets,orddict,rabbit_amqqueue,
           rabbit_limiter,gb_trees,rabbit_queue_index,
           rabbit_exchange_decorator,gen,dict,ordsets,file_handle_cache,
           rabbit_msg_store,array,rabbit_msg_store_ets_index,rabbit_msg_file,
           rabbit_exchange_type_fanout,rabbit_exchange_type_topic,mnesia,
           mnesia_lib,rpc,mnesia_tm,qlc,sofs,proplists,credit_flow,pmon,
           ssl_connection,tls_connection,ssl_record,tls_record,gen_fsm,ssl]},
      {lazy_queue_explicit_gc_run_operation_threshold,1000},
      {log_levels,[{connection,info}]},
      {loopback_users,[<<"guest">>]},
      {memory_monitor_interval,2500},
      {mirroring_flow_control,true},
      {mirroring_sync_batch_size,4096},
      {mnesia_table_loading_retry_limit,10},
      {mnesia_table_loading_retry_timeout,30000},
      {msg_store_credit_disc_bound,{4000,800}},
      {msg_store_file_size_limit,16777216},
      {msg_store_index_module,rabbit_msg_store_ets_index},
      {msg_store_io_batch_size,4096},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {password_hashing_module,rabbit_password_hashing_sha256},
      {plugins_dir,
          "/usr/lib/rabbitmq/plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.10/plugins"},
      {plugins_expand_dir,
          "/var/lib/rabbitmq/mnesia/rabbit@rmq01-plugins-expand"},
      {queue_explicit_gc_run_operation_threshold,1000},
      {queue_index_embed_msgs_below,4096},
      {queue_index_max_journal_entries,32768},
      {reverse_dns_lookups,false},
      {sasl_error_logger,{file,"/var/log/rabbitmq/rabbit@rmq01-sasl.log"}},
      {server_properties,[]},
      {ssl_allow_poodle_attack,false},
      {ssl_apps,[asn1,crypto,public_key,ssl]},
      {ssl_cert_login_from,distinguished_name},
      {ssl_handshake_timeout,5000},
      {ssl_listeners,[5671]},
      {ssl_options,
          [{cacertfile,"/etc/rabbitmq/ssl/OurCA.crt.pem"},
           {certfile,"/etc/rabbitmq/ssl/rmq.brk.example.org.uk.crt.pem"},
           {keyfile,"/etc/rabbitmq/ssl/rmq.brk.example.org.uk.key.pem"},
           {verify,verify_peer},
           {fail_if_no_peer_cert,true}]},
      {tcp_listen_options,
          [{backlog,128},
           {nodelay,true},
           {linger,{true,0}},
           {exit_on_close,false}]},
      {tcp_listeners,[{"auto",5672}]},
      {trace_vhosts,[]},
      {vm_memory_high_watermark,0.4},
      {vm_memory_high_watermark_paging_ratio,0.5}]},
 {rabbit_common,[]},
 {rabbitmq_federation,[{pgroup_name_cluster_id,false}]},
 {rabbitmq_federation_management,[]},
 {rabbitmq_management,
     [{cors_allow_origins,[]},
      {cors_max_age,1800},
      {http_log_dir,none},
      {listener,
          [{port,15672},
           {ssl,true},
           {ssl_opts,
               [{cacertfile,"/etc/rabbitmq/ssl/OurCA.crt.pem"},
                {certfile,"/etc/rabbitmq/ssl/rmq.brk.example.org.uk.crt.pem"},
                {keyfile,
                    "/etc/rabbitmq/ssl/rmq.brk.example.org.uk.key.pem"}]}]},
      {load_definitions,none},
      {management_db_cache_multiplier,5},
      {process_stats_gc_timeout,300000},
      {stats_event_max_backlog,250}]},
 {rabbitmq_management_agent,
     [{rates_mode,basic},
      {sample_retention_policies,
          [{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
           {basic,[{605,5},{3600,60}]},
           {detailed,[{605,5}]}]}]},
 {rabbitmq_stomp,
     [{default_user,[{login,<<"guest">>},{passcode,<<"guest">>}]},
      {default_vhost,<<"/">>},
      {hide_server_info,false},
      {implicit_connect,false},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {ssl_cert_login,false},
      {ssl_listeners,[61614]},
      {tcp_listen_options,[{backlog,128},{nodelay,true}]},
      {tcp_listeners,[61613]},
      {trailing_lf,true}]},
 {rabbitmq_web_dispatch,[]},
 {ranch,[]},
 {sasl,[{errlog_type,error},{sasl_error_logger,false}]},
 {ssl,[{protocol_version,['tlsv1.2','tlsv1.1',tlsv1]}]},
 {stdlib,[]},
 {syntax_tools,[]},
 {xmerl,[]}]
</details>

**Comment by michaelklishin** [comment]
Which suggests HTTP API isn't configured to require clients to present a certificate.

**Comment by warmfusion** [comment]
Indeed; but the http api is operating on SSL behind a self-signed cert, and if i dont submit `-s` to enable ssl the output changes to a even less insightful 'bad status line'
<details>
<summary>Without -s</summary>
```

rabbitmqadmin --ssl-disable-hostname-verification --username=admin --password=admin list queues
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 1012, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 413, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 593, in invoke_list
    format_list(self.get(uri), cols, obj_info, self.options)
  File "/usr/local/bin/rabbitmqadmin", line 440, in get
    return self.http("GET", "%s/api%s" % (self.options.path_prefix, path), "")
  File "/usr/local/bin/rabbitmqadmin", line 494, in http
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```</details>

**Comment by michaelklishin** [comment]
@lukebakken @warmfusion should we only set `SSLContext#verify_mode` only if the user hasn't opted out of peer verification?

**Comment by lukebakken** [comment]
Yes, that sounds reasonable. I haven't had time to reproduce and investigate this just yet.

**Comment by lukebakken** [comment]
As @michaelklishin notes, the `--ssl-disable-hostname-verification` option only disables host name validation for the cert provided by the server (the `CN=` value), it does *not* disable the requirement that the server cert be signed by a known CA. Using [`tls-gen`](https://github.com/michaelklishin/tls-gen/) basic profile, I can successfully use SSL when the CA cert is provided:

```
$ ./bin/rabbitmqadmin --ssl --ssl-disable-hostname-verification \
    --ssl-ca-cert-file=$TLS_GEN_PATH/tls-gen/basic/testca/cacert.pem \
    --host=localhost --port=15672 list users
+-------+--------------------------------+--------------------------------------------------+---------------+
| name  |       hashing_algorithm        |                  password_hash                   |     tags      |
+-------+--------------------------------+--------------------------------------------------+---------------+
| guest | rabbit_password_hashing_sha256 | 6Xh3oRiR51y7UWpUD7WQjVy6rIC7U78XyfgyagP3Nmx8u81P | administrator |
+-------+--------------------------------+--------------------------------------------------+---------------+
```

I suggest adding a `--ssl-disable-verification` argument that not only disables hostname verification, but sets `verify_mode` to [`CERT_NONE`](https://docs.python.org/2/library/ssl.html#ssl.CERT_NONE)

**Comment by michaelklishin** [comment]
@lukebakken and perhaps deprecate `--ssl-disable-hostname-verification`. 👍 from me.

**Comment by lukebakken** [comment]
To more closely match [`curl`](https://curl.haxx.se/docs/manpage.html#-k), I will add `--ssl-insecure` and `-k` as the short form.
