### ISSUE TITLE
Report vhost state for remote nodes.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#460]
Vhost state is currently reported only for the management request node, while other nodes in the cluster can have a different state for the vhost.

Follow up to #446

**Comment by lukebakken** [comment]
I executed the following several times to kill the `/` vhost:

```
f(), {ok, Pid} = rabbit_vhost_sup_sup:get_vhost_sup(<<"/">>),
    [MPid] = [Pid || {Name, Pid, _, _} <- supervisor:which_children(Pid),
    Name == msg_store_persistent], erlang:exit(MPid, force_vhost_failure).
```
