### ISSUE TITLE
Queue details page truncates node name

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#473]
You can see in this screenshot that in the "Details" section, "Node" removes the `rabbit@` prefix from the queue master node name. [It is hard-coded in this function](https://github.com/rabbitmq/rabbitmq-management/blob/stable/priv/www/js/formatters.js#L497), but there's no good explanation of *why* in the history.

![queue-page-hides-node-name](https://user-images.githubusercontent.com/514926/30125843-aa21a40c-92ee-11e7-9fb6-63b095e13893.png)

**Comment by lukebakken** [comment]
After looking at the UI more, this seems to be a UI "optimization" because most nodes name uses a `rabbit@` prefix, so why show it in the UI? I'm running a multi-node cluster which is why I see `rabbit2` and `rabbit3`. It does seem strange to only truncate a prefix of `rabbit@` while showing others.

**Comment by michaelklishin** [comment]
@lukebakken yes, it is weird. I think we can just display the entire name. WDYT?

**Comment by lukebakken** [comment]
It will take up more screen real estate and nobody but me has noticed over the past few years it seems. Users with long hostnames would probably notice if we show the `rabbit@` prefix, and I suspect most users are used to how things are, so it's probably best to leave it the way it is.

**Comment by lukebakken** [comment]
Reopened because I just noticed that all of our dropdowns preserve `rabbit@`. For instance, on the "Queues" page the "Node:" dropdown for "Add a new queue"
