### ISSUE TITLE
The graph configuration menu is not always visible

### ISSUE THREAD

**Issue by oneiros-de** [rabbitmq/rabbitmq-management#479]
When one selects a long page (e.g. the node stats with a lot of graphs open) that's much longer as one screen and scrolls to the bottom and then tries to configure a graph there, its configuration menu will not be visible on screen as it's always on the top of the page - which might not be visible.

**Comment by michaelklishin** [comment]
@oneiros-de I don't think we will introduce per-chart settings and floating controls is something for a complete redesign. So please scroll to the top for now.
