### ISSUE TITLE
Custom path prefix for RabbitMQ management UI

### ISSUE THREAD

**Issue by Starefossen** [rabbitmq/rabbitmq-management#481]
I am running the official Docker Image for RabbitMQ v3.6.12 with management UI enabled (rabbitmq:3.6.12-management-alpine).

However, I have not been successful in changing the path prefix for the management UI using the `--path-prefix` configuration option mentioned in the documentation for the management UI.

Running the Docker Image:

```
docker run -p 15672:15672 rabbitmq:3.6.12-management-alpine rabbitmq-server --path-prefix=/test
```

Accessing management UI over `/test`:

```
$ curl <DOCKER_IP>:15672/test
> {"error":"Object Not Found","reason":"Not Found"}
```

**Comment by michaelklishin** [comment]
@Starefossen this repository is the management plugin itself. The Docker image's one is at http://github.com/docker-library/rabbitmq/.

**Comment by Starefossen** [comment]
I'm sorry if I didn't formulate my question correctly. This isn't an issue with the Docker Image, that just happened to be the way I run my RabbitMQ management UI. The problem is with the management UI not adhering to the `--path-prefix`. Do I have the correct option for setting the path prefix for the UI?

**Comment by michaelklishin** [comment]
@Starefossen there is [no path prefix setting in the management UI](http://www.rabbitmq.com/management.html). A quick Docker image source search suggests the `--path-prefix` setting seems to cover a [local file system path prefix](https://github.com/docker-library/rabbitmq/search?utf8=✓&q=prefix&type=), not an HTTP API URI path.

Our team [does not use GitHub issues for questions](https://github.com/rabbitmq/rabbitmq-management/blob/master/CONTRIBUTING.md), so please post questions to rabbitmq-users in the future.

**Comment by michaelklishin** [comment]
Use Apache, Nginx or similar in front of RabbitMQ to perform any path rewrites you need.

**Comment by zhoubonet** [comment]
must Apache，Nginx or  similar  in front of RabbitMQ 
RabbitMQ whether support or not

**Comment by zhoubonet** [comment]
must use Apache，Nginx or similar in front of RabbitMQ
RabbitMQ whether support or not

**Comment by lukebakken** [comment]
@Starefossen - could you please explain why this is necessary or desired when using the Docker image?

**Comment by Starefossen** [comment]
Sorry for the delayed response on this one. Our problem is that we only have a limited amount of domain names where we can expose services on and we would like to expose on other than root `"/"` such as `"/rabbitmq-management"`. 

We did try to rewrite this from our Ingress Controller (reverse proxy) in Kubernetes but it looked RabbitMQ Management was very confused when it was accessed on another path than `"/"` from the outside – some parts of the user interface did not load correctly when rewriting requests.

**Comment by michaelklishin** [comment]
@Starefossen it means that not all requests were rewritten (or rewritten correctly).

**Comment by Starefossen** [comment]
Yes, and it's the WebSocket requests – those doesn't seam to be that easy to rewrite.

**Comment by michaelklishin** [comment]
This plugin does not use WebSockets or provide any WebSockets endpoints.

**Comment by michaelklishin** [comment]
Customising base path should be relatively straightforward with Cowboy but beyond that, we are not interested in introducing generic HTTP server features into this plugin. We will never be as good at path rewrites as Nginx or httpd.

[Web STOMP](http://www.rabbitmq.com/web-stomp.html) and [Web MQTT](http://www.rabbitmq.com/web-mqtt.html) plugins use a hardcoded prefix of `/ws`. If there's interest in making that customisable, please file specific issues for those plugins.

**Comment by Starefossen** [comment]
Thanks for the answer @michaelklishin. Thanks for all the awesome work you are doing for the RabbitMQ community!

**Comment by michaelklishin** [comment]
I'll reopen as I have reasons to believe @lukebakken may be interested in investigating path prefix support in this plugin.

**Comment by pujaramihir** [comment]
when this path prefix will be released?

**Comment by michaelklishin** [comment]
@pujaramihir see this issue's milestone.

**Comment by pujaramihir** [comment]
I took the latest code build it but it does not work with UI. It work i cant open that url but it does not show any thing just white screen. I check console from browser and i found the issue that in UI(Frontend) side prefix is not set.

**Comment by michaelklishin** [comment]
@pujaramihir management UI does support this (via a permanent redirect). I QA'ed this feature and it works (too well, in fact, Chrome requires clearing browser cache to remove the redirection).

You have provided no details that would let us reproduce (how the plugin was built, what's the configuration, what is in server logs, what is in the JS console, what browser is used, etc).
Our team does not use GitHub for investigations, discussions and root cause analysis. Please use 3.6.13 RC2 for your tests and take this to rabbitmq-users.

**Comment by michaelklishin** [comment]
I have taken the following steps to verify this against a 3.6.13-rc.2 node:

 * Download a generic UNIX package
 * Untar
 * Copy my [standard development config](https://gist.github.com/michaelklishin/92c02ceb16db56289e4f7fdc075e17f9) with a `rabbitmq_management.path_prefix` added
 * Start the node
 * Make sure the config is what I expect it to be (`rabbitmqctl environment`)
 * Navigate to `http://localhost:15672`
 * Observe redirection to `http://localhost:15672/management-481/test/prefix/`
 * Observe that I can sign in and management UI seems functional as usual
 * Stop the node
 * Remove the prefix
 * Clear Chrome cache for the last hour
 * Restart the node
 * Navigate to `http://localhost:15672`
 * Observe no redirection
 * Observe that I can still sign in

@pujaramihir HTH.
