### ISSUE TITLE
Not enough access control when publishing messages in Management UI

### ISSUE THREAD

**Issue by 4integration** [rabbitmq/rabbitmq-management#483]
Using RabbitMQ 3.6.10 and Erlang/OTP 19.3.
Using Chrome for testing Management UI

I know that exchanges is used for publishing. When using the Management UI and browsing to the queue there is a publishing function - which uses exchange amq.default.
In order to make it possible to use that Management UI function I need to grant access to amq.default like:

```
User Name   Role            Configure RegExp    Write RegExp                   Read RegExp
app1-mgmt   Management      (empty)             ^APP1\.\w+|^amq\.default$      ^APP1\.\w+|^amq\.default$
app2-mgmt   Management      (empty)             ^APP2\.\w+|^amq\.default$      ^APP2\.\w+|^amq\.default$
```

That make the publishing function to work in Management UI but also introduces another issue.
Users (app1-mgmt and app2-mgmt in this example) can publish to ANY queue since there is no access control if the user have access on the destination queue or not.

My view is that management UI should have a access control that prevent e.g. app1-mgmt user to publish to other queues than APP1.* (over amq.default exchange).

**Comment by lukebakken** [comment]
Hello and thank you for using RabbitMQ.

In your scenario, you would use a dedicated exchange for that user to limit write permission to a set of queues that are bound to the exchange. See "How Permissions Work" in [this document](https://www.rabbitmq.com/access-control.html).

I will close this issue now but @michaelklishin may have additional comments.

**Comment by michaelklishin** [comment]
@4integration publishers access is limited by limiting access to exchanges, not queues.

**Comment by michaelklishin** [comment]
3.7.0 introduces [topic-based authorization](http://next.rabbitmq.com/access-control.html) on top of that but that's primarily useful to STOMP and MQTT users.
