### ISSUE TITLE
With .NET client (5.0.1) the management UI shows 0.0.0.0 version 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-management#490]
Using the .NET client 5.0.1 the management UI shows the version 0.0.0.0.

Tab "Connection", column "Client", as:
![screen shot 2017-10-03 at 10 17 17](https://user-images.githubusercontent.com/386987/31115939-81ac62c8-a824-11e7-9384-d5285f0170e2.png)

RabbitMQ version `3.6.11`

**Comment by michaelklishin** [comment]
I somewhat doubt it is an issue in this plugin. More likely than not the build system did not update the version field in the client at build time.
