### ISSUE TITLE
Sorting of queues by node name seems broken in Management plugin

### ISSUE THREAD

**Issue by tommymonk** [rabbitmq/rabbitmq-management#491]
RabbitMQ version: 3.7 rc1
Erlang version: 20.1

 I've noticed that the queues don't appear to be sorting by node name correctly in the management ui.

Our cluster in this example has 4x nodes with most queues on the first node and several on the fourth.
The sort order seems incorrect both asc and desc

![sort_direction](https://user-images.githubusercontent.com/574131/31380331-fdfde714-ada8-11e7-8ecf-5534c310fbae.png)

**Comment by oneiros-de** [comment]
The same problem also happens in 3.6.14; see this screenshot. Now find all the queues on endive2...

![screenshot-endive1 15672-2017-11-14-09-49-23](https://user-images.githubusercontent.com/906250/32770820-272fc27c-c921-11e7-8d6c-ea74dfc847ea.png)
