### ISSUE TITLE
Queue rows do not display optional arguments set via a policy the same way as via x-args

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#492]
Mailing list thread is [here](https://groups.google.com/d/msg/rabbitmq-users/u2UIAiXsofo/sqx5V7oXBgAJ)

To reproduce:

* Create a policy that applies to queues with `queue-mode: lazy` and `max-length: 10000`
* Create a queue to which this policy will apply
* Visit the queue in the Queues overview page as well as the individual Queue page. You will not see any visual indication that this queue has features even though those features will be applied.
* Create a different queue that does not match any policy, but create it with queue arguments `x-queue-mode: lazy` and `x-max-length: 10000`. When you view this queue in the UI you *will* see these features displayed on the Queues overview page and individual Queue page.

**Comment by 4integration** [comment]
Hi Luke,
Thanks for this issue.
To be sure - please also handle other features than queue-mode and max-length - like all queue features:

```
- message-ttl
- expires 
- max-length-bytes
- dead-letter-exchange
- dead-letter-routing-key
- ...
```

**Comment by michaelklishin** [comment]
Let's keep one issue about one thing. Thanks.

**Comment by michaelklishin** [comment]
When a policy is applied to a queue, the name of that policy will be displayed as a separate column with a hover-on of attributes IIRC. So this may be by design. Perhaps it would be an improvement to display the green boxes with features in either case.

**Comment by michaelklishin** [comment]
@lukebakken is this still relevant?

**Comment by lukebakken** [comment]
I will check on Monday 👍

**Comment by lukebakken** [comment]
Testing with `master`, you can see the name of the policy applied to a queue. Clicking the policy leads you to the definition. I consider this to be sufficient:

<img width="843" alt="rabbitmq-management-492-queue-policy" src="https://user-images.githubusercontent.com/514926/69462983-4fb35c00-0d2f-11ea-8865-6268aaa4ef7c.png">
