### ISSUE TITLE
Make policy clickable

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#493]
If you create a policy that matches queues and / or exchanges, the policy is listed in various places in the UI but is not clickable to navigate to that policy. Instead, you have to manually go to the Admin part of the UI to see the policy.

Clicking the policy should navigate you to the correct page to display it (i.e. `http://localhost:15672/#/policies/%2F/my-awesome-policy`)

What do you think @gerhard ?

**Comment by gerhard** [comment]
That makes a lot of sense, I'm all for it. Will squeeze it in the 3.6.13 UI refactorings.
