### ISSUE TITLE
POST requests that return location header should use a relative URL

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#503]
Currently, when you `POST` to a resource that returns a `location:` header, it is returned relative to the request URI (note the number of `../` entries in the path):

```
$ curl -4vvv -u guest:guest -XPOST localhost:15672/gh-495/api/bindings/%2F/e/myexchange/q/myqueue
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15672 (#0)
* Server auth using Basic with user 'guest'
> POST /gh-495/api/bindings/%2F/e/myexchange/q/myqueue HTTP/1.1
> Host: localhost:15672
> Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
> User-Agent: curl/7.56.0
> Accept: */*
> 
< HTTP/1.1 201 Created
< server: Cowboy
< date: Thu, 26 Oct 2017 16:52:57 GMT
< content-length: 0
< content-type: application/json
< vary: accept, accept-encoding, origin
< location: ../../../../../../../api/bindings/%2F/e/myexchange/q/myqueue/~
< 
* Connection #0 to host localhost left intact
```

Instead, returning the following should be sufficient - since the URI starts with `/` the client will know it is relative to the host / scheme of the previous request:

```
/api/bindings/%2F/e/myexchange/q/myqueue
```

[Links can be found here](https://en.wikipedia.org/wiki/HTTP_location#Relative_URL_example).

Also, it appears the trailing `~` character is an artifact from [this format statement](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_bindings.erl#L99-L102) and is a bug. The returned `location:` URI works, but the tilde is returned:

```
$ curl -4vvv -u guest:guest 'localhost:15672/gh-495/api/bindings/%2F/e/myexchange/q/myqueue/../../../../../../../api/bindings/%2F/e/myexchange/q/myqueue/~'
* Rebuilt URL to: localhost:15672/gh-495/api/bindings/%2F/e/myexchange/q/myqueue/~
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15672 (#0)
* Server auth using Basic with user 'guest'
> GET /gh-495/api/bindings/%2F/e/myexchange/q/myqueue/~ HTTP/1.1
> Host: localhost:15672
> Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
> User-Agent: curl/7.56.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< server: Cowboy
< date: Thu, 26 Oct 2017 17:04:18 GMT
< content-length: 139
< content-type: application/json
< vary: accept, accept-encoding, origin
< Cache-Control: no-cache
< 
* Connection #0 to host localhost left intact
{"source":"myexchange","vhost":"/","destination":"myqueue","destination_type":"queue","routing_key":"","arguments":{},"properties_key":"~"}
```

**Comment by essen** [comment]
I was curious about this so I gave it a quick look.

In the current version the Location is relative but has a better form as it will return simply `myqueue/~` in this case which is correct. When you say relative in this ticket you actually mean the absolute-path form but it seems like a decision was made some time ago to go this road instead (see `rabbit_web_dispatch_util:relativise/2`).

The `~` also seems to be correct as it comes from `rabbit_mgmt_format:pack_binding_props/2` and not from a format error. But I'm not the most familiar in that territory.

**Comment by lukebakken** [comment]
> When you say relative in this ticket you actually mean the absolute-path

I know it doesn't make sense, but the [docs I have read](https://en.wikipedia.org/wiki/HTTP_location#Relative_URL_example) with regard to relative vs absolute path call a scheme-less path beginning with `/` "relative" ¯\_(ツ)_/¯

I'll check out the current behavior. I haven't tried this since the 2.0 upgrade. Thanks for checking this out.

**Comment by essen** [comment]
It is relative as far as the URI is concerned but the path itself is absolute. It's this form: https://tools.ietf.org/html/rfc7230#section-5.3.1

Not to be confused with a relative path which is what the current implementation does (better than the previous relative path with a lot of dot segments).
