### ISSUE TITLE
Multifield inputs not working after jQuery update

### ISSUE THREAD

**Issue by Yobilat** [rabbitmq/rabbitmq-management#511]
After update from 3.6.12 to 3.6.14 I've noticed that multifields inputs stopped working e.g. sending message with web UI directly to exchange or queue with headers or props - it only allows single param. No errors on console. It seems that issue is with javascript code migration due to jQuery update #502 that went live in 3.6.13 namely changes [1](https://github.com/rabbitmq/rabbitmq-management/pull/502/files#diff-96c49537dc1427a678b0f28251d2577cL572), [2](https://github.com/rabbitmq/rabbitmq-management/pull/502/files#diff-96c49537dc1427a678b0f28251d2577cL575).

According to [documentation](http://api.jquery.com/live/) it should look like this::
```
    $(document).on('keyup','.multifield input', function() {
            update_multifields();
        });

    $(document).on('change','.multifield select', function() {
            update_multifields();
        }); 
```
It seems to work when I changed live js file in Chrome inspector but i don't know how it plays with rest of code, if it is 100% correct implementation or if there are more similar issues due to jQuery update.

Some details:
* RabbitMQ version - 3.6.14(official docker management image)
* Erlang version - 19.2.1(official docker management image)
* Host: KDE Neon LTS (Ubuntu 16.04)
* Browser: Chrome Version 62.0.3202.89 (Official Build) (64-bit), Firefox 56

**Comment by michaelklishin** [comment]
Thanks for the details, we will take a look some time next week.
