### ISSUE TITLE
SSL private key password

### ISSUE THREAD

**Issue by robg66** [rabbitmq/rabbitmq-management#512]
Hello,

We are trying to enable ssl on our management portal. 
We use the following configuration:

```
 {rabbitmq_management,[{listener, [
              {port,     15671},
              {ip,       "0.0.0.0"},
              {ssl,      true},
              {ssl_opts, [{cacertfile, "/etc/certs/cacert.pem"},
                          {certfile,   "/etc/certs/cert.pem"},
                          {keyfile,    "/etc/certs/key.pem"},
                          {password,"......"}
                          ]}
                      ]}]
    }
```
Rabbitmq is starting and gives no errors.  But we cant reach the management portal. 
We think the reason why it is not working is because our private key has a password on it. 
For security reasons we don't want to remove this password. 
Is something wrong with our configuration or does the rabbitmq management plugin not support password protected private keys?

**Comment by lukebakken** [comment]
Hi @robg66 

Erlang certainly supports password protected keys, so there must be some other issue. The RabbitMQ team doesn't do Q-and-A via GitHub issues, so could you please post this to [our mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) and we'll take it from there?

Thanks.
