### ISSUE TITLE
Inconsistent JSON returned by /api/queues for `recoverable_slaves`, `synchronised_slave_nodes` and `slave_nodes`

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#513]
https://groups.google.com/d/msg/rabbitmq-users/XFEt25Ixqx0/nQq8pmRDAQAJ

A user reports that `/api/queues` can sometimes return a string or array:

```
# Array example
"recoverable_slaves":["rabbit@********************"]

# String example
"recoverable_slaves":""
```

If a consumer is using a strict JSON deserializer this could cause failure.

**Comment by YulerB** [comment]
Haven't tested the other two properties, but same could occur for synchronised_slave_nodes and slave_nodes.

**Comment by kjnilsson** [comment]
Could potentially be tricky to fix as in erlang the empty string is an empty list. :)

**Comment by michaelklishin** [comment]
We already addressed something similar in https://github.com/rabbitmq/rabbitmq-management/issues/75 (https://github.com/rabbitmq/rabbitmq-common/pull/72), though.

**Comment by stefanhorning** [comment]
Would this also explain why the management webinterface of RabbitMQ 3.7.3 is currenly also broken for the queues page?

It's not showing the queues and an error message instead:

![rabbitmq-mgmt-plugin-queue-page-error](https://user-images.githubusercontent.com/1150445/35860213-84f0827a-0b43-11e8-8c1c-0c9498596199.png)

**Comment by michaelklishin** [comment]
@stefanhorning it is not currently broken according to user feedback and our own dogfooding. The error is a `ReferenceError` in JavaScript code. Clear your browser's cache and please post questions to rabbitmq-users in the future.

**Comment by stefanhorning** [comment]
Sorry, didn't know that. Clearing cache worked, thank you!

**Comment by michaelklishin** [comment]
We are going to add a note about that to the [upgrade docs](http://www.rabbitmq.com/upgrade.html).

**Comment by lukebakken** [comment]
I am going to close this as I can't reproduce it. I think it may have arisen due to a stats DB corruption. I consistently see correct output like this in my 2-node test environment:

```
  "recoverable_slaves": null,
  "synchronised_slave_nodes": [
    "rabbit2@shostakovich"
  ],
  "slave_nodes": [
    "rabbit2@shostakovich"
  ],
```
