### ISSUE TITLE
Select options are not fully visible; width is restricted

### ISSUE THREAD

**Issue by asgs** [rabbitmq/rabbitmq-management#519]
I'm specifically referring to the page where we choose an Exchange and view its details. Screenshots attached show the Select dropdown corresponding to the Datatype of the Arguments text field under "Add Binding from this exchange".

The reason why the values are partially visible is, the width are set to 70px, 200px depending on where the CSS selector is. Setting them to auto fixes the issue on my FF Browser v58.
![rabbitmq-admin-ui-smaller-select-width](https://user-images.githubusercontent.com/833190/34058811-6fbd0050-e202-11e7-9e84-6ff5705f8250.png)
![rabbitmq-admin-ui-normal-select-width](https://user-images.githubusercontent.com/833190/34058823-794e2a86-e202-11e7-8a01-1d1f75d9f507.png)

**Comment by lukebakken** [comment]
It would be great if you open a PR with your recommended changes. Thanks!
