### ISSUE TITLE
HTTP Api in Version 3.6.14 and up return Content-Type header twice

### ISSUE THREAD

**Issue by jimmypoulin** [rabbitmq/rabbitmq-management#527]
We are using the HTTP Api to post messages and have noticed that since we upgraded to 3.6.14 from 3.6.5 the "Content-Type" header is returned twice when we publish a message to an exchange.
The client from which we are using the HTTP Api is unable to deal with that.
We confirmed that the issue wasn't present in 3.6.5.

See attached screenshot.
![2017-12-19 16_40_17-postman](https://user-images.githubusercontent.com/18073033/34210066-88c472dc-e562-11e7-847c-a10d5243cedd.png)

I posted the following in [rabbitmq-users google group](https://groups.google.com/forum/#!topic/rabbitmq-users/wQEgcDagk3Y) and Luke Bakken reproduced the issue and instructed me to post it here.

* RabbitMQ version: 3.6.14 and 3.7.0
* Erlang version: 20.1

**Comment by lukebakken** [comment]
Fixed by #524 and #523

**Comment by jimmypoulin** [comment]
Awesome, thanks for the quick fix and integrating it in the next version.
