### ISSUE TITLE
Passwordless user minor UI improvement

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#537]
When you update a user in the management UI that does not have a password, the page should have "No password" selected in the "Update this user" dropdown, with the other option of "Password:" as the second item in the dropdown.

Currently, it is a bit misleading that the UI expects you to provide a password when updating a password-less user.

Found when reviewing #533

**Comment by lukebakken** [comment]
Found when reviewing #533

**Comment by michaelklishin** [comment]
Re-opening until #538 and #539 are merged.
