### ISSUE TITLE
CRASH REPORT Process <0.2132.0> with 0 neighbours crashed with reason: no case clause matching

### ISSUE THREAD

**Issue by plReynaerde** [rabbitmq/rabbitmq-management#546]
I do wonder if i have a mis configuration or that er is indeed somthing wrong...

2018-01-27 18:47:17.495 [error] <0.2132.0> CRASH REPORT Process <0.2132.0> with 0 neighbours crashed with reason: no case clause matching {[{port,<<"15672">>},{port,<<"15672">>}],[{ssl_opts,[]},{node,eddy@bigwig},{description,<<"RabbitMQ Management">>},{path,<<"/">>},{ip,<<"172.25.37.58">>},{ip,<<"172.25.5.58">>}]} in rabbit_mgmt_util:pget_bin/3 line 606
2018-01-27 18:47:17.498 [error] <0.2131.0> Ranch listener rabbit_web_dispatch_sup_15672, connection process <0.2131.0>, stream 1 had its request process <0.2132.0> exit with reason {case_clause,{[{port,<<"15672">>},{port,<<"15672">>}],[{ssl_opts,[]},{node,eddy@bigwig},{description,<<"RabbitMQ Management">>},{path,<<"/">>},{ip,<<"172.25.37.58">>},{ip,<<"172.25.5.58">>}]}} and stacktrace [{rabbit_mgmt_util,pget_bin,3,[{file,"src/rabbit_mgmt_util.erl"},{line,606}]},{rabbit_mgmt_util,sort_key,2,[{file,"src/rabbit_mgmt_util.erl"},{line,590}]},{rabbit_mgmt_util,sort_key,2,[{file,"src/rabbit_mgmt_util.erl"},{line,590}]},{rabbit_mgmt_util,'-sort_list/4-lc$^0/1-1-',2,[{file,"src/rabbit_mgmt_util.erl"},{line,463}]},{rabbit_mgmt_util,sort_list,4,[{file,"src/rabbit_mgmt_util.erl"},{line,463}]},{rabbit_mgmt_util,sort_list_and_paginate,5,[{file,"src/rabbit_mgmt_util.erl"},{line,467}]},{rabbit_mgmt_wm_overview,to_json,2,[{file,"src/rabbit_mgmt_wm_overview.erl"},{line,61}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,1128}]}]

Error occurred in a cluster of three Raspberry Pi 3's.
The nodes run Raspbian stretch.

The configuration, of node1:
 [
    {mnesia,			[{dump_log_write_threshold, 1000}]},
    {rabbit,			[{tcp_listeners, [{"192.168.51.57",5672},
                                                  {"172.25.5.57",5672},
                                                  {"172.25.37.57",5672}
                                                 ]},
                                 {cluster_nodes, {['eddy@hb_silver','eddy@hb_bigwig','eddy@hb_pipkin'], disc}}]
				},
    {rabbitmq_management,	[{listener, [{ip, "172.25.37.57"},{port, 15672},
                                             {ip, "172.25.5.57"},{port, 15672}
                                            ]}]},
    {rabbitmq_stomp,		[{tcp_listeners, [{"192.168.51.57",61613},
                                                  {"172.25.5.57",61613},
                                                  {"172.25.37.57",61613}
                                                 ]}]},
    {rabbitmq_mqtt,		[{default_user,     <<"eddy">>},
				 {default_pass,     <<"s3cr33t">>},
				 {allow_anonymous,  true},
				 {vhost,            <<"/tt">>},
%%				 {exchange,         <<"amqp.topic">>},
				 {exchange,         <<"mqtt">>},
				 {subscription_ttl, 1800000},
				 {prefetch,         10},
%%				 {ssl_listeners,    []},
%%				 %% Default MQTT with TLS port is 8883
%%				 %% {ssl_listeners, [8883]}
				 {tcp_listeners,    [{"192.168.51.57",1883},
                                                     {"172.25.5.57",1883},
                                                     {"172.25.37.57",1883}
                                                    ]},
				 {tcp_listen_options,   [binary,
				 			{packet,    raw},
				 			{reuseaddr, true},
				 			{backlog,   128},
				 			{nodelay,   true}]}]}
  ].
node 2 and 3 have the same configuration with exception sed -i 's/57/58/' or n2 en 59 for n3

All nodes run keepalived and haproxy

RabbitMQ 3.7.2 on Erlang 20.1.7
Linux silver 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on eddy@silver
 |/
[e*] rabbitmq_amqp1_0                  3.7.2
[  ] rabbitmq_auth_backend_cache       3.7.2
[  ] rabbitmq_auth_backend_http        3.7.2
[  ] rabbitmq_auth_backend_ldap        3.7.2
[  ] rabbitmq_auth_mechanism_ssl       3.7.2
[  ] rabbitmq_consistent_hash_exchange 3.7.2
[  ] rabbitmq_event_exchange           3.7.2
[E*] rabbitmq_federation               3.7.2
[E*] rabbitmq_federation_management    3.7.2
[  ] rabbitmq_jms_topic_exchange       3.7.2
[E*] rabbitmq_management               3.7.2
[E*] rabbitmq_management_agent         3.7.2
[E*] rabbitmq_mqtt                     3.7.2
[  ] rabbitmq_peer_discovery_aws       3.7.2
[  ] rabbitmq_peer_discovery_common    3.7.2
[  ] rabbitmq_peer_discovery_consul    3.7.2
[  ] rabbitmq_peer_discovery_etcd      3.7.2
[  ] rabbitmq_peer_discovery_k8s       3.7.2
[  ] rabbitmq_random_exchange          3.7.2
[  ] rabbitmq_recent_history_exchange  3.7.2
[  ] rabbitmq_sharding                 3.7.2
[E*] rabbitmq_shovel                   3.7.2
[E*] rabbitmq_shovel_management        3.7.2
[E*] rabbitmq_stomp                    3.7.2
[E*] rabbitmq_top                      3.7.2
[E*] rabbitmq_tracing                  3.7.2
[  ] rabbitmq_trust_store              3.7.2
[e*] rabbitmq_web_dispatch             3.7.2
[  ] rabbitmq_web_mqtt                 3.7.2
[  ] rabbitmq_web_mqtt_examples        3.7.2
[  ] rabbitmq_web_stomp                3.7.2
[  ] rabbitmq_web_stomp_examples       3.7.2

**Comment by plReynaerde** [comment]
Added the output of 'rabbitmq-collect-env'.

[rabbitmq-env-silver-20180127-192410.tar.gz](https://github.com/rabbitmq/rabbitmq-management/files/1670403/rabbitmq-env-silver-20180127-192410.tar.gz)

**Comment by lukebakken** [comment]
Hello!

I can't reproduce this issue using the attached file. I suspect you have a syntax error or other error in yours.

[rabbitmq.config.txt](https://github.com/rabbitmq/rabbitmq-management/files/1671536/rabbitmq.config.txt)

**Comment by michaelklishin** [comment]
The plugin tries to fetch a port from a nested data structure (part of the config) and it has a different structure. Consider moving to 3.7 and the new [config format](http://www.rabbitmq.com/configure.html).
