### ISSUE TITLE
Exchanges & queues views fail with SSL termination at proxy

### ISSUE THREAD

**Issue by hdave** [rabbitmq/rabbitmq-management#560]
Running RabbitMQ v3.7.4 with management UI.  RabbitMQ management UI is NOT configured for SSL termination within itself (that is done earlier --- I'll explain).

RabbitMQ management UI is behind an nginx reverse proxy with the following configuration:

```
location /rabbit/ {
    proxy_pass http://RABBIT_SERVICE_HOST:RABBIT_SERVICE_PORT_WEB/;
}

location /rabbit/api/queues/ {
    proxy_pass http://RABBIT_SERVICE_HOST:RABBIT_SERVICE_PORT_WEB/api/queues/%2F/;
}

location /rabbit/api/exchanges/ {
    proxy_pass http://RABBIT_SERVICE_HOST:RABBIT_SERVICE_PORT_WEB/api/exchanges/%2F/;
}
```

Everything works perfectly over http, but when I put an SSL terminating load balancer in front of nginx, the "Exchanges" and "Queues" tabs fail to function.  As near as I can tell, every other feature of the management UI works.  In this setup, everything prior to the load balancer is https.  Everything after the load balancer is http.  The X-Forwarded-For and X-Forwarded-Proto headers are correct.

Clicking on the "Exchanges" tab results in an https GET which in itself would work except that some other piece of (Javascript code?) then makes a subsequent call that does not respect the scheme.  The error in Chrome debug tools is as follows:

```
Mixed Content: The page at 'https://example.com/rabbit/#/exchanges' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/rabbit/api/exchanges/?page=1&page_size=100&name=&use_regex=false&pagination=true'. This request has been blocked; the content must be served over HTTPS.
```

Whatever code that creates that URL ('http://example.com/rabbit/api/exchanges/?page=1&page_size=100&name=&use_regex=false&pagination=true') needs to respect the value of the X-Forwarded-Proto header (if that code is server side).  If that code is running client side, then it needs to respect the current Scheme and not hardcode http.  It is interested that the tab itself does not have this problem, but rather the request to get the content for the tab.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The scheme is not hardcoded. All UI code requests use relative paths. We are aware of products  that have been using TLS/HTTPS termination in front of the management plugin for years without issues.

**Comment by michaelklishin** [comment]
[Here are the UI routes](https://github.com/rabbitmq/rabbitmq-management/blob/master/priv/www/js/dispatcher.js), see for yourself.

**Comment by lukebakken** [comment]
@hdave - you should use the following configuration. There is no need to have entries for `api/queues` and `api/exchanges`. If you hard-code them to the default vhost (`%2F`) as you have in your configuration it could cause the issue you are seeing in the management UI -

```
location /rabbit/ {
    proxy_pass http://RABBIT_SERVICE_HOST:RABBIT_SERVICE_PORT_WEB/;
}
```

**Comment by hdave** [comment]
@michaelklishin - I will post to rabbitmq-users.  Thanks.

@lukebakken - That was the original config I was using that suffers from the inability to load the queues and exchanges tabs at all, even over http.

**Comment by michaelklishin** [comment]
FTR, there's a follow-up [rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/NAXiijZSrWI).
