### ISSUE TITLE
Allow configuring multiple TCP listeners (non-TLS and TLS)

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#563]
Please see this `rabbitmq-users` topic: [link](https://groups.google.com/forum/#!msg/rabbitmq-users/beeZ4Edud0A/JOOyf8I7AQAJ;context-place=topic/rabbitmq-users/BkCb6yb8WeU)

Currently the management plugin only supports one listener at a time and it is not possible to support
HTTP and HTTPS clients at the same time, for instance.

[156776853] - related to [135606833]

**Comment by michaelklishin** [comment]
We can move to supporting multiple listeners and keep the current configuration compatible. Something like

``` ini
management.listeners.tcp.default = 192.168.1.99:5672
```

``` ini
management.listeners.tcp.1 = :::5672
management.listeners.tcp.2 = :::6672
```

``` ini
management.listeners.ssl = ::1:15671
```

**Comment by michaelklishin** [comment]
Another option is to do what [Web STOMP](http://www.rabbitmq.com/web-stomp.html) and [Web MQTT](http://www.rabbitmq.com/web-mqtt.html) plugins do: they allow for 1 TCP and 1 TLS listener only:

``` ini
management.tcp.port = 15672

management.ssl.port = 15671
management.ssl.cacertfile = /path/to/cacert.pem
management.ssl.certfile = /path/to/cert.pem
management.ssl.keyfile = /path/to/key.pem
```

**Comment by michaelklishin** [comment]
Most of our team prefer option number 2.

**Comment by michaelklishin** [comment]
Doc PR: https://github.com/rabbitmq/rabbitmq-website/pull/606.

**Comment by michaelklishin** [comment]
Doc PR: https://github.com/rabbitmq/rabbitmq-website/pull/606.

**Comment by michaelklishin** [comment]
Doc PR: https://github.com/rabbitmq/rabbitmq-website/pull/606.

**Comment by michaelklishin** [comment]
Doc PR: https://github.com/rabbitmq/rabbitmq-website/pull/606.

**Comment by michaelklishin** [comment]
Doc PR: https://github.com/rabbitmq/rabbitmq-website/pull/606.

**Comment by michaelklishin** [comment]
Doc PR: https://github.com/rabbitmq/rabbitmq-website/pull/606.

I will issue a follow-up PR to #618 that covers less frequently used Cowboy options.

**Comment by michaelklishin** [comment]
Follow-up PRs: https://github.com/rabbitmq/rabbitmq-website/pull/606, https://github.com/rabbitmq/rabbitmq-management/pull/619.
