### ISSUE TITLE
Operator policy validation fails for no good reason during definition import

### ISSUE THREAD

**Issue by kevinpayne** [rabbitmq/rabbitmq-management#565]
(Using **RabbitMQ 3.7.4**)
Ingestion of Operator Policies via REST API api/definitions endpoint is failing. 

## Steps to reproduce:
1. Create Operator Policy (via REST API or Web Admin UI)
2. GET api/definitions  (all definitions)
3. POST response from step 2 to api/definitions endpoint.
4. Observe 400 failure response.

Here is the operator policy that is failing for me. This is what is exported from the call to GET api/definitions:
```
    "parameters": [
        {
            "value": {
                "pattern": "^apd\\.mce\\.estarchive.*$",
                "definition": {
                    "max-length-bytes": 200000000
                },
                "priority": 0,
                "apply-to": "queues"
            },
            "vhost": "apd",
            "component": "operator_policy",
            "name": "apd-mce-estarchive"
        }]
```

POST api/definitions returns 400 with body:
```
{
    "error": "bad_request",
    "reason": "<<\"Validation failed\\n\\nparse error while reading policy: #{&lt;&lt;\\\"max-length-bytes\\\"&gt;&gt; =&gt; 200000000}\\n (apd/operator_policy/apd-mce-estarchive)\">>"
}
```

**Comment by michaelklishin** [comment]
I can reproduce with the following definition file: [management-565-example.json.zip](https://github.com/rabbitmq/rabbitmq-management/files/1942437/management-565-example.json.zip)

**Comment by michaelklishin** [comment]
@kevinpayne what's the value you specify for the pattern? In the snippet you have, `\\.` seems to be a double escaping artifact to me. Did you actually use it or was it `^apd\.mce\.estarchive.*$`?

**Comment by michaelklishin** [comment]
Nevermind, I tried both and the outcome is the same. Curiously an import test case added passes, so it must be an early stage validation issue.

**Comment by michaelklishin** [comment]
@kevinpayne a fix is pending QA. Thank you for providing a way to reproduce!
