### ISSUE TITLE
rabbitmqadmin get queue always fails

### ISSUE THREAD

**Issue by valleedelisle** [rabbitmq/rabbitmq-management#573]
```
# $RMQADM get queue=blabla
*** {u'key_missing': u'requeue'}
# $RMQADM get queue=blabla requeue=true

ERROR: Argument "requeue" not recognised

rabbitmqadmin --help for help
```
We can't specify the requeue argument, and when we don't specify, rabbitmqadmin refuses it.

This patch solves this problem, I'll submit a pull request in a few minutes
```
diff --git a/bin/rabbitmqadmin b/bin/rabbitmqadmin
index d6ca665f..283c65f4 100755
--- a/bin/rabbitmqadmin
+++ b/bin/rabbitmqadmin
@@ -161,6 +161,7 @@ EXTRA_VERBS = {
                 'uri':       '/exchanges/{vhost}/{exchange}/publish'},
     'get':     {'mandatory': ['queue'],
                 'optional':  {'count': '1', 'ackmode': 'ack_requeue_true',
+                              'requeue': 'true',
                               'payload_file': None, 'encoding': 'auto'},
                 'uri':       '/queues/{vhost}/{queue}/get'}
 }
```

**Comment by valleedelisle** [comment]
I guess we can close this one, I didn't know that the pull request would create an issue.
See https://github.com/rabbitmq/rabbitmq-management/issues/574

**Comment by worldmind** [comment]
As I understood rabbitmq 3.7 has breaking changes in API, if you are use rabbitmq 3.6.x you need to get 3.6.x rabbitmqadmin:
`https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.6.x/bin/rabbitmqadmin`

**Comment by michaelklishin** [comment]
RabbitMQ 3.6 has been out of support for 12 months. Consider [upgrading](https://www.rabbitmq.com/upgrade.html) instead.
