### ISSUE TITLE
rabbitmq-plugins.bat  enable rabbitmq_management   not work

### ISSUE THREAD

**Issue by xuweixuwei** [rabbitmq/rabbitmq-management#583]
--win10
--erlang 21
--rabbitmq 3.7.6
--rabbitmq-server.bat    work
--rabbitmq-plugins.bat  enable rabbitmq_management   not work
exception:

D:\rabbitmq-server-windows-3.7.6\rabbitmq_server-3.7.6\sbin>rabbitmq-plugins.bat
 enable rabbitmq_management
=SUPERVISOR REPORT==== 21-Jun-2018::15:45:01.494000 ===
    supervisor: {local,'Elixir.Logger.Supervisor'}
    errorContext: start_error
    reason: noproc
    offender: [{pid,undefined},
               {id,'Elixir.Logger.ErrorHandler'},
               {mfargs,
                   {'Elixir.Logger.Watcher',start_link,
                       [{error_logger,'Elixir.Logger.ErrorHandler',
                            {true,false,500}}]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
=CRASH REPORT==== 21-Jun-2018::15:45:01.509000 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.80.0>
    registered_name: []
    exception exit: {{shutdown,
                         {failed_to_start_child,'Elixir.Logger.ErrorHandler',
                             noproc}},
                     {'Elixir.Logger.App',start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.79.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.81.0>,normal}]
    links: [<0.79.0>,<0.42.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 193
  neighbours:

=CRASH REPORT==== 21-Jun-2018::15:45:01.494000 ===
  crasher:
    initial call: Elixir.Logger.Watcher:init/1
    pid: <0.87.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from 'Elixir.Logger.Watcher':init/1 (lib/logger/watcher.ex, line 2
3)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: ['Elixir.Logger.Supervisor',<0.81.0>]
    message_queue_len: 0
    messages: []
    links: [<0.82.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 254
  neighbours:

=INFO REPORT==== 21-Jun-2018::15:45:01.509000 ===
    application: logger
    exited: {{shutdown,
                 {failed_to_start_child,'Elixir.Logger.ErrorHandler',noproc}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
Could not start application logger: Logger.App.start(:normal, []) returned an er
ror: shutdown: failed to start child: Logger.ErrorHandler
    ** (EXIT) no process: the process is not alive or there's no process current
ly associated with the given name, possibly because its application isn't starte
d

**Comment by michaelklishin** [comment]
You are attempting to run RabbitMQ CLI tools on Erlang 21, which is [not supported](https://groups.google.com/d/msg/rabbitmq-users/KbOldePfgYw/XEoQWZ8uBQAJ) by any GA release at the moment. The docs are [pretty clear about that](http://www.rabbitmq.com/which-erlang.html).
