### ISSUE TITLE
post to  `/api/definitions` returns an empty reply . 

### ISSUE THREAD

**Issue by Zhan-Jie** [rabbitmq/rabbitmq-management#586]
I want to import 10000 rabbitmq users by calling HTTP API `/api/definitions` :
```
curl -F 'file=@users.json' -u test:123456 172.20.0.115:15672/api/definitions
```
After 1 min , an error occured :  `curl: (52) Empty reply from server` .
According to rabbit logs , the import stops exactly when 1 min passes. 

users.json is attached.
[users.json](https://github.com/rabbitmq/rabbitmq-management/files/2132978/users.txt)

Is there any timeout setting for rabbitmq_management plugin ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
It is possible to configure everything our embedded HTTP server, Cowboy, allows to be configured as of https://github.com/rabbitmq/rabbitmq-web-dispatch/pull/8 (originally https://github.com/rabbitmq/rabbitmq-management/issues/138). Please post questions to the mailing list in the future.

**Comment by michaelklishin** [comment]
It is also possible to bypass HTTP requests entirely and [load definitions on startup](http://www.rabbitmq.com/management.html#load-definitions). There is no timeout in that case that I can think of.

**Comment by Zhan-Jie** [comment]
According to your suggestion, I set response body compression of cowboy enabled, restarted rabbitmq server , and made another try .  The rabbitmq server still produces empty response (no HTTP headers or status line) after 1 min. 
```
curl -F 'file=@users.json' -u test:123456 172.20.0.115:15672/api/definitions
```
The rabbit log file shows that 618 users are imported and no error log entry : 
```
...
2018-06-26 12:42:18.127 [info] <0.2084.0> Asked to import definitions. Acting user: <<"test">>
2018-06-26 12:42:19.510 [info] <0.2084.0> Importing users...
2018-06-26 12:42:19.579 [info] <0.2084.0> Setting user tags for user 'guest' to [administrator]
2018-06-26 12:42:19.691 [info] <0.2084.0> Setting user tags for user 'test-0' to [administrator]
2018-06-26 12:42:19.767 [info] <0.2084.0> Setting user tags for user 'test-1' to [administrator]
2018-06-26 12:42:19.834 [info] <0.2084.0> Setting user tags for user 'test-2' to [administrator]
...
...
2018-06-26 12:43:17.950 [info] <0.2084.0> Setting user tags for user 'test-616' to [administrator]
2018-06-26 12:43:18.004 [info] <0.2084.0> Setting user tags for user 'test-617' to [administrator]
2018-06-26 12:43:18.093 [info] <0.2084.0> Setting user tags for user 'test-618' to [administrator]
```

I think it doesn't matter with large response body but the large request body from curl's POST request. The file `users.json` is about 3 MB. It seems that the HTTP request is closed abruptly by something before the server can finish importing . 
when there are only a few users in file `users.json` (file is small), the import is successful . 
this is similar to the issue [Responding to request with "big" body makes connection reach timeout. ](https://github.com/ninenines/cowboy/issues/985)

**Comment by Zhan-Jie** [comment]
curl's log
```
[root@k8s-test out]# curl -F 'file=@users.json' -v -u test:123456 http://172.20.0.115:15672/api/definitions                                 
* About to connect() to 172.20.0.115 port 15672 (#0)
*   Trying 172.20.0.115...
* Connected to 172.20.0.115 (172.20.0.115) port 15672 (#0)
* Server auth using Basic with user 'test'
> POST /api/definitions HTTP/1.1
> Authorization: Basic dGVzdDoxMjM0NTY=
> User-Agent: curl/7.29.0
> Host: 172.20.0.115:15672
> Accept: */*
> Content-Length: 3096147
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------3d8139a63f43
> 
< HTTP/1.1 100 Continue
* Empty reply from server
* Connection #0 to host 172.20.0.115 left intact
curl: (52) Empty reply from server
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
