### ISSUE TITLE
Make it possible to configure HTTP request timeout for `rabbitmqadmin`

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#593]
`rabbitmqadmin` doesn't currently set a timeout for its HTTP requests. It should be possible to set one.

Related issue on the HTTP handler end: #594.

**Comment by stoffus** [comment]
We are currently running into this when trying to import a definitions file in `3.7.14`. The file is around 230 kB.

**Comment by michaelklishin** [comment]
@stoffus our team does not use GitHub issues for discussions. This change does not make timeouts disappear, only allows `rabbitmqadmin` users to provide one that works for them. Definition file size does not matter, the number of entities that need setting up does as does cluster configuration (e.g. setting up 50K queues mirrored to 5 nodes is not the same as 5K non-mirrored ones).

**Comment by stoffus** [comment]
@michaelklishin Sorry, honest mistake. I was just reading the docs (https://www.rabbitmq.com/management.html) and found **Client Inactivity Timeouts** which seems to work as intended.
