### ISSUE TITLE
Expose `listener.cowboy_opts` to new style configuration file

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#596]
Current Cowboy options can only be [configured via the classic config format](https://www.rabbitmq.com/web-dispatch.html). Much like with TLS options, the set of values
is known, doesn't change often, and can benefit from additional validation. In addition it would be easier to enforce defaults (e.g. enable HTTP response compression) with Cuttlefish.

It would be nice to support at least a subset of Cowboy options in the new style format.

**Comment by michaelklishin** [comment]
Filed here for visibility. This equally applies to Web STOMP, Web MQTT and rabbitmq-top.

**Comment by asgs** [comment]
@michaelklishin  when will v3.7.8 be released?

**Comment by michaelklishin** [comment]
2-3 weeks sounds most likely. Don't quote me on that.

**Comment by michaelklishin** [comment]
It is [possible to configure Cowboy](http://www.rabbitmq.com/web-dispatch.html) using the classic format (so, `advanced.config`) today.

**Comment by michaelklishin** [comment]
@asgs this is not a discussion forum. If you have a reliable way to reproduce, post it to the mailing list and we'll see if we can.

**Comment by michaelklishin** [comment]
Reopening per some QA feedback from @acogoluegnes.

**Comment by scm-git** [comment]
from the version 3.7.8, the default configure format is key-value,right? when I use the classic format, it reports wrong format when I start rabbitmq-server;
but the classic configure format works well at version 3.7.7.

**Comment by michaelklishin** [comment]
@scm-git please [read the docs](http://www.rabbitmq.com/configure.html#configuration-files) and ask questions on the mailing list. Nothing has changed between 3.7.7 and 3.7.8. You can use either format.
