### ISSUE TITLE
3.7.7 Config file location not visible in management UI

### ISSUE THREAD

**Issue by Danthar** [rabbitmq/rabbitmq-management#605]
RMQ: 3.7.7
Erl: 21.0.1

Management UI page: Overview
Browser: Not Applicable. Problem occurs in every browser
JS Errors: None

We upgraded from 3.6.9 to 3.7.7 and im noticing that the config paths information is no longer visible on the main Overview page.
Is this intentional ? Do you know that the main RMQ website docs still say it should be visible? https://www.rabbitmq.com/configure.html. 
Am i missing some config somewhere. Or is this a bug ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
It is not intentional and they should be listed. We do not have enough information to suggest much: no server logs (which list the paths as well), no details as to what config files exist or their contents. This is mailing list material.

**Comment by lukebakken** [comment]
FWIW, I can't reproduce with RabbitMQ 3.7.7 and Erlang 21.0.7. See screenshot. @Danthar - RabbitMQ logs the effective configuration files in the log like this - you should check it:

```
 Starting RabbitMQ 3.7.7 on Erlang 21.0.7
 Copyright (C) 2007-2018 Pivotal Software, Inc.
 Licensed under the MPL.  See http://www.rabbitmq.com/
2018-08-31 08:12:39.021 [info] <0.266.0> 
 node           : rabbit@shostakovich
 home dir       : /home/lbakken
 config file(s) : /home/lbakken/issues/pt/159894176-java-client-hostname-verification/rabbitmq.config
 cookie hash    : dcUa4Oz7dwb56LNQXcdWdg==
 log(s)         : /home/lbakken/issues/rmq-generic-unix/rabbitmq_server-3.7.7/var/log/rabbitmq/rabbit@shostakovich.log
                : /home/lbakken/issues/rmq-generic-unix/rabbitmq_server-3.7.7/var/log/rabbitmq/rabbit@shostakovich_upgrade.log
 database dir   : /home/lbakken/issues/rmq-generic-unix/rabbitmq_server-3.7.7/var/lib/rabbitmq/mnesia/rabbit@shostakovich
```

![rmq-mgmt-config-file](https://user-images.githubusercontent.com/514926/44920855-d8db0f00-acf5-11e8-923e-efc45c786b5d.png)

**Comment by michaelklishin** [comment]
I suspect it's one of the edge cases where `advanced.config` wasn't used if `rabbitmq.conf` did not exist (addressed for 3.7.8) or something similar. That's why we need details on the list.

**Comment by Danthar** [comment]
Ok. its much simpler.

Its not some edge case or anything fancy :P

In 3.6.9 this information was shown directly in the Overview page, above the Ports and contexts section. You didn't have to expand the Node information.

But now. if you want to see this information, you have to click on the node in the main overview. It then expands the information for that node. And thats where it now shows the config information. @lukebakken screenshot tipped me off.

So case closed ^^

**Comment by lukebakken** [comment]
@Danthar great thanks for following up. I didn't realize that info had moved.
