### ISSUE TITLE
RabbitMq overview gives me bad_utf8_character_code

### ISSUE THREAD

**Issue by joaoportela** [rabbitmq/rabbitmq-management#61]
Opening rabbitmq management overview page gives me:

    Got response code 500 with body {"error":"Internal Server Error","reason":"{error,{exit,{ucs,{bad_utf8_character_code}},\n [{xmerl_ucs,from_utf8,1,[{file,\"xmerl_ucs.erl\"},{line,186}]},\n {mochijson2,json_encode_string,2,[]},\n {mochijson2,'-json_encode_proplist/2-fun-0-',3,[]},\n {lists,foldl,3,[{file,\"lists.erl\"},{line,1262}]},\n {mochijson2,json_encode_proplist,2,[]},\n {mochijson2,'-json_encode_array/2-fun-0-',3,[]},\n {lists,foldl,3,[{file,\"lists.erl\"},{line,1262}]},\n {mochijson2,json_encode_array,2,[]}]}}\n"}

I believe this is because my appdata folder is "C:\Users\João\AppData\Roaming". My guess is that the "ã" is not being properly encoded to utf-8.

Other rabbitmq management pages work fine.

**Comment by michaelklishin** [comment]
Non-ASCII characters in RabbitMQ [installation directory on Windows are not supported](http://www.rabbitmq.com/windows-quirks.html) and will lead to other problems.

**Comment by joaoportela** [comment]
This is not the installation directory. This is the %appdata% directory, the "windows quirks" page doesn't help with that.

Is there a work around?

**Comment by michaelklishin** [comment]
You can [relocate data directory](http://www.rabbitmq.com/relocate.html).

**Comment by joaoportela** [comment]
I have set a system environment variable with RABBITMQ_BASE=c:\RabbitMq_Base but it isn't working.

Any other troubleshooting steps?

**Comment by michaelklishin** [comment]
From http://www.rabbitmq.com/configure.html:

```
For environment changes to take effect on Windows, the service must be re-installed. It is not sufficient to restart the service. This can be done using the installer or on the command line with administrator permissions: …
```

**Comment by joaoportela** [comment]
Thank you.
