### ISSUE TITLE
URI of federation upsteams is incorrect when upstream is a remote cluster.

### ISSUE THREAD

**Issue by lamoce** [rabbitmq/rabbitmq-management#617]
* RabbitMQ version 3.7.8
* Erlang version Erlang/OTP 20 [erts-9.3.3.2]

I created the federation upstream using the command listed below:

`rabbitmqctl set_parameter federation-upstream fd_upstream '{"uri":["amqp://server1","amqp://server2","amqp://server3"],"expires":3600000, "message-ttl": 300}' -p fdhost`

but in management ui, in the federation upsteams tab, the uri of the federation shows 
`<span class="unknown">?...--`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
The URI parameter is expected to be [a single URI](https://www.rabbitmq.com/federation.html) and not an array of URIs.

**Comment by michaelklishin** [comment]
Each upstream represents a connection to a single endpoint (node or cluster, depending on whether a load balancer is involved).

Shovel does support [multiple endpoints per Shovel](http://www.rabbitmq.com/shovel-dynamic.html) (search for "src-uri") but connects to just one at a time (the first from the list that it can successfully connect to).

This is 100% mailing list material, please stop filing issues for questions. Thanks.
