### ISSUE TITLE
templates overwritten on server restart

### ISSUE THREAD

**Issue by freimanas** [rabbitmq/rabbitmq-management#62]
Hi,

sorry if this is not the right place, but it sure looks like something out of the ordinary here...

As an example: I try to modify the template for `/priv/www/js/tmpl/queues.ejs` so it displays number of consumers on each queue. all is good and fine, now if i restart the server template goes back to the original, and I need to edit that template again to have number of consumers listed.

Just could not find any documentation on how that is implemented and why it is overwritten...

anyhow it would be really nice to have a feature to display extra data to the templates currently provided, all the data that is already within the JSON docs and can easily be displayed, we would just need to select which data to show.... any idea if that would be a good feature request?

Cheers!

**Comment by michaelklishin** [comment]
You need to build the plugin with 'make' after modifying the template.
Questions belong to rabbitmq-users.
