### ISSUE TITLE
Conflicting definitions are skipped instead of returning error

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-management#627]
According to the HTTP API docs, conflicting queue definition import should result with an error. Instead it returns 204.

`rabbit_amqqueue:assert_equivalence` is only executed in rabbit_channel, but not for definitions.
Conflicting definition is just skipped.

Maybe docs should be updated. Maybe it should actually return an error and stop import.

Simple way to reproduce:
- Declare a queue
- Export vhost definitions
- Edit the queue durability in the definitions file
- Import the definitions

The result will be 204.

[161790451]

**Comment by michaelklishin** [comment]
The management guide is ambiguous about what should happen with conflicts:

```
Note that the definitions in the file will overwrite anything already in the broker; using this option will not delete anything that is already there
```

but my reading of it given the rest of the content in that section is that conflicting definitions are expected to be skipped.

**Comment by hairyhum** [comment]
I was refering to HTTP API docs http://37.gcp.rabbitmq.com/api/index.html
Stating that `Conflicting definitions on immutable objects (exchanges, queues and bindings) will cause an error. `
