### ISSUE TITLE
Move from Webmachine to Cowboy

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-management#63]
It's a fairly large task involving more than a handful of applications, including management, web-dispatch, web-stomp-examples and many applications depending on management. I will try to maintain the API (and so avoid making changes in these many applications) but they will need to at least be tested to confirm everything works as intended.

The community plugins found at https://www.rabbitmq.com/community-plugins.html should also be checked. Since Webmachine is being removed, there's no other choice than breaking things (plugins include a header from Webmachine), but hopefully that break will be only constrained to resources and will be easy to document and fix.

* [x] management: port definitions resource multipart handling code to Cowboy
  * `curl -i http://guest:guest@localhost:15672/api/definitions -X POST -H "content-type: multipart/form-data;boundary=abcdef"`
* [x] management: git grep wrq
* [x] management: git grep -i webmachine
* [x] management: play around in the UI
* [x] management: tests
* [x] web dispatch: tests
* [x] management: add / -> /index.html routes
* [x] management: add redirects for API etc.
* [x] management: access logs
* [x] management: fix crashes found in logs during (successful) tests
* [x] management: support both IPv4 and IPv6 (https://github.com/rabbitmq/rabbitmq-management/issues/64)
* [x] management: last clean up, check warnings, unused functions, Dialyzer
* [x] web dispatch: git grep -i webmachine
* [x] web dispatch: git grep Req:
* [x] web dispatch: test with SSL
* [x] web dispatch: error handler
* [x] web dispatch: update plugins that use web dispatch
* [x] web dispatch: last clean up, check warnings unused functions, Dialyzer
* [x] web dispatch: update README
* [x] web stomp: make sure examples still work
* [x] update documentation

**Comment by essen** [comment]
Spent 3 days on this so far. It's still a work in progress and here is a lit of things I still need to look at:

* git grep wrq:
* git grep -i webmachine
* make test (currently fails early)
* add / -> /index.html routes
* add the redirects that I left out for now
* probably left a few warnings/unused functions for now for things that are not fully done
* check ssl
* check the plugins that depend on web dispatch and fix them as interface changed slightly

Everything I tried in the UI works as far as I can see, but I didn't try everything and I know some things are not working yet. I suspect this needs about 3 days of additional work to get it to completion.

**Comment by michaelklishin** [comment]
Thank you, Loïc.

We have at least 2 fairly well covered client libraries for the HTTP API to help with testing.

**Comment by essen** [comment]
This is ready for review!

**Comment by michaelklishin** [comment]
We need to decide if this can go into `3.6.x`. Otherwise so far the changes look ready. I'll do some more testing of definitions export/import.

**Comment by michaelklishin** [comment]
Merged into master only.
