### ISSUE TITLE
Rabbitmqadmin get queue not found

### ISSUE THREAD

**Issue by xtrembaker** [rabbitmq/rabbitmq-management#631]
Hello all !

I'm using rabbitmqadmin version 3.7.8.
When I'm doing the following command:
`
rabbitmqadmin get queue=my_queue_name
`

I'm getting the following error:
`
*** Not found: /api/queues/%2F/my_queue_name/get
`

I've tested with different queue name, I always get the same error.
Can anyone help me ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Not a lot can be suggested without RabbitMQ and `rabbitmqadmin` versions as well as `rabbitmqctl list_queues -p /` output and server logs. This is mailing list material.

**Comment by lukebakken** [comment]
@xtrembaker the `rabbitmqadmin get` command will get one message from a queue. `Not found` means that there are no messages in the queue to get.
