### ISSUE TITLE
charset with response header 'Content-Type'

### ISSUE THREAD

**Issue by prasanthks** [rabbitmq/rabbitmq-management#633]
I am using HTTP API from DB2 SQL using the supplied UDF.  This needs charset to be supplied in the Response Header 'Content-Type'. E.g 'Content Type:application/json:charset=utf-8'. Is there a Setting in RabbitmQ where I can get this charset as well? Thanks in advance.

What we normally get in Response Header is as follows (re-producable with a simple curl) 
----------------------------------------------------------------------------------------------------
< content-length: 448                      
content-length: 448                        
< content-type: application/json           
content-type: application/json             
< date: Wed, 21 Nov 2018 10:40:44 GMT      
date: Wed, 21 Nov 2018 10:40:44 GMT        
< server: Cowboy                           
server: Cowboy                             
< vary: accept, accept-encoding, origin    
vary: accept, accept-encoding, origin

Thanks,
Prasanth.

**Comment by lukebakken** [comment]
Hi Prasanth,

Thanks for using RabbitMQ. We only use GitHub issues for actionable work. When you clicked "New Issue", you should have seen a document indicating as such.

Please post this question to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list and provide the following information:

* RabbitMQ and Erlang version
* Full `curl` request that you are making
* Full response attached to your message in a text file

If we determine an actual issue exists, we will re-open this GitHub issue.

**Comment by prasanthks** [comment]
The Version is 3.7.5.

**Comment by lukebakken** [comment]
@prasanthks please read my instructions in [this comment](https://github.com/rabbitmq/rabbitmq-management/issues/633#issuecomment-440708006) and follow them if you would like assistance. Thank you.

**Comment by prasanthks** [comment]
Thanks. The original problem is that the german umlauts are not being received correctly in IBM i with  http API of Rabbitmanagement api. I have found out this is probably because the RMQ server is not sending the charset along with content-type. I thought this is the default behaviour of server and may be needs to be added. Anyway will send it to the mailing list as suggested. Thanks for your reply.

**Comment by lukebakken** [comment]
Thank you. The author of Cowboy has already followed up: [link](https://groups.google.com/d/msg/rabbitmq-users/2MwsaQWkFwM/ku1phYPAAgAJ)

**Comment by lukebakken** [comment]
In addition, please see this discussion: https://github.com/request/request/issues/383
