### ISSUE TITLE
"Last 8 hours" and "Last day" stat selection improvement

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#635]
See #475 

If the user has not configured `sample_retention_policies` for the `basic` stats to save data for a day's worth, the per-queue page can be confusing if the user selects "Last 8 hours" or "Last day". The time period will be incorrect in the graph, and there will be no stats since they aren't saved.

We could consider removing those UI radio buttons if the `basic` retention policy is set to the default.

**Comment by michaelklishin** [comment]
4 or 6 hours sounds sufficient for most scenarios to me. Anything than longer than that should use a dedicated monitoring/time series service (Prometheus, Datadog and so on).
