### ISSUE TITLE
ConnectionRefusedError is not defined in python2

### ISSUE THREAD

**Issue by theMPatel** [rabbitmq/rabbitmq-management#647]
https://github.com/rabbitmq/rabbitmq-management/blob/0fd4da3f0462f991d603490bae710e01920d4a96/bin/rabbitmqadmin#L554

We ran into an issue at work whereby the connection request in the try/catch failed but because this was started using py2, it exited with a NameError rather than the appropriate message. Has anybody seen this before and/or is this an 'us' issue? Thanks!

**Comment by michaelklishin** [comment]
This is not the right place for questions.

According to Python documentation, `ConnectionRefusedError` is only available in Python 3, so is its superclass, `ConnectionError`. `rabbitmqadmin` generally is compatible with Python 2.7.9 and later versions but it's a best effort kind of thing. Python 2 users are welcome to submit pull requests that improve compatibility. That said, I don't think betting your farm on Python 2 is wise in 2019.

**Comment by michaelklishin** [comment]
So `ConnectionError` is a subclass of `OSError` according to [the docs](https://docs.python.org/3/library/exceptions.html) (not particularly easy to spot) and Python source.

One solution can be to define it for Python 2 the same way and catch `ConnectionError` instead of `ConnectionRefusedError`. Feel free to look into it.

**Comment by theMPatel** [comment]
Sometimes one does not have a choice in the technologies a farm is based on and you have to do the best with what you have. Thanks for the tip!

**Comment by dequis** [comment]
Not sure how much python2 matters at this point, but the fix linked to this issue doesn't work

```python
import sys

if sys.version_info[0] == 2:
    import httplib
else:
    import http.client as httplib

if sys.version_info[0] == 2:
    class ConnectionError(OSError):
        pass
    class ConnectionRefusedError(ConnectionError):
        pass

a = httplib.HTTPConnection('0.0.0.0', 1234)
try:
    a.request('A', 'A')
except ConnectionRefusedError:
    print('caught successfully')
```

Works on python3 but throws this on python2:

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    a.request('A', 'A')
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

This works:

```python
import sys

if sys.version_info[0] == 2:
    import httplib
else:
    import http.client as httplib

if sys.version_info[0] == 2:
    from socket import error as ConnectionRefusedError

a = httplib.HTTPConnection('0.0.0.0', 1234)
try:
    a.request('A', 'A')
except ConnectionRefusedError:
    print('caught successfully')
```

**Comment by michaelklishin** [comment]
We cannot comment on "it does not work" as it lacks specifics. The change in https://github.com/rabbitmq/rabbitmq-management/commit/941e7d4beb63a9341051f5adb77e8bf5d2b6e947 was verified.

Instead of posting comments here, consider submitting a pull request. With Python 2.7 going
EOL in 2020, it's not a priority for our team but we can quite easily test a PR.

**Comment by michaelklishin** [comment]
If we consider this message to be problematic

```
socket.error: [Errno 111] Connection refused
```

then I'd argue that it provides a fairly specific error message.

**Comment by michaelklishin** [comment]
No worries, thank you for providing the details. Soon enough this issue won't be very relevant. The nice aspect of `rabbitmqadmin` being a zero dependency script is that it can be easily modified for the needs of a specific environment.
