### ISSUE TITLE
fmt_percent formats undefined as 0

### ISSUE THREAD

**Issue by Avivsalem** [rabbitmq/rabbitmq-management#660]
The function fmt_percent on formatters.js formats undefined (null) as 0 instead of N/A.

I causes consumer utilization of queue to show 0% when no consumers.

The current code looks for '' (empty string) to format as N/A. but an earlier bugfix that you merged changed it from '' to null... Guess you forgot to change here also...

**Comment by michaelklishin** [comment]
This is intentional. When it's `N/A%`, both humans and statically typed HTTP API consumers freak out and report that as a bug.

**Comment by Avivsalem** [comment]
Really? I'd expect it to be NaN.
Otherwise, it makes me think that my utilization is problematic in those queues (can't differentiate between real 0%,where I have to improve my consumers, and "fake" 0% where I don't have to do anything...)

For me, seeing 0% is more confusing then seeing NaN or N/A.

Maybe if I could change it locally to myself... Any suggestions?

**Comment by Avivsalem** [comment]
Also, if it's intentional, why is the comparison to an empty string still there?

**Comment by michaelklishin** [comment]
@Avivsalem yes, really. We had it at `N/A%` or something like that before and that was reported as an issue.

0% utilisation is intended to attract operator and monitoring system attention as in a realistic system it's probably expected to be above 0. So while we are well aware that `0` is not the same as "no value", there is some logic to this thinking.

Comparison with values previously returned by the API can be mistakes. The management UI in its current form doesn't get much attention as we concluded that the only way to really improve it is a complete rewrite using a modern day set of tools for single page apps. Pull requests with small corrections (and detailed steps to reproduce the problem) are welcome.

This team does not use GitHub issues for discussions.
