### ISSUE TITLE
Virtual host limit endpoints documentation is confusing and incorrect

### ISSUE THREAD

**Issue by deadanon** [rabbitmq/rabbitmq-management#666]
Steps to reproduce:

Create at least one vhost limit.
GET /api/vhost-limits  via REST API
```
[
    {
        "vhost": "local",
        "value": {
            "max-connections": 50
        }
    }
]
```

Attempt to change limit via
PUT /api/vhost-limits/vhost/local
BODY {"max-connections": 100}
```
{
    "error": "not_found",
    "reason": "vhost_not_found"
}
```

**Comment by lukebakken** [comment]
I can reproduce this using RabbitMQ `3.7.12`, thanks -

```
$ curl -4u 'guest:guest' -H 'content-type: application/json' -X PUT localhost:15672/api/vhost-limits/vhost/local -d '{"max-connections":50}'
{"error":"not_found","reason":"vhost_not_found"}
```

**Comment by michaelklishin** [comment]
Here are [the routes](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_dispatcher.erl#L121). The interesting endpoint is

`"/vhost-limits/:vhost/:name"`

The `{vhost}` parameter is expected to be the virtual host name and the `{name}` one is the limit name. So you are not using the endpoint correctly.

**Comment by lukebakken** [comment]
@michaelklishin we've got to fix the docs then - https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.12/priv/www/api/index.html

**Comment by michaelklishin** [comment]
I agree with that. The docs provide an incorrect payload example and this language is confusing:

```
Set or delete per-vost limit for vhost with name
```

What the `name` refers to is not at all clear.

**Comment by lukebakken** [comment]
Yep. I've got to figure out exactly how to make the requests, since this ain't it:

```
$ curl -4u 'guest:guest' -X PUT localhost:15672/api/vhost-limits/local/max-connections -d 50

$ curl -4u 'guest:guest' localhost:15672/api/vhost-limits/local
[]
```

**Comment by michaelklishin** [comment]
The docs also claim that `/api/vhost-limits/{vhost}` only supports `GET` requests but the code says it does support `PUT`. It is not a copy-paste artifact because `PUT` support was introduced in https://github.com/rabbitmq/rabbitmq-management/commit/f608459cb0c21b3c7c0af090303974a41b78b17a.

**Comment by lukebakken** [comment]
Voila, this works:

```
$ curl -4u 'guest:guest' -H 'content-type:application/json' -X PUT localhost:15672/api/vhost-limits/local/max-connections -d '{"value": 50}'
```

**Comment by michaelklishin** [comment]
```
curl -u guest:guest -X PUT -H 'Content-Type: application/json' http://warp10.local:15672/api/vhost-limits/management-666/max-connections --data-raw '{"value": 888}'
curl -u guest:guest -X GET http://warp10.local:15672/api/vhost-limits | jq
```

**Comment by deadanon** [comment]
> Voila, this works:
> 
> ```
> $ curl -4u 'guest:guest' -H 'content-type:application/json' -X PUT localhost:15672/api/vhost-limits/local/max-connections -d '{"value": 50}'
> ```
> @deadanon ^^^^

This works perfectly!

**Comment by michaelklishin** [comment]
There may still be a legitimate problem with PUTs in the `/api/vhost-limits/{vhost}` endpoint.
I don't see what it does [in response to `PUT` requests](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_limits.erl) in the code and https://github.com/rabbitmq/rabbitmq-management/commit/f608459cb0c21b3c7c0af090303974a41b78b17a doesn't make it any clearer.

**Comment by michaelklishin** [comment]
Management UI doesn't have a way to set or clear N limits at once, so the `PUT` verb for `/api/vhost-limits/{vhost}` has no reason to exist.

**Comment by lukebakken** [comment]
All set, thanks for the report @deadanon
