### ISSUE TITLE
Not authorized responses (401) deliver JSON bodies, skip content-type header

### ISSUE THREAD

**Issue by smee** [rabbitmq/rabbitmq-management#67]
If the credentials are invalid the response will encode its body as JSON but does not add the "content-type" header with "application/json" as value. This means that parsing responses needs to be extra careful when interpreting these error messages.

**Comment by michaelklishin** [comment]
Thanks, @smee!

@Gsantomaggio assigning to you as you already have some experience with the plugin. This is for `3.5.7` (early November).

**Comment by Gsantomaggio** [comment]
The problem is in [this function](https://github.com/rabbitmq/rabbitmq-management/blob/rabbitmq-management-67/src/rabbit_mgmt_util.erl#L288), since the result is `json` but the `content-type` is not set.

we are going to add the  `set_resp_header("Content-Type", "application/json"`

**Comment by michaelklishin** [comment]
Fixed in #69.
