### ISSUE TITLE
Management UI does not support long queue names with dots and spaces

### ISSUE THREAD

**Issue by AndrewDryga** [rabbitmq/rabbitmq-management#672]
Hey guys,

It looks like management UI does not support queue names with dots in the name. See screenshots:
<img width="1680" alt="Снимок экрана 2019-03-15 в 13 03 02" src="https://user-images.githubusercontent.com/1877644/54427265-b30dd880-4722-11e9-9aee-f497f7971e8e.png">
<img width="1680" alt="Снимок экрана 2019-03-15 в 13 03 05" src="https://user-images.githubusercontent.com/1877644/54427266-b30dd880-4722-11e9-9928-34a94fe5b026.png">

Once I click on queue name it renders 404 page. I also see a request to back-end in Chrome inspector which returns 404:

`GET https://HOST/api/queues/TalkInto.Domain.Analytics.Subscriber?lengths_age=3600&lengths_incr=60&msg_rates_age=3600&msg_rates_incr=60&data_rates_age=3600&data_rates_incr=60`
.

* RabbitMQ version: 3.7.13
* Erlang version: 21.2.7
* Operating system, version, and patch level: MacOS, latest Chrome browser

**Comment by michaelklishin** [comment]
Yes, it does. Plenty of test suites and examples of policies use dots.

**Comment by michaelklishin** [comment]
Here's one example:
<img width="634" alt="Screenshot 2019-03-15 at 16 29 00" src="https://user-images.githubusercontent.com/1090/54434519-81573a80-473f-11e9-9f2f-5c4352046f66.png">

There can be any number of reasons, e.g. an HTTP server in front doing request rewrites. This is mailing list material.
