### ISSUE TITLE
requeue option of the Get Messages UI is ignored

### ISSUE THREAD

**Issue by ghost** [rabbitmq/rabbitmq-management#68]
When using the "Get Message(s)" button it appears as if a `noack` with no requeue was sent (look at the graph). But the message is never sent to the dead letter exchange.

If it's intentional then I find it misleading. Spend a few hours messing around with different settings to get it to work. Until I found out that setting TTL was the way to go.

![image](https://cloud.githubusercontent.com/assets/7996710/10416593/dcf9498a-701c-11e5-8772-eed87d056c3c.png)

**Comment by michaelklishin** [comment]
Looking at the code, it seems that "no requeue" is treated slightly differently from what you expect:

``` erlang
NoAck = not rabbit_mgmt_util:parse_bool(RequeueBin),
```

and then

``` erlang
basic_get(Ch, Q, NoAck, Enc, Trunc) ->
    case amqp_channel:call(Ch, #'basic.get'{queue = Q,
                                            no_ack = NoAck}) of
        {#'basic.get_ok'{redelivered   = Redelivered,
                         exchange      = Exchange,
                         routing_key   = RoutingKey,
                         message_count = MessageCount},
         #amqp_msg{props = Props, payload = Payload}} ->
            [{payload_bytes, size(Payload)},
             {redelivered,   Redelivered},
             {exchange,      Exchange},
             {routing_key,   RoutingKey},
             {message_count, MessageCount},
             {properties,    rabbit_mgmt_format:basic_properties(Props)}] ++
                payload_part(maybe_truncate(Payload, Trunc), Enc);
        #'basic.get_empty'{} ->
            none
    end.
```ˇ

It other words, it is used as the noack argument to `basic.get` but nothing else as far as I can tell.

**Comment by Gsantomaggio** [comment]
As  @michaelklishin wrote the `requeue` [value](https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_queue_get.erl#L87) is used as `noack` for `basic.get` .


Basically it is different the meaning of `requeue`.

To use `requeue` option we could set `no_ack = false`  and then use `basic.reject` as:

   

    basic_get(Ch, Q, Requeue, Enc, Trunc) ->
        case amqp_channel:call(Ch, #'basic.get'{queue = Q,
                                                no_ack = false}) of
            {#'basic.get_ok'{redelivered   = Redelivered,
                             exchange      = Exchange,
                             routing_key   = RoutingKey,
                             message_count = MessageCount,
                             delivery_tag  = DeliveryTag},
             
             #amqp_msg{props = Props, payload = Payload}} ->
             amqp_channel:call(Ch, #'basic.reject'{delivery_tag = DeliveryTag,
                                                requeue = Requeue}),
                [{payload_bytes, size(Payload)},
                 {redelivered,   Redelivered},
                 {exchange,      Exchange},
                 {routing_key,   RoutingKey},
                 {message_count, MessageCount},
                 {properties,    rabbit_mgmt_format:basic_properties(Props)}] ++
                    payload_part(maybe_truncate(Payload, Trunc), Enc);

    
In this case the  when you set `requeue = false` the message will be redirect to the dead letter exchange (if you have one)

**Comment by Gsantomaggio** [comment]
To be more generic we could modify the  `requeue`  with something like this:
    ` <select name="requeue">`
    ` <option value="ack">Ack message </option>`
    ` <option value="nack">NAck message </option>`
    ` <option value="reject_false">Reject requeue false</option>`
    ` <option value="reject_true">Reject requeue true</option>`
     `</select>`


See the [image here](https://dl.dropboxusercontent.com/u/17370989/ACK%20mode.png)

**Comment by Gsantomaggio** [comment]
The branch [`rabbitmq-management-68`](https://github.com/rabbitmq/rabbitmq-management/tree/rabbitmq-management-68) contains the new `Get Message(s)`.


UI options:
![get_messages](https://cloud.githubusercontent.com/assets/386987/14911775/e9cc1d3a-0df7-11e6-81c9-542ef99d578f.png)



I had to change the `requeue = yes/no` API with:
 ```
ackmode=ack_requeue_false
ackmode=ack_requeue_true
ackmode=reject_requeue_false
ackmode=reject_requeue_true 
```         

So, we have more options, but we **lose the API compatibility**.

**Comment by michaelklishin** [comment]
@Gsantomaggio that's fine, then it should go into `3.7.0`.

**Comment by yegos** [comment]
> @Gsantomaggio that's fine, then it should go into `3.7.0`.

It's not fine. I spend 40 minutes to find all possible options list

**Comment by lukebakken** [comment]
@yegos - could you elaborate on the trouble you had by posting a message to [`rabbitmq-users`](https://groups.google.com/forum/#!topic/rabbitmq-users/wY_o5t-QzgI)? Please be sure to let us know what version of RabbitMQ and Erlang you're using.

**Comment by michaelklishin** [comment]
@yegos what I meant by "fine" is that a feature release in our case allows for breaking changes. We updated HTTP API clients that we maintain as well as `rabbitmqadmin` to match.

I see that the docs [in the HTTP API reference](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.9/priv/www/api/index.html) do mention all possible values in the `/api/queues/{vhost}/{name}/get` endpoint description. All of our docs are open source and the entire core team is on our mailing list, so your PRs and feedback on the docs is always welcome.

**Comment by michaelklishin** [comment]
[RabbitMQ 3.7.0 release notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0) do mention breaking changes in the HTTP API. I added a note **in bold** next to this specific issue to mention that the request body expected from the client has changed.

If you have other ideas as to what can be improved, they are welcome on the list. FWIW RabbitMQ 3.7.0 has shipped 1 year ago, so at this point it's on library and tool authors who haven't caught up wit the changes.
