### ISSUE TITLE
Queue details vary with headers

### ISSUE THREAD

**Issue by blackheaven** [rabbitmq/rabbitmq-management#699]
I'm trying to get the [message count of a queue via the management API](https://github.com/linagora/james-project/pull/2325/files#diff-a37ac63e67cb9dd5e9f5bf0823eb29df).

I used to get it via `/api/queues/{vhost}/{name}`, I get the `messages` key but it requires a bit of work.

A suggestion have been made to directly use `/api/queues/{vhost}/{name}`, so I have added:

```
@RequestLine(value = "GET /api/queues/{vhost}/{name}", decodeSlash = false)
void getQueue(@Param("vhost") String vhost, @Param("name") String name);
```

And we do not get `messages` anymore.

We use:
 * `feign-core` `10.2.0`
 * The Docker image of RabbitMQ `rabbitmq:3.7.7-management`

After a while we've dumped the log from `feign`:

```
---> GET http://localhost:33005/api/queues/%2F/JamesMailQueue-workqueue-spool HTTP/1.1
Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
---> END HTTP (0-byte body)
<--- HTTP/1.1 200 OK (5ms)
cache-control: no-cache
content-length: 357
content-type: application/json
date: Tue, 30 Apr 2019 16:20:31 GMT
server: Cowboy
vary: accept, accept-encoding, origin

{"garbage_collection":{"max_heap_size":-1,"min_bin_vheap_size":-1,"min_heap_size":-1,"fullsweep_after":-1,"minor_gcs":-1},"consumer_details":[],"incoming":[],"deliveries":[],"node":"rabbit@my-rabbit-223d4572-cc03-4c31-b051-43173a8c3944","arguments":{},"exclusive":false,"auto_delete":false,"durable":true,"vhost":"/","name":"JamesMailQueue-workqueue-spool"}
<--- END HTTP (357-byte body)
```

We find it quite short, so we have tried a `curl`:

```
curl -v -u guest:guest http://localhost:33005/api/queues/%2F/JamesMailQueue-workqueue-spool
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 33005 (#0)
* Server auth using Basic with user 'guest'
> GET /api/queues/%2F/JamesMailQueue-workqueue-spool HTTP/1.1
> Host: localhost:33005
> Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< cache-control: no-cache
< content-length: 1797
< content-type: application/json
< date: Tue, 30 Apr 2019 16:12:18 GMT
< server: Cowboy
< vary: accept, accept-encoding, origin
<
{"consumer_details":[],"incoming":[],"deliveries":[],"messages_details":{"rate":0.0},"messages":1,"messages_unacknowledged_details":{"rate":0.0},"messages_unacknowledged":0,"messages_ready_details":{"rate":0.0},"messages_ready":1,"reductions_details":{"rate":0.0},"reductions":9846,"message_stats":{"deliver_get_details":{"rate":0.0},"deliver_get":1,"ack_details":{"rate":0.0},"ack":0,"redeliver_details":{"rate":0.0},"redeliver":0,"deliver_no_ack_details":{"rate":0.0},"deliver_no_ack":0,"deliver_details":{"rate":0.0},"deliver":1,"get_no_ack_details":{"rate":0.0},"get_no_ack":0,"get_details":{"rate":0.0},"get":0,"publish_details":{"rate":0.0},"publish":2},"node":"rabbit@my-rabbit-223d4572-cc03-4c31-b051-43173a8c3944","arguments":{},"exclusive":false,"auto_delete":false,"durable":true,"vhost":"/","name":"JamesMailQueue-workqueue-spool","message_bytes_paged_out":0,"messages_paged_out":0,"backing_queue_status":{"avg_ack_egress_rate":0.0,"avg_ack_ingress_rate":0.0,"avg_egress_rate":0.0,"avg_ingress_rate":0.1289355721* Connection #0 to host localhost left intact
011951,"delta":["delta","undefined",0,0,"undefined"],"len":1,"mode":"default","next_seq_id":1,"q1":0,"q2":0,"q3":0,"q4":1,"target_ram_count":"infinity"},"head_message_timestamp":null,"message_bytes_persistent":0,"message_bytes_ram":431,"message_bytes_unacknowledged":0,"message_bytes_ready":431,"message_bytes":431,"messages_persistent":0,"messages_unacknowledged_ram":0,"messages_ready_ram":1,"messages_ram":1,"garbage_collection":{"minor_gcs":7,"fullsweep_after":65535,"min_heap_size":233,"min_bin_vheap_size":46422,"max_heap_size":0},"state":"running","recoverable_slaves":null,"consumers":0,"exclusive_consumer_tag":null,"effective_policy_definition":[],"operator_policy":null,"policy":null,"consumer_utilisation":null,"idle_since":"2019-04-30 16:10:35","memory":17704}
```

Here we get what we expect: a lot of information, including `messages`.

It's a bit surprising, the only different on the client side seems to be in the headers.

Is it an expected behavior? Thanks for your feedback.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Message rates would be excluded if there were no samples (to put it another way, all rates were zero) for the time interval requested. So likely there simply haven't been any activity on the node/cluster recently. Try [running PerfTest](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/) concurrently with your experiments ;)

I agree that it is somewhat confusing and we have discussed returning zeros instead but it is less trivial a change than it sounds. We will discuss this with @dcorbacho and @gerhard.

**Comment by michaelklishin** [comment]
Err, published too soon. So the variable you are not accounting for is time (and the sliding stat sample window this plugin uses internally) :)

**Comment by blackheaven** [comment]
Thanks for your answer.

I do not thinks so, I did not get this issues when I query for all the queues while it's reproducible with specifying one queue.

**Comment by michaelklishin** [comment]
@blackheaven I am quite certain. We exclude metrics only when there are no samples for them. If you have a way to consistently reproduce, please share it on the mailing list. We do not use GitHub issues for discussions and investigations. Thank you.
