### ISSUE TITLE
effective_policy_definition is sometimes an object, sometimes an array

### ISSUE THREAD

**Issue by wjdavis5** [rabbitmq/rabbitmq-management#701]
**RabbitMQ version**
3.7.10
**Erlang version**
20.3

**When calling the API:**
`/api/queues/VHOST/`

The json property for `effective_policy_definition`
is either a json object if it has a value
or an empty json array if it doesnt have a value:

**Empty:**
`"effective_policy_definition": [],`

**With value:**
```
"effective_policy_definition": {
            "ha-mode": "exactly",
            "ha-params": 2
        },
```

This makes serializing the response cumbersome, and the result should be consistent.

**Comment by michaelklishin** [comment]
#75 and #424 in a different place.
