### ISSUE TITLE
Root vhost encoding

### ISSUE THREAD

**Issue by tarastriska** [rabbitmq/rabbitmq-management#702]
I use rabbitmq 3.7.14 web interface.
There are 2 vhosts:

1. Root (/)
2. Custom

There are exchanges/queues/etc. for both vhosts.
They are shown well in list views. However once I wanna click on any object to get details it fails for any resource from root vhost and works fine for custom.
It encodes URL with /%2F/ for root and always return 404 for get.
Does it mean that I have to use specific vhost instead of root?

**Comment by michaelklishin** [comment]
Very likely something (a browser plugin, a proxy) in your environment rewrites or double-encodes %-encoded values. This is not a commonly reported issue. Keep in mind that our team uses management UI pretty much every day. Nothing around HTTP resource routing has changed in 5 or so years.

**Comment by michaelklishin** [comment]
You can use any virtual host you please, including overriding what the default vhost is. [Virtual hosts](https://www.rabbitmq.com/virtual-hosts.html) form no hierarchy of any kind, `/` simply happens to be the default value.

URI path [encoding rules](https://www.rabbitmq.com/uri-spec.html) have a dedicated guide with examples.

For every newly created virtual host you will have to [grant permissions](http://rabbitmq.com/access-control.html) to the users applications will use to connect. We strongly recommend using a user [other than guest](https://www.rabbitmq.com/production-checklist.html) everywhere except local development.
