### ISSUE TITLE
rabbitmqadmin : properties_file option like payload_file ?

### ISSUE THREAD

**Issue by crownedgrouse** [rabbitmq/rabbitmq-management#728]
A feature is missing MHO in rabbitmqadmin : get all message properties (including headers) in a file.
Payload can be put in a file with `payload_file` option, but not properties.

`--depth` show things but only on shell output, mixed with other informations.

**Comment by michaelklishin** [comment]
`rabbitmqadmin` really wasn't meant to be used to develop consumers.

**Comment by crownedgrouse** [comment]
yes but properties are usefull to debug an invalid route. That's what I wait from an administration tool ?
