### ISSUE TITLE
Is there a way to make the complex passwords creation obligatory?

### ISSUE THREAD

**Issue by kurtulekrem** [rabbitmq/rabbitmq-management#747]
Hi guys,

Does the rabbitmq have an option or config parameter which makes the complex password creation obligatory? I mean I need to adjust passwords so that they must contain, for example, a lower case letter, an uppercase letter, a number and a symbol etc. I have tried the following config parameters in my rabbitmq.conf file but it just lets me to choose which characters are able to reside in the password and the number of characters of the password.

credential_validator.validation_backend = rabbit_credential_validator_password_regexp
credential_validator.regexp = ^[A-Za-z\d!%"'$& ()*+,-./:;<=>?@[\]^~_{|}]{8,64}

Thanks a lot.

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ.

This is [mailing list material](https://groups.google.com/forum/?pli=1#!forum/rabbitmq-users). In the future, please ask questions there. Team RabbitMQ uses GitHub for actionable work.

You would have to write your own validation backend to enforce complex passwords.

**Comment by lukebakken** [comment]
You will find this discussion to be helpful:

https://elixirforum.com/t/groups-in-regex-to-validate-password/7086/12

If you implement an entropy-based password validation backend and wish to contribute it to RabbitMQ, we would appreciate it. Thanks.

**Comment by kurtulekrem** [comment]
Thanks a lot for the response.

I have followed the discussion that you forwarded and got something. I have inserted the following two lines to rabbitmq.conf file and now the password requires the following criteria no matter what the order of the characters are.
- Must contain at least one capital letter
- Must contain at least one lowercase letter
- Must contain at least one number
- Must contain at least one special character
- The size must be greater than 8 characters

credential_validator.validation_backend = rabbit_credential_validator_password_regexp
credential_validator.regexp = ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!%"'$& *+,\-./:;<=>?@^~_|])[^\W_]{8,100}

I hope this will work for all of the RabbitMQ users.

Have a nice day.
