### ISSUE TITLE
Wrong JSON data type for empty `publish-properties` in /api/parameters/shovel

### ISSUE THREAD

**Issue by smee** [rabbitmq/rabbitmq-management#75]
If I create a dynamic shovel via pushing to `/api/parameters/shovel` with a `publish-properties` attribute like this
```
 curl -i -u guest:guest -H "content-type:application/json" -XPUT \
-d'{"value":{"dest-exchange":"amq.direct","src-queue":"test","dest-uri":"amqp://", "src-uri":"amqp://","publish-properties":{"user_id":"guest"}}}' \
http://localhost:15672/api/parameters/shovel/%2f/test1
```
I can see at `/api/parameters/shovel/%2f/test1` that the attribute `publish-properties` is a JSON object. If I instead create a queue with an empty `publish-properties` like

```
 curl -i -u guest:guest -H "content-type:application/json" -XPUT \
-d'{"value":{"dest-exchange":"amq.direct","src-queue":"test","dest-uri":"amqp://", "src-uri":"amqp://","publish-properties":{}}}' \
http://localhost:15672/api/parameters/shovel/%2f/test1
```
the data type of this field is a JSON array instead. Is it possible to either not show the property or use an empty object?

**Comment by michaelklishin** [comment]
This was fixed in several places before,
returning an empty array is possible.

**Comment by smee** [comment]
You mean only an empty array? Not an empty object?

**Comment by michaelklishin** [comment]
An empty object, sorry. The issue here is that proplists are lists in Erlang and so empty proplists are serialised as empty lists unless mochijson2 is instructed otherwise.

**Comment by michaelklishin** [comment]
This belongs to `shovel-management` but lets keep it here.

**Comment by michaelklishin** [comment]
We've evaluated this and there is an issue with Erlang JSON libraries prior to 17.x: they use lists to express what is objects in JSON. So we can't reliably tell an empty list from an empty object. In master we will switch to maps. For `3.6.x`, we will look at what we can do.

**Comment by essen** [comment]
Just sent two PRs with a proposal for a fix for this on stable. It's dirty really, and I have not run the full test suites to make sure I didn't break anything. Looking to see if that sort of fix is OK.
