### ISSUE TITLE
Operator policies updated via /api/defintions are not applied causing queue to crash

### ISSUE THREAD

**Issue by yakuninv** [rabbitmq/rabbitmq-management#751]
Hello, we are experiencing problem with applying operator policies via /api/definitions endpoint.

We use RabbitMQ 3.7.19 with Erlang 21.3.8.9, hosted in Oracle Linux 7.6

We have queue created, and we want to apply operator policy setting message ttl for this queue.
We generate json file containg operator policy definitions, and pass it to /api/definitions endpoint using curl. Endpoint is responding 204 and we are able to see newly created policies in Admin|Policies view in Managment console. After some time (usually few seconds) we observe that queue that is affected by newly uploaded policy crashes. Once policies are deleted sutuation recovers. Everything works fine if we use UI and create policies manually.

I am uploading crash reprt below
[20191112-crash-report.txt](https://github.com/rabbitmq/rabbitmq-management/files/3836151/20191112-crash-report.txt)

Please let me know if you need more details.

With warm regards,
Sla

**Comment by lukebakken** [comment]
Please provide the necessary information for us to reproduce this:

* The queue definition you're using
* The JSON file containing policy definitions

Without the above, we would have to guess which is not productive. Thank you!

**Comment by michaelklishin** [comment]
The function that fails with a `function_clause` is [rabbit_policy:effective_definition0/2`](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_policy.erl#L83), so it's an edge case in definition combination or how definitions are restored from the JSON file.

How can we reproduce?

**Comment by michaelklishin** [comment]
We can address this as part of the ongoing work on #749 if an example definitions file is provided.

**Comment by yakuninv** [comment]
Hi sure please find below.

In the zip you will find following:

1. inital.json - this initial state of the cluster before operator policy is applied. It contains few users, some global policies and single queue. Snapshot was taken by GET on api/definitions

2. operator-policy.json is the policy we are going to apply by calling somthing like 
`curl --silent --insecure -u rabbitmq_admin:rabbitmq_admin -X POST -H 'Content-Type: application/json' -w "%{http_code}" -d @operator-policy.json https://harabbit01-hosel.cz.infra:15672/api/definitions`

3. crash-report.txt is report generated as a result of operator policy appication from step above.

You can model it as following: 
Apply inital.json to empty cluster.
Apply policy.
Wait 30-40 seconds.
Ensure the issue exists

Thanks
Sla

[20191112-issue-751-test-case.zip](https://github.com/rabbitmq/rabbitmq-management/files/3836711/20191112-issue-751-test-case.zip)

**Comment by michaelklishin** [comment]
Thanks, I will try to reproduce as part of finishing #750.

**Comment by michaelklishin** [comment]
I managed to reproduce.

**Comment by michaelklishin** [comment]
Addressed as part of #750.

**Comment by yakuninv** [comment]
@michaelklishin just small question, what version will it go? Will it be part of 3.7.x or it will likely go to 3.8.x?
