### ISSUE TITLE
Queue page no longer shows consumers

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#758]
> Hi all, I have a question about the RabbitMQ Management tool, we have just upgraded from 3.7.15 to 3.8.2 and noticed on the queue page there is no longer any collapsible block that shows consumers for the queue, was this removed or is it now a setting which needs to be enabled somewhere?

Reported [here](https://rabbitmq.slack.com/archives/C1EDN83PA/p1576245885005200)

**Comment by nitrag** [comment]
Anxiously looking forward to the 3.8.3 release to resolve this! Thanks
