### ISSUE TITLE
Security : auth token in "Download broker definition" Url

### ISSUE THREAD

**Issue by chrisfb** [rabbitmq/rabbitmq-management#770]
Hi,

From RabbitMQ Administration GUI, one can click on the "Download broker definition" button in order to retrieve the cluster configuration, including login/ hashed passwords, exchange and queue names, etc.

Clicking on the button leeds to the following request from the broker : 
http(s)://<node_name>:<node_port>/api/definitions?download=<json_conf_file_name>&auth=<auth_token>

When the connection is SSL encrypted via HTTPS, <auth_token> is not visible by an attacker. But should the browser navigate to any http page right after the download, the http referer header field could display the whole url including the auth token. Hence the attacker would be able to download the broker definition using this url, without any other cookie or https header authentication information.

General solution to this and similar issues is to remove auth token from url, and use for instance cookie base authentication.

Ideal solution would be to patch RabbitMQ admin GUI code to :
- not provide auth token in url
- only rely on cookie or any http header based authentication solution

Is there any way to completely disable the use of auth token in url as a way of authenticating the request ?

Please find below version information. 

* RabbitMQ version : 3.7.11
* Erlang version : 21.0.9
* RabbitMQ plugin information via `rabbitmq-plugins list` : 
[E*] rabbitmq_federation               3.7.11
[E*] rabbitmq_federation_management    3.7.11
[E*] rabbitmq_jms_topic_exchange       3.7.11
[E*] rabbitmq_management               3.7.11
[e*] rabbitmq_management_agent         3.7.11
[E*] rabbitmq_shovel                   3.7.11
[E*] rabbitmq_shovel_management        3.7.11
[e*] rabbitmq_web_dispatch             3.7.11

 * Browser and its version : Chrome Version 70
 * What management UI page was used (if applicable) : "Overview"

Best regards,

Christian

**Comment by michaelklishin** [comment]
If you care about security, consider directing your security-related ideas to a dedicated responsible disclosure address (`security` at RabbitMQ domain) in the future.

The solution is to use HTTPS. We also introduced OAuth 2 support in 3.8 which management UI supports. If there is a way to pass such values on the form in question we'd be interested in hearing it but we haven't found one. @dcorbacho do you remember what was the limitation?

**Comment by chrisfb** [comment]
Michael,

Acknowledged. Will continue this discussion in a thread mail (you are in CC).

Cheers,

Christian
