### ISSUE TITLE
management UI ignores path_prefix when loading JS and CSS assets

### ISSUE THREAD

**Issue by izenk** [rabbitmq/rabbitmq-management#771]
* RabbitMQ version 3.7.5-1
* Erlang version1:20.3-1
* Operating system, version, and patch level Ubuntu 16.04.3

Issue is related to Management UI
```
rabbitmqctl environment | grep -C 3 path
      {listener,[{port,15672}]},
      {load_definitions,none},
      {management_db_cache_multiplier,5},
      {path_prefix,"/rabbitmq"},
      {process_stats_gc_timeout,300000},
      {stats_event_max_backlog,250}]},
```
path_prefix is configured, but ui does not work.
```
curl 127.0.0.1:15672 -v -L

* Rebuilt URL to: 127.0.0.1:15672/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 15672 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:15672
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< content-length: 0
< date: Tue, 11 Feb 2020 10:15:06 GMT
< location: /rabbitmq/
< server: Cowboy
<
* Connection #0 to host 127.0.0.1 left intact
* Issue another request to this URL: 'http://127.0.0.1:15672/rabbitmq/'
* Found bundle for host 127.0.0.1: 0x55b1f50decf0 [can pipeline]
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 15672 (#0)
> GET /rabbitmq/ HTTP/1.1
> Host: 127.0.0.1:15672
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 1391
< content-type: text/html
< date: Tue, 11 Feb 2020 10:15:06 GMT
< etag: "3077839945"
< last-modified: Tue, 11 Feb 2020 09:46:07 GMT
< server: Cowboy
<
<!doctype html>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<html>
  <head>
    <title>RabbitMQ Management</title>
    <script src="js/ejs-1.0.min.js" type="text/javascript"></script>
    <script src="js/jquery-1.12.4.min.js" type="text/javascript"></script>
    <script src="js/jquery.flot-0.8.1.min.js" type="text/javascript"></script>
    <script src="js/jquery.flot-0.8.1.time.min.js" type="text/javascript"></script>
    <script src="js/sammy-0.7.6.min.js" type="text/javascript"></script>
    <script src="js/json2-2016.10.28.js" type="text/javascript"></script>
    <script src="js/base64.js" type="text/javascript"></script>
    <script src="js/global.js" type="text/javascript"></script>
    <script src="js/main.js" type="text/javascript"></script>
    <script src="js/prefs.js" type="text/javascript"></script>
    <script src="js/formatters.js" type="text/javascript"></script>
    <script src="js/charts.js" type="text/javascript"></script>

    <link href="css/main.css" rel="stylesheet" type="text/css"/>
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon"/>

<!--[if lte IE 8]>
    <script src="js/excanvas.min.js" type="text/javascript"></script>
    <link href="css/evil.css" rel="stylesheet" type="text/css"/>
<![endif]-->
  </head>
  <body>
    <div id="outer"></div>
    <div id="debug"></div>
    <div id="scratch"></div>
  </body>
</html>
```
As shown in curl output, despite the request was redirected to path_prefix, src attributes contain paths without prefix, e.g. "js/charts.js" - this leads to situation when UI trying to open, but browser gets 404

<img width="1434" alt="Screen Shot 2020-02-11 at 17 21 37" src="https://user-images.githubusercontent.com/6417697/74229127-592bdf00-4cf4-11ea-8479-b2b589842793.png">

**Comment by michaelklishin** [comment]
I cannot reproduce with 3.7.22.

<img width="1467" alt="Screenshot 2020-02-11 at 16 15 29" src="https://user-images.githubusercontent.com/1090/74239863-c8e89c80-4ce9-11ea-8184-71e800fe1b60.png">

**Comment by michaelklishin** [comment]
You are [18 patch releases behind](https://www.rabbitmq.com/changelog.html) even in the 3.7 series. Consider [upgrading](https://www.rabbitmq.com/upgrade.html).

**Comment by michaelklishin** [comment]
`3.7.5` was released in May 2018. There were several relevant changes to prefix handling and routes in at least

 * https://github.com/rabbitmq/rabbitmq-management/commit/68bb0938260a8cb4ee4bc0d7ad29e8d305aa01d3#diff-05f60cc1b34c60ce1135034f7239c647
 * https://github.com/rabbitmq/rabbitmq-management/commit/8f356084a33c0015f974b1d425f5edb81a10fa5a#diff-05f60cc1b34c60ce1135034f7239c647 (according to GitHub this is a part of the `v3.7.5` tag but why is it from several months later in history, I'm not sure)
 * https://github.com/rabbitmq/rabbitmq-management/commit/24b28d311ad98231584f0656224b965a42001098#diff-05f60cc1b34c60ce1135034f7239c647

**Comment by izenk** [comment]
thanks, will try to upgrade. For now closing this issue
