### ISSUE TITLE
RMQ Admin: Transient error in viewing queues on UI

### ISSUE THREAD

**Issue by lbernick** [rabbitmq/rabbitmq-management#772]
When clicking on a specific queue in the queues page on the UI or trying to navigate to the URL for a queue, the following error frequently appears in the browser instead of the desired page:

Traceback:
`ReferenceError: highlight_extra_whitespace is not defined ReferenceError: highlight_extra_whitespace is not defined at Array.process (eval at compile (https://<hostname>/js/ejs-1.0.min.js:1:6654), :1:180) at EJS.render (https://<hostname>/js/ejs-1.0.min.js:1:1885) at format (https://<hostname>/js/main.js:1086:21) at https://<hostname>/js/main.js:444:24 at with_reqs (https://<hostname>/js/main.js:1068:9) at https://<hostname>/js/main.js:1064:17 at XMLHttpRequest.req.onreadystatechange (https://<hostname>/js/main.js:1144:17)`

Browser: Chrome 79.0.3945.130
OS: MacOS Mojave version 10.14.6

RabbitMQ Version: Using 3.7 image from Dockerhub (https://github.com/docker-library/rabbitmq/blob/2ca391613d0c76bf0da98ca609b858f50e6140f4/3.7/ubuntu/Dockerfile). Uses Erlang version 22.2.6.

rabbitmq-plugins list:
```
root@rabbitmq-0:/# rabbitmq-plugins list
Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@<hostname>
 |/
[  ] rabbitmq_amqp1_0                  3.7.24
[  ] rabbitmq_auth_backend_cache       3.7.24
[  ] rabbitmq_auth_backend_http        3.7.24
[  ] rabbitmq_auth_backend_ldap        3.7.24
[  ] rabbitmq_auth_mechanism_ssl       3.7.24
[  ] rabbitmq_consistent_hash_exchange 3.7.24
[  ] rabbitmq_event_exchange           3.7.24
[  ] rabbitmq_federation               3.7.24
[  ] rabbitmq_federation_management    3.7.24
[  ] rabbitmq_jms_topic_exchange       3.7.24
[E*] rabbitmq_management               3.7.24
[e*] rabbitmq_management_agent         3.7.24
[  ] rabbitmq_mqtt                     3.7.24
[  ] rabbitmq_peer_discovery_aws       3.7.24
[e*] rabbitmq_peer_discovery_common    3.7.24
[  ] rabbitmq_peer_discovery_consul    3.7.24
[  ] rabbitmq_peer_discovery_etcd      3.7.24
[E*] rabbitmq_peer_discovery_k8s       3.7.24
[  ] rabbitmq_random_exchange          3.7.24
[  ] rabbitmq_recent_history_exchange  3.7.24
[  ] rabbitmq_sharding                 3.7.24
[  ] rabbitmq_shovel                   3.7.24
[  ] rabbitmq_shovel_management        3.7.24
[  ] rabbitmq_stomp                    3.7.24
[  ] rabbitmq_top                      3.7.24
[  ] rabbitmq_tracing                  3.7.24
[  ] rabbitmq_trust_store              3.7.24
[e*] rabbitmq_web_dispatch             3.7.24
[  ] rabbitmq_web_mqtt                 3.7.24
[  ] rabbitmq_web_mqtt_examples        3.7.24
[  ] rabbitmq_web_stomp                3.7.24
[  ] rabbitmq_web_stomp_examples       3.7.24
```

`curl https:/<host>/\#/queues/<vhost>/<queue name>` returns the source html just fine.

JS console output: 
```
Uncaught error: ReferenceError: highlight_extra_whitespace is not defined
main.js:1090 Stack: ReferenceError: highlight_extra_whitespace is not defined
    at Array.process (eval at compile (https://<hostname>/js/ejs-1.0.min.js:1:6654), <anonymous>:1:180)
    at EJS.render (https://<hostname>/js/ejs-1.0.min.js:1:1885)
    at format (https://<hostname>/js/main.js:1086:21)
    at https://<hostname>/js/main.js:444:24
    at with_reqs (https://<hostname>/js/main.js:1068:9)
    at https://<hostname>/js/main.js:1064:17
    at XMLHttpRequest.req.onreadystatechange (https://<hostname>/js/main.js:1144:17)
main.js:844 Uncaught TypeError: input.size is not a function
    at HTMLSelectElement.<anonymous> (main.js:844)
    at Function.each (jquery-3.4.1.min.js:2)
    at k.fn.init.each (jquery-3.4.1.min.js:2)
    at update_multifield (main.js:827)
    at HTMLDivElement.<anonymous> (main.js:818)
    at Function.each (jquery-3.4.1.min.js:2)
    at k.fn.init.each (jquery-3.4.1.min.js:2)
    at update_multifields (main.js:817)
    at postprocess (main.js:689)
    at main.js:282
```  

Please let me know if there's any other information that would be helpful here.

**Comment by lukebakken** [comment]
* I downloaded RabbitMQ 3.7.24 from here - https://github.com/rabbitmq/rabbitmq-server/releases/v3.7.24
* I enabled the `rabbitmq_management` plugin
* I started RabbitMQ
* I then created a queue and navigated to the queue overview page. No errors were visible on the screen nor in the Chrome dev tools console

I suspect the issue is with the [docker image](https://github.com/docker-library/rabbitmq/issues) or is specific to your environment. The RabbitMQ engineering team does not maintain the docker image - perhaps open an issue in that repository?

**Comment by michaelklishin** [comment]
`highlight_extra_whitespace` was [introduced](https://github.com/rabbitmq/rabbitmq-management/pull/721) in `3.7.17`. If you have accessed management UI in an earlier version, you must clear browser cache when upgrading. This is [mentioned in the Upgrade guide](https://www.rabbitmq.com/upgrade.html#rabbitmq-plugins-compatibility).

**Comment by lbernick** [comment]
Thanks for the quick response! Clearing my browser cache resolved this issue for me. I'll update this issue if this error pops up again and isn't resolved by clearing the cache, or if we find a reliable way to reproduce the issue.
