### ISSUE TITLE
Permissions required for bindings from api too high

### ISSUE THREAD

**Issue by artandor** [rabbitmq/rabbitmq-management#773]
Creating a binding through management API requires the user to have config, write and read permissions on the vhost. I think this is too high because configurating a binding seems to be a CONFIG action and not a read or write one.

This requirement remove the possibility to create a "configurator" user that has the specific purpose of configuring the exchanges and queues but not publish or read.

## Infos
Rabbitmq 3.7.23
Erlang 20.3

I think the requirement to make this call should be config permissions on the targeted vhost :
`curl -u configurator:mypass -XPOST http://localhost:15672/api/bindings/testvhost/e/test_exch/q/myqueue -d '{"routing_key":"custombinding"}'`

**Comment by michaelklishin** [comment]
Binding requires a [write permission on target queue and read permission on the source exchange](https://www.rabbitmq.com/access-control.html). If you don't have those, chances are you wouldn't be able to set up the topology anyway. Separate "configurator" users are not a common scenario and they do not sit well with the philosophy of the original protocol, which is: applications define their own topology, not a dedicated "configurator".
