### ISSUE TITLE
Management Database Grows in Size In Seconds

### ISSUE THREAD

**Issue by gsogol** [rabbitmq/rabbitmq-management#784]
Running a cluster of 3 nodes. All clients/browsers are communicating via a stomp plugin. All queues are set to autodelete. In the overview tab, you can see around 2000 connections and queues. The main issue is that the management database grows to GBs and slows the whole cluster down to the point that we can't even browse the management UI (super slow) and connections are erring out.

Here is what we see:
Overview tab --> https://drive.google.com/file/d/1VzzqE4u90vxvt3ygIgrBn0JJndK8m2Es/view?usp=sharing

Memory usage --> https://drive.google.com/file/d/1bqeRggCGk-zVQbMjhpbpKjkTDHuZHMaW/view?usp=sharing

`rabbitmqctl eval 'rabbit_mgmt_storage:reset_all().'` --> does not reset the management db.

`rabbitmqctl eval 'supervisor2:terminate_child(rabbit_mgmt_sup_sup, rabbit_mgmt_sup), rabbit_mgmt_sup_sup:start_child().'` --> does reset the management database but it quickly goes back to 3-10 GB

rabbitmq.config (no policies are configured at all) --> 
`
[
{rabbit,
  [
    {loopback_users, []}
  ]},
{rabbitmq_management,
  [
    {rates_mode, none}
  ]}
]`

RabbitMQ version: 3.7.18
Erlang version 22.1
RabbitMQ plugin information via `rabbitmq-plugins list` -->
```
[  ] rabbitmq_amqp1_0                  3.7.18
[  ] rabbitmq_auth_backend_cache       3.7.18
[  ] rabbitmq_auth_backend_http        3.7.18
[  ] rabbitmq_auth_backend_ldap        3.7.18
[  ] rabbitmq_auth_mechanism_ssl       3.7.18
[  ] rabbitmq_consistent_hash_exchange 3.7.18
[  ] rabbitmq_event_exchange           3.7.18
[  ] rabbitmq_federation               3.7.18
[  ] rabbitmq_federation_management    3.7.18
[  ] rabbitmq_jms_topic_exchange       3.7.18
[E*] rabbitmq_management               3.7.18
[e*] rabbitmq_management_agent         3.7.18
[  ] rabbitmq_mqtt                     3.7.18
[  ] rabbitmq_peer_discovery_aws       3.7.18
[  ] rabbitmq_peer_discovery_common    3.7.18
[  ] rabbitmq_peer_discovery_consul    3.7.18
[  ] rabbitmq_peer_discovery_etcd      3.7.18
[  ] rabbitmq_peer_discovery_k8s       3.7.18
[  ] rabbitmq_random_exchange          3.7.18
[  ] rabbitmq_recent_history_exchange  3.7.18
[  ] rabbitmq_sharding                 3.7.18
[  ] rabbitmq_shovel                   3.7.18
[  ] rabbitmq_shovel_management        3.7.18
[E*] rabbitmq_stomp                    3.7.18
[  ] rabbitmq_top                      3.7.18
[E*] rabbitmq_tracing                  3.7.18
[  ] rabbitmq_trust_store              3.7.18
[e*] rabbitmq_web_dispatch             3.7.18
[  ] rabbitmq_web_mqtt                 3.7.18
[  ] rabbitmq_web_mqtt_examples        3.7.18
[E*] rabbitmq_web_stomp                3.7.18
[  ] rabbitmq_web_stomp_examples       3.7.18`
```

Running the `rabbitmq-collect-env`--> https://drive.google.com/file/d/1QgYNaVxwmt52OmwOF9OBwNqub8KBVcRQ/view?usp=sharing

We stood up another 3 node cluster with similar as above running load tests but could not recreate the management db issue like the cluster above running in prod. What can we do to figure out what is happening?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
