### ISSUE TITLE
rabbitmqadmin imports non-ASCII character in queue name as �

### ISSUE THREAD

**Issue by loop-evgeny** [rabbitmq/rabbitmq-management#785]
Ubuntu 18.04 x64, RabbitMQ 3.7.24, Erlang 22.2

Using Python 3.6.9 now, I successfully exported server configuration using `rabbtimqadmin export` from one server and imported it into another using `rabbtimqadmin import`, however the character "ö" in a queue name became "�" on the new server. This is what's shown in the management UI and also if I export the new server's configuration to JSON again.

**Comment by lukebakken** [comment]
Thanks for using RabbitMQ. To speed up a fix, please attach a complete definitions file that reproduces this issue. Thanks!

**Comment by michaelklishin** [comment]
@lukebakken Python 2 is EOL. I suggest that we close this.

**Comment by loop-evgeny** [comment]
Here you go: [nonascii.json.txt](https://github.com/rabbitmq/rabbitmq-management/files/4313476/nonascii.json.txt)

This is happening with Python 3, not Python 2.

**Comment by lukebakken** [comment]
@loop-evgeny thanks for the file.

**Comment by loop-evgeny** [comment]
In fact, when importing this into the same server the old queue (with the ö) remains and a new one is added.

**Comment by lukebakken** [comment]
@loop-evgeny if you have a second to test #793 with some different queue names exhibiting this issue we would appreciate it. Thanks.

**Comment by loop-evgeny** [comment]
Thanks for fixing this quickly! I don't actually have another queue name with non-ASCII characters and have since renamed that one (to work around this).

**Comment by michaelklishin** [comment]
@loop-evgeny at the very least you can use your own provided definition file to try it in a dev or QA environment ;)
