### ISSUE TITLE
rabbitmqadmin export fails on Python 2.7 with UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by loop-evgeny** [rabbitmq/rabbitmq-management#786]
Ubuntu 18.04 x64, RabbitMQ 3.7.24, Erlang 22.2
/usr/bin/python is Python 2.7.17 on this machine

Trying to export configuration data using Python 2.7 fails:

```
# rabbitmqadmin --host MYSERVER --user USER --password PASSWORD export backup.json
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 1150, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 494, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 675, in invoke_export
    f.write(definitions)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 15280: ordinal not in range(128)
```

The character at that offset is ö (part of a queue name).

This works using Python 3.6.9 (`python3 rabbitmqadmin ...`) - the configuration is exported successfully.

**Comment by michaelklishin** [comment]
@lukebakken Python 2 is EOL. I suggest that we close this.

**Comment by loop-evgeny** [comment]
EOL or not, this is a bad user experience. An easy "fix" would be to change "!#/usr/bin/env python" to "!#/usr/bin/env python3" in rabbitmqadmin.

**Comment by lukebakken** [comment]
I've had to address similar issues in Pika so this may be easy to address.

**Comment by michaelklishin** [comment]
@loop-evgeny EOL means EOL. If you want Python 2 support you can maintain your own fork, `rabbitmqadmin` is a fairly small standalone zero dependency script.

**Comment by lukebakken** [comment]
Ah I didn't realize 2.7 is dead dead dead. I'll update `rabbitmqadmin` to use `python3`

**Comment by lukebakken** [comment]
@michaelklishin addressed this in https://github.com/rabbitmq/rabbitmq-management/commit/700203040f61c35d5eaee99b8033e1dc9552903f
