### ISSUE TITLE
When stats are disabled, the queue page throws a TypeError

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-management#787]
Given the following rabbitmq.conf:

```
management.disable_stats = true
```

The queue page throws the following error:

```
main.js:1139 Uncaught error: TypeError: Cannot read property 'length' of undefined
main.js:1140 Stack: TypeError: Cannot read property 'length' of undefined
    at Object.process (eval at compile (http://localhost:15672/js/ejs-1.0.min.js:1:6654), <anonymous>:1:140)
    at EJS.render (http://localhost:15672/js/ejs-1.0.min.js:1:1885)
    at format (http://localhost:15672/js/main.js:1136:21)
    at Array.process (eval at compile (http://localhost:15672/js/ejs-1.0.min.js:1:6654), <anonymous>:254:37)
    at EJS.render (http://localhost:15672/js/ejs-1.0.min.js:1:1885)
    at format (http://localhost:15672/js/main.js:1136:21)
    at http://localhost:15672/js/main.js:484:24
    at with_reqs (http://localhost:15672/js/main.js:1118:9)
    at http://localhost:15672/js/main.js:1114:17
    at XMLHttpRequest.req.onreadystatechange (http://localhost:15672/js/main.js:1198:17)
```

On next refresh, it throws the same error again. This is what the final queue page looks like, after 2 errors have been thrown:

![image](https://user-images.githubusercontent.com/3342/76336944-a187ee00-62ee-11ea-942a-ab82935d8c76.png)

This can be reproduced in `master` by running:

```
make run-broker RABBITMQ_CONFIG_FILE=$PWD/rabbitmq.conf
```

The same happens for a queue of type quorum.

We should back-port this fix to 3.8.x as well.

**Comment by dcorbacho** [comment]
@gerhard I got a different error, where `consumers` are undefined. I fixed that, let me know if you still have issues. Something else might have escaped the `if` condition.

**Comment by gerhard** [comment]
Thanks, looking at this now. I didn't have any consumers in my test, but will try that use-case as well.

**Comment by dcorbacho** [comment]
You don't need consumers, it's the consumers entry in the UI that tried to show them (and we don't return them when stats are disabled)

**Comment by michaelklishin** [comment]
#789 was reverted because it reintroduces #758.

**Comment by gerhard** [comment]
Indeed, when stats are **not** disabled, the consumers do not show:

![Screenshot 2020-03-11 at 17 40 44](https://user-images.githubusercontent.com/3342/76446980-cb5d1580-63bf-11ea-8a1e-28e5090f8118.png)

![Screenshot 2020-03-11 at 17 41 51](https://user-images.githubusercontent.com/3342/76446973-c8622500-63bf-11ea-9ac2-75d006987f6f.png)

We need a different fix.
