### ISSUE TITLE
Missing historical charts data

### ISSUE THREAD

**Issue by clain23** [rabbitmq/rabbitmq-management#79]
We are using RabbitMQ 3.5.3, Erlang 17.5 on Windows 2012R2.

Historical charts for the same queue are showing different numbers:

At 12:13 it says it were 27k messages at 10:00 http://content.screencast.com/users/timramone/folders/Jing/media/9f717015-502f-42bc-8841-17f83b1a71af/2015-10-23_1213.png

But at 14:26 it says there were 50k messages at 10:00
http://content.screencast.com/users/timramone/folders/Jing/media/d7a6e48e-4ddc-4de4-8ef6-e689083ac45b/2015-10-23_1426.png

It seems that queue graphs are showing data only for last hour. Message rates are also showing only last hour http://screencast.com/t/NkmdtVFh2i

**Comment by michaelklishin** [comment]
Stats collector can drop some data when it gets overloaded, by design. See #41.

**Comment by michaelklishin** [comment]
…plus [data retention periods are configurable](http://rabbitmq.com/management.html). Stats database is not meant to be used for long term metrics storage: treat it as a transient data store (which it is) and store data in something like collectd for long term retention.
