### ISSUE TITLE
API returns incomplete queue details

### ISSUE THREAD

**Issue by RodolfoSGomez** [rabbitmq/rabbitmq-management#795]
The API returns incomplete queue details when queried too soon after the queue has been created.

This reproduces on Ubuntu 18.04
- 3.6.10 Erlang  20.2.2
- 3.8.2 Erlang 22.2.8
(but it is OK on 3.5.7 Erlang 18.3)

A script to reproduce it on localhost/guest (first arg is the queue name, second is the sleep time)

```
printf "\nCreating queue $1\n"
curl -i -u guest:guest -H "content-type:application/json" -XPUT http://localhost:15672/api/queues/%2f/$1

printf "\nWaiting for $2\n"
sleep $2

printf "\nGetting info for queue $1\n"
curl -i -u guest:guest -XGET http://localhost:15672/api/queues/%2f/$1

printf "\nDeleting queue $1\n"
curl -i -u guest:guest -H "content-type:application/json" -XDELETE http://localhost:15672/api/queues/%2f/$1
```

Here's the output where you can see the API returned only partial info (no sleep time, removed irrelevant lines)

```
$ ./queue_info my_queue 0s

Creating queue my_queue
HTTP/1.1 201 Created
date: Mon, 23 Mar 2020 09:07:13 GMT

Waiting for 0s

Getting info for queue my_queue
HTTP/1.1 200 OK
date: Mon, 23 Mar 2020 09:07:13 GMT

{"garbage_collection":{"max_heap_size":-1,"min_bin_vheap_size":-1,"min_heap_size":-1,"fullsweep_after":-1,"minor_gcs":-1},"consumer_details":[],"arguments":{},"auto_delete":false,"deliveries":[],"durable":false,"exclusive":false,"incoming":[],"name":"my_queue","node":"rabbit@localhost","type":"classic","vhost":"/"}

Deleting queue my_queue
```

And here's the full info for the queue if we wait 3s after we create it

```
$ ./queue_info my_queue 3s

Creating queue my_queue
HTTP/1.1 201 Created
date: Mon, 23 Mar 2020 09:16:59 GMT

Waiting for 3s

Getting info for queue my_queue
HTTP/1.1 200 OK
date: Mon, 23 Mar 2020 09:17:02 GMT

{"consumer_details":[],"arguments":{},"auto_delete":false,"backing_queue_status":{"avg_ack_egress_rate":0.0,"avg_ack_ingress_rate":0.0,"avg_egress_rate":0.0,"avg_ingress_rate":0.0,"delta":["delta","undefined",0,0,"undefined"],"len":0,"mode":"default","next_seq_id":0,"q1":0,"q2":0,"q3":0,"q4":0,"target_ram_count":"infinity"},"consumer_utilisation":null,"consumers":0,"deliveries":[],"durable":false,"effective_policy_definition":{},"exclusive":false,"exclusive_consumer_tag":null,"garbage_collection":{"fullsweep_after":65535,"max_heap_size":0,"min_bin_vheap_size":46422,"min_heap_size":233,"minor_gcs":2},"head_message_timestamp":null,"incoming":[],"memory":42668,"message_bytes":0,"message_bytes_paged_out":0,"message_bytes_persistent":0,"message_bytes_ram":0,"message_bytes_ready":0,"message_bytes_unacknowledged":0,"messages":0,"messages_details":{"rate":0.0},"messages_paged_out":0,"messages_persistent":0,"messages_ram":0,"messages_ready":0,"messages_ready_details":{"rate":0.0},"messages_ready_ram":0,"messages_unacknowledged":0,"messages_unacknowledged_details":{"rate":0.0},"messages_unacknowledged_ram":0,"name":"my_queue","node":"rabbit@localhost","operator_policy":null,"policy":null,"recoverable_slaves":null,"reductions":3880,"reductions_details":{"rate":0.0},"single_active_consumer_tag":null,"state":"running","type":"classic","vhost":"/"}

Deleting queue my_queue
```

Note that, there's still an open issue very much like this in https://github.com/rabbitmq/rabbitmq-management/issues/456. But looks like in that case a node restart fixes it. That's not the case here.

I've checked the rabbitmq logs but they don't show anything relevant.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin is based on a stats database that is updated periodically (5s by default) by stats-emitting entities. It, therefore, does not offer strong consistency as observed by clients. CLI tools go "straight to the source" and would list what internal tables and such contain.
