### ISSUE TITLE
Timestamps on x-axis of charts not in local time

### ISSUE THREAD

**Issue by dgritsko** [rabbitmq/rabbitmq-management#8]
The charts introduced in RabbitMQ 3.1.0 feature timestamps along the x-axis of all graphs. However, the times displayed are in UTC:

![timestamps](https://f.cloud.github.com/assets/526546/705467/60b8f192-ddd7-11e2-9a5c-943e43337a18.png)

This is inconsistent with the "Last update" displayed at the bottom of the page, which is displayed in local time. I would expect these times to be consistent with one another:

![last_update](https://f.cloud.github.com/assets/526546/705459/329f96b2-ddd7-11e2-8839-fd3b40e38383.png)

**Comment by michaelklishin** [comment]
Is this still relevant?

**Comment by blackside** [comment]
Not since I upgraded to 3.3.3 :)

**Comment by simonmacmullen** [comment]
To close the loop, this was bug 25676 fixed in 3.2.0.
