### ISSUE TITLE
Wrong terminology for binding key in the UI

### ISSUE THREAD

**Issue by blubberdiblub** [rabbitmq/rabbitmq-management#80]
In the UI (when you use topic exchanges, go to **Exchanges**, click on a topic exchange and open the **Bindings**), the *binding key* is called *Routing Key*. That's really confusing and contributes to proliferation of wrong assumptions about how message routing works.

The *routing key* is the piece of metadata that accompanies a message  and is strictly composed of words separated by periods. In contrast, the *binding key* is associated with a binding and functions as a pattern against which a message's routing key is matched and as such allows some kinds of wildcards. This differentiation is important and should be reflected with correct labels in the UI.

**Comment by michaelklishin** [comment]
Routing key is what things are called in the protocol. Binding key is very rare to come by. Sorry but the who are used interchangeably and this has been the case for some 8 years now.

**Comment by xylesoft** [comment]
I have to agree with **blubberdiblub** here, the idea that the terms are interchangeable is a very weak argument, using "this has been the case for some 8 years now" is not a reasoning to this concern. A routing key has a clear distinction in that it's a **identifier** where as the binding key is an expression which is used to by bindings to the route messages by a routing key. Those two concepts are very clearly distinct and should be respected to clarify the differences.

**Comment by michaelklishin** [comment]
@xylesoft I'd be all for making this change if we could erase some 9 years worth of interchangeable term use off the face of the Internet.
