### ISSUE TITLE
TLS options for rabbit application supersede TLS options for rabbitmq_management

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#800]
As reported [in this discussion](https://groups.google.com/d/topic/rabbitmq-users/YnqEbaFNv-c/discussion).

To reproduce:

* Create two sets of certs using [`tls-gen`](https://github.com/michaelklishin/tls-gen):
    ```
    cd basic
    make CN=server-a
    mv result server-a-certs
    make CN=server-b
    mv result server-b-certs
    ```
* Edit `hosts` file so that `server-a` and `server-b` resolve to your RabbitMQ host name
* Use the following conf, with adjusted paths for certs: [rabbitmq.conf.txt](https://github.com/rabbitmq/rabbitmq-management/files/4478282/rabbitmq.conf.txt)
* Start RabbitMQ
* Run the following command and you will see `server-a` cert presented for port `15671` and the check will fail:
    ```
    $ openssl s_client -host server-b -port 15671 -CAfile server-b/ca_certificate.pem -cert server-b/client_certificate.pem -key server-b/client_key.pem -servername server-b
    CONNECTED(00000003)
    depth=1 CN = TLSGenSelfSignedtRootCA, L = $$$$
    verify error:num=19:self signed certificate in certificate chain
    verify return:1
    depth=1 CN = TLSGenSelfSignedtRootCA, L = $$$$
    verify return:1
    depth=0 CN = server-a, O = server
    verify return:1
    140162307126400:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1544:SSL alert number 48
    ---
    Certificate chain
     0 s:CN = server-a, O = server
       i:CN = TLSGenSelfSignedtRootCA, L = $$$$
     1 s:CN = TLSGenSelfSignedtRootCA, L = $$$$
       i:CN = TLSGenSelfSignedtRootCA, L = $$$$
    ```

**Comment by lukebakken** [comment]
PRs:

* #801
* https://github.com/rabbitmq/rabbitmq-prometheus/pull/35

**Comment by nick-george** [comment]
This is my first time looking at Erlang :open_mouth:

**Comment by lukebakken** [comment]
@nick-george once you get used to it you realize how simple the syntax is, and how amazing the VM is for concurrent applications and distributed apps. Highly recommended.
