### ISSUE TITLE
.rabbitmqadmin.conf settings take precedence over CLI switches

### ISSUE THREAD

**Issue by HariSekhon** [rabbitmq/rabbitmq-management#804]
I've found that the `rabbitmqadmin` command was not respecting the `--host` switch on the command line and instead was using the `[default]` `hostname` field's value, leading to confusion over socket timeouts.

Usually explicit command line switches should take priority over implicit values like the default values of a configuration file, or environment variables.

Example configuration file:

``` ini
[default]
hostname = unreachable-host
port = 15672
```

and an example invocation:

``` shell
./bin/rabbitmqadmin -c /path/to/configs/issues/rabbitmqadmin.management-804.conf --host localhost list users
```

**Comment by michaelklishin** [comment]
I updated the issue with a set of steps to reproduce with the latest `rabbitmqadmin`.

**Comment by HariSekhon** [comment]
@michaelklishin thanks

**Comment by michaelklishin** [comment]
Oops, I thought I reopened it.

I have a PR almost ready but unfortunately, it introduces a subtle regression that was caught by the test suite. The interaction between CLI switches, config file values, and defaults is pretty involved. Still investigating.

**Comment by michaelklishin** [comment]
@HariSekhon #805 is ready for your review :)

**Comment by michaelklishin** [comment]
As with most `rabbitmqadmin` changes, since it's a zero dependency Python script it can be [downloaded from GitHub](https://github.com/rabbitmq/rabbitmq-management/blob/v3.8.x/bin/rabbitmqadmin) and used immediately with existing releases, no need to wait for RabbitMQ `3.8.4` to ship.
