### ISSUE TITLE
UI: Automatically redirect back to home for unauthorized users

### ISSUE THREAD

**Issue by oxr463** [rabbitmq/rabbitmq-management#808]
Location: /#/users

Reproduction Steps:
1. Login as non-administrative user, (tag can be set to Monitoring or lower).
2. Navigate to the location provided above.

Current Behavior:

> Not administrator user

Desired Behavior

After clicking close, the page should redirect back to home.

**Comment by oxr463** [comment]
![rabbitmq_management_users](https://user-images.githubusercontent.com/43783393/80247689-79551400-863c-11ea-9ca7-21c2e6915ec6.png)

**Comment by oxr463** [comment]
Source: https://github.com/rabbitmq/rabbitmq-management/blob/master/priv/www/js/tmpl/users.ejs

**Comment by michaelklishin** [comment]
Thank you for your time and for providing enough information to understand what you are asking for.

We could "redirect" on [this line](https://github.com/rabbitmq/rabbitmq-management/blob/master/priv/www/js/main.js#L1303) but I am not convinced this would be less surprising. So let's assume that there is no clear answer and we should wait for more requests like before we decide to go with automatic redirection.

A more conventional and hopefully less surprising thing to do would be to render a 404/403/401 template. If you'd like to see that happen, please submit a PR or file a new issue.
