### ISSUE TITLE
UI is not working on Firefox

### ISSUE THREAD

**Issue by gnumoksha** [rabbitmq/rabbitmq-management#820]
* RabbitMQ version: 3.8.4
* Erlang version: 23.0.2
* Operating system, version, and patch level: `Ubuntu 18.04.1 LTS`
 * Browser and its version: Firefox Developer Edition 78.0b4 (64-bits)
 * What management UI page was used (if applicable): http://host:15672/#/queues or any other
 * Errors reported in the JavaScript console (if any)
```
Uncaught ReferenceError: login_route is not defined
    <anonymous> http://host:15672/js/dispatcher.js:17
    dispatcher http://host:15672/js/main.js:26
    Application http://host:15672/js/sammy-0.7.6.min.js:5
    start_app http://host:15672/js/main.js:173
    dispatcher_add http://host:15672/js/main.js:20
    <anonymous> http://host:15672/js/shovel.js:1
dispatcher.js:17:5
```

**Comment by magroski** [comment]
For context, this happend after rabbitmq was upgraded from 3.7 to 3.8

**Comment by michaelklishin** [comment]
[Clear your browser's cache](https://www.rabbitmq.com/upgrade.html#rabbitmq-plugins-compatibility)

**Comment by gnumoksha** [comment]
> [Clear your browser's cache](https://www.rabbitmq.com/upgrade.html#rabbitmq-plugins-compatibility)

- local storage - didn't work
- session storage - didn't work
- cookies - didn't work
- Clear browser cache - I usually do this using `ctrl + F5`, which didn't work. It was necessary to [delete all browser cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_clear-the-cache), losing all sessions (deleting only based on the RabbitMQ domain also didn't work).

**Comment by michaelklishin** [comment]
Asset cache (JS files specifically) is what makes a difference.
