### ISSUE TITLE
When upgrading to a new version, JS is cached

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-management#824]
* RabbitMQ version: 3.8.5
* Erlang version: 21.3.6

I find that when I upgrade RabbitMQ from one version to the next and the JS has changed in the management plugin, browser caches prevent the new JS from being loaded. In upgrading from 3.8.2 to 3.8.5 the following is what a user sees before clearing their cache:

![Screen Shot 2020-06-17 at 10 21 33 AM](https://user-images.githubusercontent.com/49469/84910229-9f1ef800-b084-11ea-826d-2ebf27a03ceb.png)

A better user experience would be to use cache-busting query arguments or version specific filenames. This would allow rolling upgrades without the user having to take additional steps to get the UI to work properly in their browser.

**Comment by michaelklishin** [comment]
This will be addressed with a new version of the UI. `erlang.mk` does not really offer any asset processing capabilities and any major changes to the UI side are hard to justify.
