### ISSUE TITLE
JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by rzajac** [rabbitmq/rabbitmq-management#825]
When I do

`rabbitmqadmin get queue=my_queue ackmode=ack_requeue_true count=4`

I get error:

```Traceback (most recent call last):
  File "./bin/rabbitmqadmin", line 1193, in <module>
    main()
  File "./bin/rabbitmqadmin", line 532, in main
    method()
  File "./bin/rabbitmqadmin", line 697, in invoke_get
    result = self.post(uri, json.dumps(upload))
  File "./bin/rabbitmqadmin", line 567, in post
    return self.http("POST", "%s/api%s" % (self.options.path_prefix, path), body)
  File "./bin/rabbitmqadmin", line 635, in http
    die(json.loads(resp.read())['reason'])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'```

My management plugin version: v3.8.5 rabitmq version  3.6.15

All messages in the queue are JSON stroings. I tried to set `encoding` parameter to string or auto but it does not help. What should I do to get the message?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
You cannot have management plugin 3.8.5 with RabbitMQ 3.6.15. Something here does not add up.

**Comment by michaelklishin** [comment]
I cannot reproduce using a 3.8.5 node and `rabbitmqadmin` from the tip of `v3.8.x`:

```
rabbitmqadmin get queue=cq.1 ackmode=ack_requeue_true count=4                                                                                                                                                       1 ↵
+-------------+----------+---------------+---------+---------------+------------------+-------------+
| routing_key | exchange | message_count | payload | payload_bytes | payload_encoding | redelivered |
+-------------+----------+---------------+---------+---------------+------------------+-------------+
| cq.1        |          | 6             | {}      | 2             | string           | False       |
| cq.1        |          | 5             | {}      | 2             | string           | False       |
| cq.1        |          | 4             | {}      | 2             | string           | False       |
| cq.1        |          | 3             | {}      | 2             | string           | False       |
+-------------+----------+---------------+---------+---------------+------------------+-------------+
```

**Comment by michaelklishin** [comment]
So you very likely use a `rabbitmqadmin` version that's not fully compatible with Python 3 and/or the HTTP API it targets. [`rabbitmqadmin` doc guide](https://www.rabbitmq.com/management-cli.html) explains how to obtain the version from the node itself or at least get the latest one from GitHub.
