### ISSUE TITLE
Possible Cross site scripting in main.js

### ISSUE THREAD

**Issue by digennarot** [rabbitmq/rabbitmq-management#85]
After I run security scan against rmq managment console i found this possible security issues:

Line 30:Unsafe client output calling window.location.replace() with tainted arg
Line 29:Assignment of "location" to user-controlled value
Line 29:Result of taint-preserving function call on user-controlled value
Line 29:"location.substr" is controlled by the user

Can we fix it ?

**Comment by michaelklishin** [comment]
@digennarot that is an undocumented feature that allows logins from arguments in the URI hash, as opposed to filling out the form. Until we get OAuth 2 support, which will take a while, there is simply no alternative to this and certain products pretty much require this kind of login.

Take a look at the code, it doesn't do anything sophisticated. There is a worse aspect of it: that credentials have to be passed in the URI if you need to use this feature. But it is not required, not advertised anywhere, and OAuth 2 is the only realistic solution we know of.

So yes, we can fix it. By removing the need for it entirely.

**Comment by smclewin** [comment]
For anybody finding this thread years later, a PR to address this can be found in #748
