### ISSUE TITLE
API request to aliveness-test when message-ttl is 0 results in a 500

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-management#855]
Reported here:

https://groups.google.com/d/topic/rabbitmq-users/UgXnKBZEaA4/discussion

**Comment by michaelklishin** [comment]
A policy that sets message TTL to 0 (discards all messages) violates a very fundamental assumption of this check: that published messages can be consumed. I'd say it works as expected but we should respond with a `503` in that case, much like we do in the checks introduced in #854.
