### ISSUE TITLE
RabbitMQ publish fails with HTTP 500. RabbitMQ server not working with supported Erlang/OTP version.

### ISSUE THREAD

**Issue by karan-kaushik-searce** [rabbitmq/rabbitmq-management#863]
Hi Team
I tried installing RabbitMQ v3.7.8 on a cluster of 3 nodes, Centos 7. To install Erlang, I made use of the following yum repo, mentioned here, https://github.com/rabbitmq/erlang-rpm#erlang-22x-from-packagecloud
```
# In /etc/yum.repos.d/rabbitmq_erlang.repo
[rabbitmq_erlang]
name=rabbitmq_erlang
baseurl=https://packagecloud.io/rabbitmq/erlang/el/7/$basearch
repo_gpgcheck=1
gpgcheck=1
enabled=1
# PackageCloud's repository key and RabbitMQ package signing key
gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey
       https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[rabbitmq_erlang-source]
name=rabbitmq_erlang-source
baseurl=https://packagecloud.io/rabbitmq/erlang/el/7/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
# PackageCloud's repository key and RabbitMQ package signing key
gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey
       https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```
Following was the final configuration:
OS: Centos 7
RabbitMQ: 3.7.8
Erlang: 23.1.1

Although this worked out fine, the issue came when I tried publishing to one of my queues from the UI, and got a HTTP 500 error. Upon investigating, it turns out the version of Erlang installed (v23.1.1) with RabbitMQ (v3.7.8) was not compatible for management level operations, but supported rabbitmq just enough to not disrupt work.

Resolution: Uninstall Erlang 23.x and install Erlang 21.x, as this is the supported version as per the documentation, https://www.rabbitmq.com/which-erlang.html#intro

Since my rabbitmq cluster was already serving production traffic, I followed the simple steps to uninstalled Erlang using rpm command and install the supported version via yum.

Commands to uninstall Erlang 23.x
```
rpm -qa | grep erlang
rpm -e --nodeps erlang-23.1.1-1.el7.x86_64
```
This helped me remove Erlang without disrupting my rabbitmq installation  
  
Yum repo used for installing Erlang 21.x, https://github.com/rabbitmq/erlang-rpm#erlang-21x-from-bintray
```
# In /etc/yum.repos.d/rabbitmq-erlang.repo
[rabbitmq-erlang]
name=rabbitmq-erlang
baseurl=https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/7
gpgcheck=1
gpgkey=https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
repo_gpgcheck=0
enabled=1
```

New Configuration:
OS: Centos 7
RabbitMQ: 3.7.8
Erlang: 21.3.8.17

However, the rabbitmq server would fail to start after the installation of the supported version of Erlang, due to dependencies.
```
[root@rabbitmq-server-03 ~]#systemctl status rabbitmq-server -l
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-10-28 10:44:58 UTC; 9s ago
  Process: 3250836 ExecStop=/usr/sbin/rabbitmqctl shutdown (code=exited, status=0/SUCCESS)
  Process: 3251174 ExecStart=/usr/sbin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 3251174 (code=exited, status=1/FAILURE)
Oct 28 10:44:56 rabbitmq-server-03 rabbitmq-server[3251174]: rabbitmq_web_dispatch]}}
Oct 28 10:44:56 rabbitmq-server-03 rabbitmq-server[3251174]: Log file(s) (may contain more information):
Oct 28 10:44:56 rabbitmq-server-03 rabbitmq-server[3251174]: /var/log/rabbitmq/rabbit@rabbitmq-server-03.log
Oct 28 10:44:56 rabbitmq-server-03 rabbitmq-server[3251174]: /var/log/rabbitmq/rabbit@rabbitmq-server-03_upgrade.log
Oct 28 10:44:58 rabbitmq-server-03 rabbitmq-server[3251174]: {"init terminating in do_boot",{error,{missing_dependencies,[inets,mnesia,ssl],[amqp10_client,rabbitmq_auth_backend_http,rabbitmq_aws,rabbitmq_management,rabbitmq_management_agent,rabbitmq_peer_discovery_aws,rabbitmq_peer_discovery_common,rabbitmq_trust_store,rabbitmq_web_dispatch]}}}
Oct 28 10:44:58 rabbitmq-server-03 rabbitmq-server[3251174]: init terminating in do_boot ({error,{missing_dependencies,[inets,mnesia,ssl],[amqp10_client,rabbitmq_auth_backend_http,rabbitmq_aws,rabbitmq_management,rabbitmq_management_agent,rabbitmq_peer_discover
Oct 28 10:44:58 rabbitmq-server-03 systemd[1]: rabbitmq-server.service: main process exited, code=exited, status=1/FAILURE
Oct 28 10:44:58 rabbitmq-server-03 systemd[1]: Failed to start RabbitMQ broker.
Oct 28 10:44:58 rabbitmq-server-03 systemd[1]: Unit rabbitmq-server.service entered failed state.
Oct 28 10:44:58 rabbitmq-server-03 systemd[1]: rabbitmq-server.service failed.
```
To overcome this, I uninstalled Erlang, and installed it again using the following rpm from erlang-solutions, https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_21.3.8.17-1~centos~7_amd64.rpm

The problem still persisted, and the rabbitmq-server would not startup.

Workaround employed: Install Erlang 22.x base version.

After a lot of trial and error, I was able to get rabbitmq-server working with Erlang v22.1, however, the issue with publishing messages to queues still persisted.

I used rabbitmqadmin, to try publishing from the CLI, but was met with the same HTTP 500 error.
```
[root@rabbitmq-server-03 ~]# rabbitmqadmin -V / publish exchange=test-queue routing_key=test-queue payload="hello, world"
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmqadmin", line 1081, in <module>
    main()
  File "/usr/local/bin/rabbitmqadmin", line 452, in main
    method()
  File "/usr/local/bin/rabbitmqadmin", line 607, in invoke_publish
    resp = json.loads(self.post(uri, json.dumps(upload)))
  File "/usr/local/bin/rabbitmqadmin", line 488, in post
    return self.http("POST", "%s/api%s" % (self.options.path_prefix, path), body)
  File "/usr/local/bin/rabbitmqadmin", line 569, in http
    % (resp.status, resp.reason, path, resp.read()))
Exception: Received 500 Internal Server Error for path /api/exchanges/%2F/selective-message/publish
```

Rabbitmqadmin was downloaded from the URL, http://localhost:15672/cli/rabbitmqadmin

Final configuration:
OS: Centos 7
RabbitMQ: 3.7.8
Erlang: 22.1

Output for the command, `rabbitmq-plugins list` (only mentioning enabled plugins)
```
Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@rabbitmq-server-03
[E*] rabbitmq_management               3.7.8
[e*] rabbitmq_management_agent         3.7.8
[e*] rabbitmq_web_dispatch             3.7.8
```

Need help/clarity with the following items:
1. Why would rabbitmq-server not work with the supported version of Erlang mentioned in the documentation, https://www.rabbitmq.com/which-erlang.html#intro
2. How can I overcome publishing messages to queues with the version I have installed.

Please do let me know if additional information would be needed. Thanks in advance.

**Comment by michaelklishin** [comment]
See [server logs for clues](https://www.rabbitmq.com/logging.html). The embedded HTTP Web server we use does not log the entire stack trace in 3.7 or 3.8 up to future `3.8.10` but it can be enough.

RabbitMQ 3.7 has gone out of support in [May 2020](https://www.rabbitmq.com/versions.html). `3.7.8` is 20 patch releases behind even in that series. Sorry but we won't investigate this. Please [upgrade](https://www.rabbitmq.com/upgrade.html).

**Comment by michaelklishin** [comment]
The first RabbitMQ release to support Erlang 22 was [`3.7.15`](https://www.rabbitmq.com/changelog.html). See the [Erlang Compatibility Guide](https://www.rabbitmq.com/which-erlang.html) for a matrix of compatible versions. Trying versions randomly will only lead to wasted time and frustration. According to that table, `3.7.8` supports Erlang 19.3 through 21.x.

Our team maintains an Erlang RPM and there are reasonably recent [`21.3.x` releases](https://github.com/rabbitmq/erlang-rpm/releases/) available for CentOS 6 and 8. However, RabbitMQ 3.8 has recently dropped support for Erlang 21.3, so these releases will be produced for a limited amount of time.

**Comment by michaelklishin** [comment]
Finally, publishing over HTTP API is technically possible but this option should only be used when there is absolutely no other way to use a "real" messaging protocol. `rabbitmqadmin publish` is not something we would recommend for any kind of production use.
