### ISSUE TITLE
queue stats `idle_since` timestamp is in node local timezone, with no timezone indication

### ISSUE THREAD

**Issue by triccardi-systran** [rabbitmq/rabbitmq-management#92]
Hi,
I'm trying to detect via the management REST APi when a queue has been inactive for a certain period of time (inactive == no message was published, and no message in queue or in flight).

The queue stats `idle_since` field, when present, seems to be a good fit, even if I don't have a real definition, except in a 2013 ML message from Simon MacMullen:
> That reports on the last time anything contacted the queue to wake it up - this would include publishing,  consuming, (re)declaring, or listing it with rabbitmqctl (not mgmt). 

(This means I may have false negative using this, but it's not a real issue for my use-case).

The issue is that this field is a string timestamp using node local timezone, with no timezone indication.
I would have expected a UTC timestamp (with an explicit marker for it), or at least a timezone marker to compute back UTC time, for comparisons.

1/ Could this be fixed, ie specify the timezone in the string, or change to UTC (maybe add an additional field to avoid any breaking change) ?

2/ If not, how could I determine the node timezone to recompute the UTC date?

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users.

`idle_since` is a leaked implementation detail. Its format can be changed but it's already to late to do that for 3.6.
