### ISSUE TITLE
Validate (limit) user-provided query parameters, e.g. lengths_age

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-management#97]
`lengths_age` and `lengths_incr ` need to be validated and capped the same way page size is.

**Comment by essen** [comment]
What max values should i put?

**Comment by essen** [comment]
Nevermind that. If I understand right you want to limit the number of records returned by queries that use those values, not limiting the records themselves? Ie if we request an hour of data with a sample by minutes that's 60, and perhaps we can have a hard limit of samples of 500 or something? Am I understanding right?

**Comment by michaelklishin** [comment]
Currently it is possible to enter an arbitrarily high number and potentially put a serious strain on the management node. We need to limit our exposure to that.

**Comment by essen** [comment]
Understood, I can reproduce (even did an OOM, oops). What I was saying in the previous comment should be at least a first step.

**Comment by michaelklishin** [comment]
Fixed in #106.
